<?php
// General Translation file (i18n) for ControlPanel gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: 注册"
 * "Last-Translator: shalibaji <freeyiyi@yahoo.co.uk>"
 * "Language-Team: ZH"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_ZH_REGISTRY_NAME', "注册");
define('_ZH_REGISTRY_DESCRIPTION', "Jaws信息注册系统.");

/* ACLs */
define('_ZH_REGISTRY_ACL_MANAGEREGISTRY', "编辑注册");

/* Registry */
define('_ZH_REGISTRY_REGISTRY', "注册");
define('_ZH_REGISTRY_ACL', "ACL Keys");
define('_ZH_REGISTRY_DISCLAIMER', "<em>警告:</em> 这一页用来编辑网站属性，不是会员注册，请注意！不懂请勿动！");
define('_ZH_REGISTRY_KEY', "Key");
define('_ZH_REGISTRY_VALUE', "意义");

define('_ZH_REGISTRY_EDIT_REGISTRY', "编辑注册keys");
define('_ZH_REGISTRY_EDIT_ACL', "编辑ACL keys");


define('_ZH_REGISTRY_KEY_SAVED', "key被改变并且保存");
