<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Phoo"
 * "Last-Translator: Karl-Gustav Freding <gusse500@gusse.no>"
 * "Language-Team: NB"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_NB_PHOO_NAME', "Bildeorganisering");
define('_NB_PHOO_DESCRIPTION', "En enkel bildeorganiserer for nettstedet");
define('_NB_PHOO_DEFAULT_VIEW', "Standard visning");
define('_NB_PHOO_ALBUM_LIST', "Albumliste");
define('_NB_PHOO_PHOTOBLOG', "Bildeblogg");
define('_NB_PHOO_RANDOM_IMAGE', "Tilfeldig bilde");
define('_NB_PHOO_RANDOM_IMAGE_DESC', "Viser et tilfeldig bilde fra hvilket som helst album");
define('_NB_PHOO_MOBLOG', "Moblogg");
define('_NB_PHOO_MOBLOG_DESC', "Viser Mobloggalbumet");
define('_NB_PHOO_ALBUMS', "Albumer");
define('_NB_PHOO_ALBUMS_DESC', "Vis alle albumene");
define('_NB_PHOO_UNKNOW_ALBUM', "Ikke funnet i noe album");
define('_NB_PHOO_WITHOUT_ALBUM', "Foreldreløse bilder");
define('_NB_PHOO_WITHOUT_ALBUM_DESCRIPTION', "Bilder som ikke tilhører noe album");
define('_NB_PHOO_NEW_ALBUM', "Nytt album");
define('_NB_PHOO_EDIT_ALBUM', "Rediger album");
define('_NB_PHOO_ALBUM_CREATION_DATE', "Opprettelsesdato {0}");
define('_NB_PHOO_EDIT_PHOTO', "Rediger bilde");
define('_NB_PHOO_FIRST', "Første");
define('_NB_PHOO_PREVIOUS', "Forrige");
define('_NB_PHOO_NEXT', "Neste");
define('_NB_PHOO_LAST', "Siste");
define('_NB_PHOO_THUMBS', "Miniatyrbilde");
define('_NB_PHOO_WIDTH', "Bredde");
define('_NB_PHOO_HEIGHT', "Høyde");
define('_NB_PHOO_SIZE', "Størrelse");
define('_NB_PHOO_APERTURE', "Åpning");
define('_NB_PHOO_EXPOSURE_TIME', "Visningstid");
define('_NB_PHOO_FOCAL_LENGTH', "Fokallengde");
define('_NB_PHOO_UNKNOWN_CAM', "Ukjent kamera");
define('_NB_PHOO_LEAVE_COMMENT', "Kommenter");
define('_NB_PHOO_PHOTOS', "Bilder");
define('_NB_PHOO_PHOTO', "Bilde {0}");
define('_NB_PHOO_PHOTO_COUNTER', "Bilde {0} av {1}");
define('_NB_PHOO_PHOTOS_COUNT', "{0} bilder");
define('_NB_PHOO_COMMENTS', "Kommentarer");
define('_NB_PHOO_ADDITIONAL_SETTINGS', "Tilleggsinnstillinger");
define('_NB_PHOO_IMPORT', "Importer");
define('_NB_PHOO_NUM_PHOTOS_ALBUM', "{0} bilder i albumet");
define('_NB_PHOO_UPLOAD_PHOTOS', "Last opp bilde");
define('_NB_PHOO_EDIT_DESCRIPTION', "Rediger beskrivelse");
define('_NB_PHOO_DELETE_ALBUM_CONFIRM', "Er du sikker på å slette dette albumet?");
define('_NB_PHOO_NOT_FOUND', "Ikke funnet");
define('_NB_PHOO_NOT_PUBLISHED', "Ikke publisert");
define('_NB_PHOO_START_UPLOADING_PHOTOS', "Start opplasting av bilder");
define('_NB_PHOO_INEXISTENT_ALBUM', "Albumet eksisterer ikke");
define('_NB_PHOO_EMPTY_ALBUMSET', "Det er ingen albumer");
define('_NB_PHOO_PHOTO_TITLE', "Bildetittel");
define('_NB_PHOO_PHOTO_DESCRIPTION', "Bildebeskrivelse");
define('_NB_PHOO_POSTED_BY', "Lagt til av");
define('_NB_PHOO_ALBUM', "Album");
define('_NB_PHOO_ALLOW_COMMENTS', "Tillat kommentarer");
define('_NB_PHOO_STATUS', "Status");
define('_NB_PHOO_HIDDEN', "Skjult");
define('_NB_PHOO_PUBLISHED', "Publisert");
define('_NB_PHOO_DELETE_PHOTO_CONFIRM', "Er du sikker på å slette dette bildet?");
define('_NB_PHOO_UPLOAD_FAILURE', "Kunne ikke laste opp bildet");
define('_NB_PHOO_ALBUM_NAME', "Albumnavn");
define('_NB_PHOO_ALBUM_DESC', "Albumbeskrivelse");
define('_NB_PHOO_CREATE_NEW_ALBUM', "Opprett nytt album");
define('_NB_PHOO_DELETE_ALBUM', "Slett album");
define('_NB_PHOO_KEEP_ORIGINAL', "Behold originale bilde");
define('_NB_PHOO_SHOW_EXIF_INFO', "Vis EXIF informasjon");
define('_NB_PHOO_EXIF_INFO', "EXIF informasjon");
define('_NB_PHOO_SAVE_CHANGES', "Lagre forandringer");
define('_NB_PHOO_COMMENTS_WHERE', "Kommentarer var");
define('_NB_PHOO_ID', "ID er");
define('_NB_PHOO_TITLE_CONTAINS', "tittel inneholder");
define('_NB_PHOO_COMMENT_CONTAINS', "kommentarer inneholder");
define('_NB_PHOO_NAME_CONTAINS', "navn inneholder");
define('_NB_PHOO_EMAIL_CONTAINS', "E-post inneholder");
define('_NB_PHOO_URL_CONTAINS', "nettadresse inneholder");
define('_NB_PHOO_IP_CONTAINS', "IPadresse inneholder");
define('_NB_PHOO_FILTER', "Filter");
define('_NB_PHOO_IP_ADDRESS', "IP adresse");
define('_NB_PHOO_COMMENT', "Kommentar");
define('_NB_PHOO_UPDATE_COMMENT', "Oppdater kommentaren");
define('_NB_PHOO_DELETE_COMMENT', "Slett kommentaren");
define('_NB_PHOO_REPLY', "Svar");
define('_NB_PHOO_SEND_COMMENT', "Send kommentaren");
define('_NB_PHOO_RECENT_COMMENTS', "Siste kommentarer på bilder");
define('_NB_PHOO_RECENT_COMMENTS_DESC', "Viser sammendrag av siste kommentarer.");
define('_NB_PHOO_SAVE_SETTINGS', "Lagre innstillinger");
define('_NB_PHOO_RESIZE_METHOD', "Metode for å endre størrelse");
define('_NB_PHOO_DEFAULT_STATUS', "Standard status");
define('_NB_PHOO_MOBLOG_ALBUM', "Moblogg album");
define('_NB_PHOO_MOBLOG_LIMIT', "Moblogg begrensing");
define('_NB_PHOO_PHOTOBLOG_ALBUM', "Bildeblogg album");
define('_NB_PHOO_PHOTOBLOG_LIMIT', "Bildeblogg begrensing");
define('_NB_PHOO_THUMBNAIL_LIMIT', "Bilder pr. side");
define('_NB_PHOO_FULL_ALBUM', "Fullt album");
define('_NB_PHOO_READY_TO_IMPORT', "Klar til å importere {0} bilder");
define('_NB_PHOO_IMPORT_MESSAGE', "Importer valgte bilde til");
define('_NB_PHOO_NO_IMAGES_TO_IMPORT', "Ingen bilder å importere");
define('_NB_PHOO_IMPORT_INSTRUCTIONS', "Kopier bildet til mappen data/phoo/import og gå tilbake til dette valget for å importere dine bilder.");
define('_NB_PHOO_IMPORTING', "Importerer");
define('_NB_PHOO_IMPORTING_WARNING', "Ikke lukk dette vinduet mens importeringen pågår");
define('_NB_PHOO_FINISHED', "Ferdig");
define('_NB_PHOO_DELETE_MASSIVE_COMMENTS', "Er du sikker på å slette dette/disse kommentaren(e)");
define('_NB_PHOO_MODERATE_COMMENTS', "Moderere kommentarene");
define('_NB_PHOO_COMMENT_IS_SPAM', "Kommentarer er blitt markert som søppelpost.");
define('_NB_PHOO_COMMENT_IS_WAITING', "Kommentaren venter på moderering.");
define('_NB_PHOO_ALBUMS_ORDER_TYPE', "Type rekkefølge for albumene");
define('_NB_PHOO_PHOTOS_ORDER_TYPE', "Type rekkefølge for bildene");
define('_NB_PHOO_ORDER_TYPE_BY_CREATETIME', "Med opprettelsestid");
define('_NB_PHOO_ORDER_TYPE_BY_NAME', "Med navn");
define('_NB_PHOO_ORDER_TYPE_BY_ID', "Med ID");
define('_NB_PHOO_ADD_ANOTHER_PHOTO', "Legg til annet bilde");
define('_NB_PHOO_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_NB_PHOO_ALBUM_EMPTY', "Tøm album");
define('_NB_PHOO_CSS_CLASS', "CSS klasse");
define('_NB_PHOO_THUMB', "Miniatyr");
define('_NB_PHOO_MEDIUM', "Medium");
define('_NB_PHOO_ORIGINAL', "Originalt");
define('_NB_PHOO_INSERTIMAGE', "Sett inn bilde");
define('_NB_PHOO_IMAGE_LABEL', "Bilde");
define('_NB_PHOO_SELECT_OTHER_IMAGE', "Velg annet bilde");
define('_NB_PHOO_INCLUDE_LINK_TO_ALBUM', "Inkluder lenke til albumet");
define('_NB_PHOO_ACL_DEFAULT', "Administrer bildeorganisering");
define('_NB_PHOO_ACL_ADDPHOTOS', "Legg til nytt bilder");
define('_NB_PHOO_ACL_DELETEPHOTOS', "Slett bilder");
define('_NB_PHOO_ACL_MANAGEPHOTOS', "Behandle bilder");
define('_NB_PHOO_ACL_MODIFYOTHERSPHOTOS', "Endre bilder eid av andre");
define('_NB_PHOO_ACL_MANAGECOMMENTS', "Behandle kommentarer");
define('_NB_PHOO_ACL_MANAGEALBUMS', "Behandle albumer");
define('_NB_PHOO_ACL_SETTINGS', "Endre innstillinger");
define('_NB_PHOO_ACL_IMPORT', "Importer bilder");
define('_NB_PHOO_ERROR_ADVANCEDSEARCH_QUERY', "Kunne ikke utføre Avansert Søkespørring");
define('_NB_PHOO_ERROR_GETMOBLOG', "Kunne ikke utføre Moblogg spørringen");
define('_NB_PHOO_ERROR_ALBUMLIST', "Kunne ikke hente albumlisten");
define('_NB_PHOO_ERROR_RANDOMIMAGE', "Kunne ikke velge et tilfeldig bilde");
define('_NB_PHOO_ERROR_ALBUMINFO', "Kunne ikke hente informasjonen for et album");
define('_NB_PHOO_ERROR_ALBUMS', "Kunne ikke velge album av {0}");
define('_NB_PHOO_ERROR_GETALBUM', "Kunne ikke hente albumet");
define('_NB_PHOO_ERROR_GETIMAGE', "Kunne ikke hente bildet");
define('_NB_PHOO_ERROR_GETIMAGEENTRY', "Kunne ikke hente bildeelementer");
define('_NB_PHOO_ERROR_CANT_UPLOAD_PHOTO_EXT', "Det er ikke en gyldig fil. Bruk (gif|jpeg|png)");
define('_NB_PHOO_ERROR_CANT_UPDATE_PHOTO', "Kunne ikke oppdatere bildet");
define('_NB_PHOO_ERROR_CANT_UPLOAD_PHOTO', "Kunne ikke laste opp bildet");
define('_NB_PHOO_ERROR_CANT_DELETE_PHOTO', "Kunne ikke slette bildet");
define('_NB_PHOO_ERROR_CANT_ADD_ENTRY_TO_ALBUM', "Kunne ikke legge elementer til albumet");
define('_NB_PHOO_ERROR_GETASPORTRAIT', "Kunne ikke hente albumet som et portrett");
define('_NB_PHOO_ERROR_ALBUM_NOT_UPDATED', "Kunne ikke oppdatere albumet");
define('_NB_PHOO_ERROR_ALBUM_NOT_DELETED', "Kunne ikke slette albumet");
define('_NB_PHOO_ERROR_ALBUM_NOT_CREATED', "Kunne ikke opprette albumet");
define('_NB_PHOO_ERROR_GETCOMMENTS', "Kunne ikke hente kommentarene");
define('_NB_PHOO_ERROR_RECENTCOMMENTS', "Kunne ikke hente de siste kommentarene");
define('_NB_PHOO_ERROR_FILETEREDCOMMENTS', "Kunne ikke filtrere kommentarene");
define('_NB_PHOO_ERROR_GETCOMMENT', "Kunne ikke hente kommentaren");
define('_NB_PHOO_ERROR_CANT_ADD_COMMENT', "Kunne ikke legge til kommentaren");
define('_NB_PHOO_ERROR_CANT_UPDATE_COMMENT', "Kunne ikke oppdatere kommentaren");
define('_NB_PHOO_ERROR_CANT_DELETE_COMMENT', "Kunne ikke slette kommentaren");
define('_NB_PHOO_ERROR_CANT_UPDATE_SETTINGS', "Kunne ikke oppdatere innstillingene");
define('_NB_PHOO_ERROR_CANT_DELETE_IMAGE', "Kunne ikke slette bildet");
define('_NB_PHOO_ERROR_CANT_FETCH_SETTINGS', "Kunne ikke hente innstillingene");
define('_NB_PHOO_ALBUM_CREATED', "Albumet er opprettet");
define('_NB_PHOO_ALBUMS_UPDATED', "Albumene er oppdatert");
define('_NB_PHOO_ALBUM_UPDATED', "Albumet er oppdatert");
define('_NB_PHOO_ALBUM_DELETED', "Albumet er slettet");
define('_NB_PHOO_PHOTO_ADDED', "Bildet er lagt til");
define('_NB_PHOO_PHOTO_UPDATED', "Bildet er oppdatert");
define('_NB_PHOO_PHOTO_DELETED', "Bildet er slettet");
define('_NB_PHOO_COMMENT_UPDATED', "Kommentaren er oppdatert");
define('_NB_PHOO_COMMENT_DELETED', "Kommentaren er slettet");
define('_NB_PHOO_SETTINGS_UPDATED', "Innstillingene er oppdatert");
