<?php
// General Translation file (i18n) for ControlPanel gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Registry"
 * "Last-Translator: "
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_REGISTRY_NAME', "Registry");
define('_EN_REGISTRY_DESCRIPTION', "The Jaws registry.");

/* ACLs */
define('_EN_REGISTRY_ACL_MANAGEREGISTRY', "Edit the registry");

/* Registry */
define('_EN_REGISTRY_REGISTRY', "Registry");
define('_EN_REGISTRY_ACL', "ACL Keys");
define('_EN_REGISTRY_DISCLAIMER', "<em>Warning:</em> Editing values on this page may cause your site to stop working.");
define('_EN_REGISTRY_KEY', "Key");
define('_EN_REGISTRY_VALUE', "Value");

define('_EN_REGISTRY_EDIT_REGISTRY', "Edit registry keys");
define('_EN_REGISTRY_EDIT_ACL', "Edit ACL keys");


define('_EN_REGISTRY_KEY_SAVED', "They key has been changed and saved");
