<?php
// General Translation file  (i18n) for JMS gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Jms"
 * "Last-Translator: Helgi Þormar Þorbjörnsson"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_JMS_NAME', "Component Management");
define('_EN_JMS_DESCRIPTION', "Manage all components in Jaws.");
define('_EN_JMS_INSTALLED_COMPONENTS', "Installed components");
define('_EN_JMS_UNINSTALLED_COMPONENTS', "Uninstalled components");
define('_EN_JMS_OUTDATED_COMPONENTS', "Outdated components");
define('_EN_JMS_KEY', "Key");
define('_EN_JMS_VALUE', "Value");
define('_EN_JMS_INFORMATION', "Information");
define('_EN_JMS_VERSION', "Version");
define('_EN_JMS_INSTALL', "Install");
define('_EN_JMS_UNINSTALL', "Uninstall");
define('_EN_JMS_PURGE', "Purge");
define('_EN_JMS_UNINSTALLED', "uninstalled");
define('_EN_JMS_PURGED', "purged");
define('_EN_JMS_UPDATE', "Update");
define('_EN_JMS_ONLY_SHOW', "Only show: ");

/* ACL */
define('_EN_JMS_ACL_MANAGEJMS', "Use component manager");
define('_EN_JMS_ACL_MANAGEGADGETS', "Enable/Disable gadgets");
define('_EN_JMS_ACL_MANAGEPLUGINS', "Enable/Disable plugins");

/* Plugins */
define('_EN_JMS_PLUGINS', "Plugins");
define('_EN_JMS_PLUGINS_INSTALLED_PLUGINS', "Installed plugins");
define('_EN_JMS_PLUGINS_NOTINSTALLED_PLUGINS', "Not installed plugins");

define('_EN_JMS_PLUGINS_PLUGIN', "Plugin");
define('_EN_JMS_PLUGINS_USAGE', "Plugin Usage");
define('_EN_JMS_PLUGINS_NO_EXAMPLE', "No example found");
define('_EN_JMS_PLUGINS_FRIENDLY', "Friendly");
define('_EN_JMS_PLUGINS_NOT_FRIENDLY', "Not friendly");
define('_EN_JMS_PLUGINS_ACCESSKEY', "Access Key");
define('_EN_JMS_PLUGINS_NO_ACCESSKEY', "No access key found");
define('_EN_JMS_PLUGINS_USE_IN', "Plugin usage");
define('_EN_JMS_PLUGINS_SAVED', "Your plugin settings have been saved.");
define('_EN_JMS_PLUGINS_NOTHING', "No plugins");
define('_EN_JMS_PLUGINS_ALWAYS', "Always");
define('_EN_JMS_PLUGINS_ONLY_IN_GADGET', "Only in these pluggable gadgets");
define('_EN_JMS_PLUGINS_ENABLED_OK', "The {0} plugin has been installed sucessfully");
define('_EN_JMS_PLUGINS_ENABLED_FAILURE', "There was a problem installing {0} plugin");
define('_EN_JMS_PLUGINS_NO_SELECTION', "No plugin has been selected, please select one");
define('_EN_JMS_SIDEBAR_DISABLE_PLUGIN', "Disable");
define('_EN_JMS_SIDEBAR_DISABLE_PLUGINS', "Enabled Plugins");
define('_EN_JMS_SIDEBAR_DISABLE_PLUGINS_WAITING', "Plugin waiting to be disabled");
define('_EN_JMS_PLUGINS_DISABLE_FAILURE', "Could not disable plugin");
define('_EN_JMS_PLUGINS_DISABLE_OK', "Plugin uninstalled sucessfully");
define('_EN_JMS_PLUGINS_PLUGIN_DOESNT_EXISTS', "The plugin {0} does not exists");
define('_EN_JMS_PLUGINS_PLUGIN_CANT_HAVE_NAME_CORE', "The plugin can't have the name Core, it's reserved for Jaws.");
define('_EN_JMS_PLUGINS_UNINSTALL_CONFIRM', "Do you want to uninstall this plugin ?");

/* Gadgets */
define('_EN_JMS_GADGETS', "Gadgets");
define('_EN_JMS_GADGETS_INSTALLED_GADGETS', "Installed gadgets");
define('_EN_JMS_GADGETS_NOTINSTALLED_GADGETS', "Not installed gadgets");
define('_EN_JMS_GADGETS_NOTHING', "No gadgets");
define('_EN_JMS_GADGETS_REGISTRY', "Registry Keys");
define('_EN_JMS_GADGETS_ACL', "ACL Rules");
define('_EN_JMS_GADGETS_DOESNT_EXISTS', "The gadget {0} does not exists");
define('_EN_JMS_GADGETS_UNINSTALL_CONFIRM', "Do you want to uninstall the gadget? This option does not delete data");
define('_EN_JMS_GADGETS_PURGE_CONFIRM', "Do you want to purge the gadget? This option will uninstall and delete data");
define('_EN_JMS_GADGETS_NOT_EXISTS', "The gadget does not exists");
define('_EN_JMS_GADGETS_NO_SELECTION', "No gadget has been selected, please select one");
define('_EN_JMS_GADGETS_ENABLED_OK', "The {0} gadget has been installed sucessfully");
define('_EN_JMS_GADGETS_ENABLED_FAILURE', "There was a problem installing {0} gadget");
define('_EN_JMS_GADGETS_DISABLE_OK', "The {0} gadget has been uninstalled successfully");
define('_EN_JMS_GADGETS_DISABLE_FAILURE', "There was a problem uninstalling {0} gadget");
define('_EN_JMS_GADGETS_UPDATED_OK', "The {0} gadget has been updated successfully");
define('_EN_JMS_GADGETS_UPDATED_FAILURE', "There was a problem updating {0} gadget");
define('_EN_JMS_GADGETS_UPDATED_NO_NEED', "There is no need to update the {0} gadget");
define('_EN_JMS_GADGETS_REQUIRES_X_GADGET', "{0} requires these gadgets to be installed to work: {1}");
define('_EN_JMS_GADGETS_REQUIRES_X_DEPENDENCY', "{0} can't be {2} because {1} gadget(s) depends on it");

/* Sidebar */
define('_EN_JMS_SIDEBAR_ENABLE', "Enable");
define('_EN_JMS_SIDEBAR_DISABLE', "Disable");

/* Gadgets Sidebar */
define('_EN_JMS_SIDEBAR_DISABLED_GADGETS', "Disabled Gadgets");
define('_EN_JMS_SIDEBAR_GADGETS_WAITING', "There are gadgets waiting to be enabled:");
define('_EN_JMS_SIDEBAR_ENABLED_GADGETS', "Enabled Gadgets");
define('_EN_JMS_SIDEBAR_DISABLE_GADGETS_WAITING', "There are gadgets you can disable:");

/* Gadget disabling errors */
define('_EN_JMS_SIDEBAR_DISABLE_MAIN_FAILURE', "Cannot disable main gadget");

/* Not updated gadgets sidebar */
define('_EN_JMS_SIDEBAR_NOTUPDATED_GADGETS', "Outdated Gadgets");
define('_EN_JMS_SIDEBAR_NOTUPDATED_SUGESTION', "These are gadgets that can be updated now:");

/* Plugins Sidebar */
define('_EN_JMS_SIDEBAR_DISABLED_PLUGINS', "Disabled Plugins");
define('_EN_JMS_SIDEBAR_PLUGINS_WAITING', "There are plugins waiting to be enabled:");
