<?php
// General Translation file  (i18n) for ControlPanel gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Layout"
 * "Last-Translator: Ali Fazelzadeh <afz@php.net>"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_LAYOUT_NAME', "Layout");
define('_EN_LAYOUT_DESCRIPTION', "The Jaws layout.");

/* ACLs */
define('_EN_LAYOUT_ACL_MANAGELAYOUT', "Design layout of your website");
define('_EN_LAYOUT_ACL_MANAGETHEMES', "Select default template of website");

/* Layout */
define('_EN_LAYOUT', "Layout");
define('_EN_LAYOUT_MODE', "Layout Mode");
define('_EN_LAYOUT_MODE_TWOBAR', "Both Sidebars");
define('_EN_LAYOUT_MODE_LEFTBAR', "Left Sidebar");
define('_EN_LAYOUT_MODE_RIGHTBAR', "Right Sidebar");
define('_EN_LAYOUT_MODE_NOBAR', "No Sidebars");
define('_EN_LAYOUT_NEW', "Add Gadget");
define('_EN_LAYOUT_BACK', "Back to Control Panel");
define('_EN_LAYOUT_CHANGE_DW', "When to display this gadget");
define('_EN_LAYOUT_THEME', "Theme");
define('_EN_LAYOUT_THEME_LOCAL', "Local themes");
define('_EN_LAYOUT_THEME_REMOTE', "Non-local themes");
define('_EN_LAYOUT_THEME_CHANGED', "Theme has been changed");
define('_EN_LAYOUT_CONFIRM_DELETE', "Are you sure you want to remove this gadget?");
define('_EN_LAYOUT_REQUESTED_GADGET', "Requested Gadget");
define('_EN_LAYOUT_REQUESTED_GADGET_DESC', "Display the requested page.");
define('_EN_LAYOUT_SECTION_EMPTY', "Empty Section");
define('_EN_LAYOUT_GADGETS', "Gadgets");
define('_EN_LAYOUT_ADD', "Add");
define('_EN_LAYOUT_EDIT_GADGET', "Edit Gadget");
define('_EN_LAYOUT_DISPLAY', "Display");
define('_EN_LAYOUT_DISPLAY_IN', "Display in");
define('_EN_LAYOUT_ALWAYS', "Always");
define('_EN_LAYOUT_NEVER', "Never");
define('_EN_LAYOUT_ONLY_IN_GADGET', "Only in these gadgets");
define('_EN_LAYOUT_ACTIONS', "Actions");
define('_EN_LAYOUT_INDEX', "Index");
define('_EN_LAYOUT_NO_GADGET_ACTIONS', "This gadget does not have layout actions");
define('_EN_LAYOUT_MANAGER', "Layout Manager");

/* Layout Builder */
define('_EN_LAYOUT_BUILDER', "Layout Builder");
define('_EN_LAYOUT_WIDE_SECTION', "Is wide?");
define('_EN_LAYOUT_NEW_MODE', "New mode");
define('_EN_LAYOUT_RENAME_MODE', "Rename mode");
define('_EN_LAYOUT_DEL_MODE', "Delete mode");
define('_EN_LAYOUT_NEW_SECTION', "New section");
define('_EN_LAYOUT_MOVEUP', "Move up");
define('_EN_LAYOUT_MOVEDOWN', "Move down");
define('_EN_LAYOUT_NEW_MODE_MSG', "How you want to name this mode?");
define('_EN_LAYOUT_NEW_SECTION_MSG', "How you want to name this section?");
define('_EN_LAYOUT_MODE_CONFIRM_DELETE', "Delete this layout mode?");
define('_EN_LAYOUT_SECTION_CONFIRM_DELETE', "Delete this layout mode's section?");

/* Responses */
define('_EN_LAYOUT_ELEMENT_ADDED', "The element has been added");
define('_EN_LAYOUT_ELEMENT_UPDATED', "The element has been updated");
define('_EN_LAYOUT_ELEMENT_MOVED', "The element has been moved");
define('_EN_LAYOUT_ELEMENT_DELETED', "The element has been deleted");
define('_EN_LAYOUT_ELEMENT_CHANGE_WHEN', "The element has been updated");

/* Errors */
define('_EN_LAYOUT_ERROR_ELEMENT_ADDED', "Can't add the element");
define('_EN_LAYOUT_ERROR_ELEMENT_UPDATED', "Can't update the element");
define('_EN_LAYOUT_ERROR_ELEMENT_MOVED', "There was an error while moving the element");
define('_EN_LAYOUT_ERROR_ELEMENT_DELETED', "There was an error while deleting the element");
define('_EN_LAYOUT_ERROR_CHANGE_WHEN', "Can't update display when property");
define('_EN_LAYOUT_ERROR_NO_BLOCK', "Theme \"{0}\" doesn't have \"{1}\" block");
