<?php
// General Translation file (i18n) for ControlPanel gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: 设置"
 * "Last-Translator: shalibaji <freeyiyi@yahoo.co.uk>"
 * "Language-Team: ZH"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_ZH_SETTINGS_NAME', "设置");
define('_ZH_SETTINGS_DESCRIPTION', "Jaws系统设置.");

/* ACLs */
define('_ZH_SETTINGS_ACL_MANAGESETTINGS', "常规设置");

/* Site 设置 */
define('_ZH_SETTINGS', "设置");
define('_ZH_SETTINGS_SITE_NAME', "站点名称");
define('_ZH_SETTINGS_SITE_DESCRIPTION', "站点描述");
define('_ZH_SETTINGS_DEFAULT_THEME', "默认主题");
define('_ZH_SETTINGS_DEFAULT_LANGUAGE', "默认语言");
define('_ZH_SETTINGS_MAIN_GADGET', "默认组件");
define('_ZH_SETTINGS_SITE_AUTHOR', "站长名称");
define('_ZH_SETTINGS_COPYRIGHT', "版权");
define('_ZH_SETTINGS_DATE_FORMAT', "时间格式");
define('_ZH_SETTINGS_ALLOW_COMMENTS', "允许评论站点");
define('_ZH_SETTINGS_GRAVATAR', "形象等级");
define('_ZH_SETTINGS_GRAVATAR_G', "G: 儿童友善的内容.");
define('_ZH_SETTINGS_GRAVATAR_PG', "PG: 可能无礼的内容.");
define('_ZH_SETTINGS_GRAVATAR_R', "R: 裸露,暴力,保露的性内容,或者用来吸毒。");
define('_ZH_SETTINGS_GRAVATAR_X', "X: 赤裸的性图片,或者强烈的暴力.");
define('_ZH_SETTINGS_USE_GRAVATAR', "使用gravatar");
define('_ZH_SETTINGS_SAVED', "你的设被保存.");
define('_ZH_SETTINGS_EDITOR', "编辑器");
define('_ZH_SETTINGS_EDITOR_CLASSIC', "一流的Jaws编辑器");
define('_ZH_SETTINGS_EDITOR_TINYMCE', "类似于Word/OpenWriter的编辑器");
define('_ZH_SETTINGS_SHOW_VIEWSITE', "显示站点图标");
define('_ZH_SETTINGS_BASIC_SETTINGS', "基础设置");
define('_ZH_SETTINGS_ADVANCED_SETTINGS', "高级设置");
define('_ZH_SETTINGS_TITLE_SEPARATOR', "页面标题分隔符");
define('_ZH_SETTINGS_TITLE_SEPARATOR_SLASH', "单一的斜线 (/)");
define('_ZH_SETTINGS_TITLE_SEPARATOR_PIPE', "单一的竖线 (|)");
define('_ZH_SETTINGS_TITLE_SEPARATOR_DASH', "单一的横线 (-)");
define('_ZH_SETTINGS_TITLE_SEPARATOR_DOUBLECOLON', "双冒号 (::)");
define('_ZH_SETTINGS_DEFAULT_TITLE_AS_SITEDESC', "站点描述({0})");
define('_ZH_SETTINGS_DATE_CALENDAR', "日历类型");
define('_ZH_SETTINGS_MAILSERVER_SETTINGS', "Mail服务设置");
define('_ZH_SETTINGS_MAILSERVER_USE', "使用邮件服务器");
define('_ZH_SETTINGS_MAILSERVER_HOST', "主机名称");
define('_ZH_SETTINGS_MAILSERVER_PORT', "端口");
define('_ZH_SETTINGS_MAILSERVER_USER', "用户名");
define('_ZH_SETTINGS_MAILSERVER_PASS', "密码");
