<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Phoo"
 * "Last-Translator: Jonathan Hernandez <ion@suavizado.com>"
 * "Language-Team: ES"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_ES_PHOO_NAME', "Organizador de Fotos");
define('_ES_PHOO_DESCRIPTION', "Un bonito organizador de fotos para tu sitio");
define('_ES_PHOO_DEFAULT_VIEW', "Vista Default");
define('_ES_PHOO_ALBUM_LIST', "Lista de Álbums");
define('_ES_PHOO_PHOTOBLOG', "Fotoblog");
define('_ES_PHOO_RANDOM_IMAGE', "Imagen Aleatoria");
define('_ES_PHOO_RANDOM_IMAGE_DESC', "Despliega una imagen aleatoria de cualquier álbum");
define('_ES_PHOO_MOBLOG', "Moblog");
define('_ES_PHOO_MOBLOG_DESC', "Despliega el álbum Moblog");
define('_ES_PHOO_ALBUMS', "Álbums");
define('_ES_PHOO_ALBUMS_DESC', "Despliega toda la lista de albums");
define('_ES_PHOO_UNKNOW_ALBUM', "En ningún álbum");
define('_ES_PHOO_WITHOUT_ALBUM', "Fotos huerfanas");
define('_ES_PHOO_WITHOUT_ALBUM_DESCRIPTION', "Fotos que no pertenecen a ningun album");
define('_ES_PHOO_NEW_ALBUM', "Nuevo Álbum");
define('_ES_PHOO_EDIT_ALBUM', "Editar Álbum");
define('_ES_PHOO_ALBUM_CREATION_DATE', "Fecha de creación {0}");
define('_ES_PHOO_EDIT_PHOTO', "Editar Foto");
define('_ES_PHOO_FIRST', "Primero");
define('_ES_PHOO_PREVIOUS', "Anterior");
define('_ES_PHOO_NEXT', "Siguiente");
define('_ES_PHOO_LAST', "Último");
define('_ES_PHOO_THUMBS', "Vistas miniatura");
define('_ES_PHOO_WIDTH', "Ancho");
define('_ES_PHOO_HEIGHT', "Alto");
define('_ES_PHOO_SIZE', "Tamaño");
define('_ES_PHOO_APERTURE', "Apertura");
define('_ES_PHOO_EXPOSURE_TIME', "Tiempo de Exposición");
define('_ES_PHOO_FOCAL_LENGTH', "Largo Focal");
define('_ES_PHOO_UNKNOWN_CAM', "Cámara Desconocida");
define('_ES_PHOO_LEAVE_COMMENT', "Dejar un Comentario");
define('_ES_PHOO_PHOTOS', "Fotos");
define('_ES_PHOO_PHOTO', "Foto {0}");
define('_ES_PHOO_PHOTO_COUNTER', "Foto {0} de {1}");
define('_ES_PHOO_PHOTOS_COUNT', "{0} fotos");
define('_ES_PHOO_COMMENTS', "Comentarios");
define('_ES_PHOO_ADDITIONAL_SETTINGS', "Ajustes Adicionales");
define('_ES_PHOO_IMPORT', "Importar");
define('_ES_PHOO_NUM_PHOTOS_ALBUM', "{0} imágenes en el álbum");
define('_ES_PHOO_UPLOAD_PHOTOS', "Subir fotos");
define('_ES_PHOO_EDIT_DESCRIPTION', "Editar Descripción");
define('_ES_PHOO_DELETE_ALBUM_CONFIRM', "Estás seguro que quieres borrar este álbum?");
define('_ES_PHOO_NOT_PUBLISHED', "Sin Publicar");
define('_ES_PHOO_START_UPLOADING_PHOTOS', "Empezar a subir fotos");
define('_ES_PHOO_INEXISTENT_ALBUM', "El álbum no existe");
define('_ES_PHOO_EMPTY_ALBUMSET', "No hay álbums");
define('_ES_PHOO_PHOTO_TITLE', "Título de Foto");
define('_ES_PHOO_PHOTO_DESCRIPTION', "Descripción de Foto");
define('_ES_PHOO_POSTED_BY', "Subida por");
define('_ES_PHOO_ALBUM', "Álbum");
define('_ES_PHOO_ALLOW_COMMENTS', "Permitir Comentarios");
define('_ES_PHOO_STATUS', "Estado");
define('_ES_PHOO_HIDDEN', "Borrador");
define('_ES_PHOO_PUBLISHED', "Publicado");
define('_ES_PHOO_DELETE_PHOTO_CONFIRM', "Estás seguro que quieres borrar esta foto?");
define('_ES_PHOO_UPLOAD_FAILURE', "No se pudo subir la foto");
define('_ES_PHOO_ALBUM_NAME', "Nombre del álbum");
define('_ES_PHOO_ALBUM_DESC', "Descripción del álbum");
define('_ES_PHOO_CREATE_NEW_ALBUM', "Crear un nuevo álbum");
define('_ES_PHOO_DELETE_ALBUM', "Borrar álbum");
define('_ES_PHOO_KEEP_ORIGINAL', "Conservar imagen original");
define('_ES_PHOO_SHOW_EXIF_INFO', "Mostrar información EXIF");
define('_ES_PHOO_EXIF_INFO', "Información EXIF");
define('_ES_PHOO_SAVE_CHANGES', "Guardar cambios");
define('_ES_PHOO_COMMENTS_WHERE', "Comentarios donde");
define('_ES_PHOO_ID', "ID es");
define('_ES_PHOO_TITLE_CONTAINS', "Título contiene");
define('_ES_PHOO_COMMENT_CONTAINS', "Comentarios contienen");
define('_ES_PHOO_NAME_CONTAINS', "Nombre contiene");
define('_ES_PHOO_EMAIL_CONTAINS', "Email contiene");
define('_ES_PHOO_URL_CONTAINS', "URL contiene");
define('_ES_PHOO_IP_CONTAINS', "Dirección IP contiene");
define('_ES_PHOO_FILTER', "Filtro");
define('_ES_PHOO_IP_ADDRESS', "Dirección IP");
define('_ES_PHOO_COMMENT', "Comentario");
define('_ES_PHOO_UPDATE_COMMENT', "Modificar Comentario");
define('_ES_PHOO_DELETE_COMMENT', "Borrar Comentario");
define('_ES_PHOO_REPLY', "Responder");
define('_ES_PHOO_SEND_COMMENT', "Enviar Comentarios");
define('_ES_PHOO_RECENT_COMMENTS', "Comentarios Recientes");
define('_ES_PHOO_RECENT_COMMENTS_DESC', "iDespliega un resumen de comentarios recientes.");
define('_ES_PHOO_SAVE_SETTINGS', "Guardar Ajustes");
define('_ES_PHOO_RESIZE_METHOD', "Método de Escala");
define('_ES_PHOO_DEFAULT_STATUS', "Estado Default");
define('_ES_PHOO_MOBLOG_ALBUM', "Álbum Moblog");
define('_ES_PHOO_MOBLOG_LIMIT', "Límite del Moblog");
define('_ES_PHOO_PHOTOBLOG_ALBUM', "Álbum Fotoblog");
define('_ES_PHOO_PHOTOBLOG_LIMIT', "Límite del Fotoblog");
define('_ES_PHOO_THUMBNAIL_LIMIT', "Miniaturas por Página");
define('_ES_PHOO_FULL_ALBUM', "Todo el Álbum");
define('_ES_PHOO_READY_TO_IMPORT', "Listo para importar {0} imágenes");
define('_ES_PHOO_IMPORT_MESSAGE', "Importar las imágenes seleccionadas a ");
define('_ES_PHOO_NO_IMAGES_TO_IMPORT', "No hay imágenes para importar");
define('_ES_PHOO_IMPORT_INSTRUCTIONS', "Copia o sube las imágenes al directorio JAWS_HOME/data/phoo/import, luego selecciona que imágenes quieres importar a que álbum y presiona importar.");
define('_ES_PHOO_IMPORTING', "Importando");
define('_ES_PHOO_IMPORTING_WARNING', "No cierres esta ventana mientras se importan las imágenes");
define('_ES_PHOO_FINISHED', "Terminado");
define('_ES_PHOO_DELETE_MASSIVE_COMMENTS', "¿Estás seguro que quieres borrar este/estos comentario(s)?");
define('_ES_PHOO_MODERATE_COMMENTS', "Moderar comentarios");
define('_ES_PHOO_COMMENT_IS_SPAM', "Tu comentario ha sido marcado como spam.");
define('_ES_PHOO_COMMENT_IS_WAITING', "Tu comentario está esperando moderación.");
define('_ES_PHOO_ALBUMS_ORDER_TYPE', "Tipo de orden para álbums");
define('_ES_PHOO_PHOTOS_ORDER_TYPE', "Tipo de orden para fotos");
define('_ES_PHOO_ORDER_TYPE_BY_CREATETIME', "Por tiempo de creación");
define('_ES_PHOO_ORDER_TYPE_BY_NAME', "Por nombre");
define('_ES_PHOO_ORDER_TYPE_BY_ID', "Por ID");
define('_ES_PHOO_ADD_ANOTHER_PHOTO', "Agregar otra imagen");
define('_ES_PHOO_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_ES_PHOO_ALBUM_EMPTY', "Album vacío");
define('_ES_PHOO_CSS_CLASS', "Clase CSS");
define('_ES_PHOO_THUMB', "Miniatura");
define('_ES_PHOO_MEDIUM', "Mediana");
define('_ES_PHOO_ORIGINAL', "Original");
define('_ES_PHOO_INSERTIMAGE', "Insertar imagen");
define('_ES_PHOO_IMAGE_LABEL', "Imagen");
define('_ES_PHOO_SELECT_OTHER_IMAGE', "Seleccionar una imagen diferente");
define('_ES_PHOO_INCLUDE_LINK_TO_ALBUM', "Incluir enlace al álbum");
define('_ES_PHOO_ACL_DEFAULT', "Administrar Phoo");
define('_ES_PHOO_ACL_ADDPHOTOS', "Agregar nuevas fotos");
define('_ES_PHOO_ACL_DELETEPHOTOS', "Borrar fotos");
define('_ES_PHOO_ACL_MANAGEPHOTOS', "Administrar fotos");
define('_ES_PHOO_ACL_MODIFYOTHERSPHOTOS', "Modificar fotos de otros");
define('_ES_PHOO_ACL_MANAGECOMMENTS', "Administrar comentarios");
define('_ES_PHOO_ACL_MANAGEALBUMS', "Administrar álbums");
define('_ES_PHOO_ACL_SETTINGS', "Modificar ajustes");
define('_ES_PHOO_ACL_IMPORT', "Importar fotos");
define('_ES_PHOO_ERROR_ADVANCEDSEARCH_QUERY', "Hubo un problema al ejecutar la búsqueda avanzada de Phoo");
define('_ES_PHOO_ERROR_GETMOBLOG', "Hubo un problema al ejecutar la búsqueda de Phoo-Moblog");
define('_ES_PHOO_ERROR_ALBUMLIST', "Hubo un problema al buscar la lista de álbums de Phoo");
define('_ES_PHOO_ERROR_RANDOMIMAGE', "Hubo un problema al escoger una imagen aleatoria de Phoo");
define('_ES_PHOO_ERROR_ALBUMINFO', "Hubo un problema al obtener la información de este álbum");
define('_ES_PHOO_ERROR_ALBUMS', "Hubo un problema al escoger el álbum por {0}");
define('_ES_PHOO_ERROR_GETALBUM', "Hubo un problema al obtener el álbum");
define('_ES_PHOO_ERROR_GETIMAGE', "Hubo un problema al obtener la imagen");
define('_ES_PHOO_ERROR_GETIMAGEENTRY', "Hubo un problema al obtener la entrada de la imagen");
define('_ES_PHOO_ERROR_CANT_UPLOAD_PHOTO_EXT', "Esto no es un archivo valido. Usar (gif|jpeg|png)");
define('_ES_PHOO_ERROR_CANT_UPDATE_PHOTO', "Hubo un problema al modificar la imagen");
define('_ES_PHOO_ERROR_CANT_UPLOAD_PHOTO', "Hubo un problema al subir la foto");
define('_ES_PHOO_ERROR_CANT_DELETE_PHOTO', "Hubo un problema al borrar la foto");
define('_ES_PHOO_ERROR_CANT_ADD_ENTRY_TO_ALBUM', "Hubo un problema al borrar ");
define('_ES_PHOO_ERROR_GETASPORTRAIT', "Hubo un problema al tratar de obtener el álbum como retrato");
define('_ES_PHOO_ERROR_ALBUM_NOT_UPDATED', "Hubo un problema al actualizar el álbum");
define('_ES_PHOO_ERROR_ALBUM_NOT_DELETED', "Hubo un problema al borrar el álbum");
define('_ES_PHOO_ERROR_ALBUM_NOT_CREATED', "Hubo un problema al crear el álbum");
define('_ES_PHOO_ERROR_GETCOMMENTS', "Hubo un problema al obtener los comentarios");
define('_ES_PHOO_ERROR_RECENTCOMMENTS', "Hubo un problema al obtener los comentarios recientes");
define('_ES_PHOO_ERROR_FILETEREDCOMMENTS', "Hubo un problema al obtener los comentarios filtrados");
define('_ES_PHOO_ERROR_GETCOMMENT', "Hubo un problema al obtener un comentario");
define('_ES_PHOO_ERROR_CANT_ADD_COMMENT', "Hubo un problema al agregar el comentario");
define('_ES_PHOO_ERROR_CANT_UPDATE_COMMENT', "Hubo un problema al modificar el comentario");
define('_ES_PHOO_ERROR_CANT_DELETE_COMMENT', "Hubo un problema al borrar el comentario");
define('_ES_PHOO_ERROR_CANT_UPDATE_SETTINGS', "Hubo un problema al modificar los ajustes");
define('_ES_PHOO_ERROR_CANT_DELETE_IMAGE', "Hubo un problema al borrar la imagen");
define('_ES_PHOO_ERROR_CANT_FETCH_SETTINGS', "Hubo un problema al obtener los ajustes.");
define('_ES_PHOO_ALBUM_CREATED', "El álbum ha sido creado");
define('_ES_PHOO_ALBUMS_UPDATED', "Los álbums han sido modificados");
define('_ES_PHOO_ALBUM_UPDATED', "El álbum ha sido modificado");
define('_ES_PHOO_ALBUM_DELETED', "El álbum ha sido borrado");
define('_ES_PHOO_PHOTO_ADDED', "La imagen ha sido agregada");
define('_ES_PHOO_PHOTO_UPDATED', "La imagen ha sido modificada");
define('_ES_PHOO_PHOTO_DELETED', "La imagen ha sido borrada");
define('_ES_PHOO_COMMENT_UPDATED', "El comentario ha sido modificado");
define('_ES_PHOO_COMMENT_DELETED', "El comentario ha sido borrado");
define('_ES_PHOO_SETTINGS_UPDATED', "Los ajustes han sido modificados");
