<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Blog"
 * "Last-Translator: Uğur YILDIZ <uguryildiz@kocaeli.edu.tr>, C.Tuemer <info@exceptionz.net>"
 * "Language-Team: TR"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_TR_BLOG_NAME', "Günlük");
define('_TR_BLOG_DESCRIPTION', "Çok kullanıcılı günlük sistemi. Geçmişi takip etme desteği, pingbacks, yorumlar, ve XML gereksinimleri.");
define('_TR_BLOG_ACL_DEFAULT', "Günlük yönet");
define('_TR_BLOG_ACL_ADDENTRIES', "Kayıt ekle");
define('_TR_BLOG_ACL_MODIFYOTHERSENTRIES', "Diğer kayıtları düzenle");
define('_TR_BLOG_ACL_DELETEENTRIES', "Kayıtları sil");
define('_TR_BLOG_ACL_PUBLISHENTRIES', "Kayıtları Yayınla");
define('_TR_BLOG_ACL_MODIFYPUBLISHEDENTRIES', "Yayımlanmış girdileri değiştirme");
define('_TR_BLOG_ACL_MANAGECOMMENTS', "Yorumları yönet ");
define('_TR_BLOG_ACL_MANAGETRACKBACKS', "Trackbak Yönetimi");
define('_TR_BLOG_ACL_MANAGECATEGORIES', "Kategorileri yönet");
define('_TR_BLOG_ACL_SETTINGS', "Ayarları değiştir");
define('_TR_BLOG_XMLRPC', "XML-RPC günlük servisi, Günlük tutmayı ve MetaWeblog API desteğini sağlar.");
define('_TR_BLOG_WEBSERVICE', "Günlük web servisi.");
define('_TR_BLOG_WSDL', "Günlük WSDL servisi.");
define('_TR_BLOG_LAYOUT_MONTHLY', "Aylık Görünüm");
define('_TR_BLOG_LAYOUT_MONTHLY_DESC', "Günlük kayıtlarının bir aylık özetini göster.");
define('_TR_BLOG_LAYOUT_CATEGORIES', "Kategori Listesi");
define('_TR_BLOG_LAYOUT_CATEGORIES_DESC', "Günlük kategorilerinin bir listesini göster.");
define('_TR_BLOG_LAYOUT_RECENT', "Son Kayıtlar");
define('_TR_BLOG_LAYOUT_RECENT_DESC', "Son kayıtların bir özetini göster.");
define('_TR_BLOG_LAYOUT_RECENTCOMMENTS', "Son Yorumlar");
define('_TR_BLOG_LAYOUT_RECENTCOMMENTS_DESC', "Son yorumların bir özetini göster.");
define('_TR_BLOG_LAYOUT_CALENDAR', "Günlük Takvimi");
define('_TR_BLOG_LAYOUT_CALENDAR_DESC', "Bu ayın takvimini göster, günlük kayıtları işaretli olarak.");
define('_TR_BLOG_LAYOUT_RSS', "RSS Düğmesi");
define('_TR_BLOG_LAYOUT_RSS_DESC', "Rss Beslemesi için bir bağ göster.");
define('_TR_BLOG_LAYOUT_ATOM', "Atom Düğmesi");
define('_TR_BLOG_LAYOUT_ATOM_DESC', "Atom beslemesi için bir bağ göster.");
define('_TR_BLOG_LAYOUT_COMMENTS_RSS', "Yorum RSS Düğmesi");
define('_TR_BLOG_LAYOUT_COMMENTS_RSS_DESC', "RSS beslemesi için bir bağ göster");
define('_TR_BLOG_LAYOUT_COMMENTS_ATOM', "Yorum Atom Düğmesi");
define('_TR_BLOG_LAYOUT_COMMENTS_ATOM_DESC', "Yorum Atom beslemesi için bağ göster");
define('_TR_BLOG_LAYOUT_TAGCLOUD', "Kategori Etiket Bulutu");
define('_TR_BLOG_LAYOUT_TAGCLOUD_DESC', "Kategorileri Etiket bulutu şeklinde göster");
define('_TR_BLOG_LAYOUT_ENTRIES_BY_CATEGORY', "{0} Kayıt Sahibi:");
define('_TR_BLOG_LAYOUT_ENTRIES_BY_CATEGORY_DESC', "Bu kategorideki en son kayıtları gösterir");
define('_TR_BLOG_LAYOUT_POPULAR_POSTS', "Popüler Kayıtlar");
define('_TR_BLOG_LAYOUT_POPULAR_POSTS_DESC', "Popüler kayıtların listesini göster");
define('_TR_BLOG_LAYOUT_POSTS_AUTHORS', "Yazar Kayıtları");
define('_TR_BLOG_LAYOUT_POSTS_AUTHORS_DESC', "Yazar kayıtlarının listesini göster");
define('_TR_BLOG_ENTRY', "Kayıt");
define('_TR_BLOG_RECENT_COMMENTS', "En Son Yorumlar ");
define('_TR_BLOG_COMMENTS_ON_POST', "Gönderilen Yorumlar");
define('_TR_BLOG_SUMMARY', "Özet");
define('_TR_BLOG_NEW_ENTRY', "Yeni Kayıt");
define('_TR_BLOG_LIST_ENTRIES', "Kayıt Listesi");
define('_TR_BLOG_ENTRIES_COUNT', "{0} adet kayıt");
define('_TR_BLOG_COMMENTS', "Yorumlar");
define('_TR_BLOG_HAS_N_COMMENTS', "{0} yorum var");
define('_TR_BLOG_MANAGE_COMMENTS', "Yorumları Yönet");
define('_TR_BLOG_CATEGORIES', "Kategoriler");
define('_TR_BLOG_SETTINGS', "Ayarlar");
define('_TR_BLOG_STATS', "İstatistikler");
define('_TR_BLOG_FIRST_ENTRY', "İlk Kayıt:");
define('_TR_BLOG_LAST_ENTRY', "Son Kayıt:");
define('_TR_BLOG_TOTAL_ENTRIES', "Toplam Kayıt:");
define('_TR_BLOG_AVERAGE_ENTRIES', "Haftalık Ort. Kayıt:");
define('_TR_BLOG_COMMENTS_RECEIVED', "Alınan Yorumlar:");
define('_TR_BLOG_RECENT_ENTRIES', "En Son Yorumlar");
define('_TR_BLOG_DRAFT', "Taslak");
define('_TR_BLOG_ADDITIONAL_SETTINGS', "Ayarlar");
define('_TR_BLOG_DEFAULT_VIEW', "Varsayılan Görünüm");
define('_TR_BLOG_MONTHLY', "Aylık");
define('_TR_BLOG_LATEST_ENTRY', "En son Kayıtlar");
define('_TR_BLOG_LAST_ENTRIES', "En Son Kayıtlar");
define('_TR_BLOG_LAST_ENTRIES_LIMIT', "Görüntülenecek Kayıtlar");
define('_TR_BLOG_POPULAR_ENTRIES_LIMIT', "Gösterilecek Popüler Kayıtlar");
define('_TR_BLOG_LAST_RECENTENTIES_LIMIT', "Görüntülenecek En Son Kayıtlar");
define('_TR_BLOG_LAST_COMMENTS_LIMIT', "Görüntülenecek Yorumlar");
define('_TR_BLOG_LAST_RECENTCOMMENTS_LIMIT', "Görüntülenecek En Son Yorumlar");
define('_TR_BLOG_DEFAULT_CATEGORY', "Varsayılan Kategori");
define('_TR_BLOG_RSS_ENTRIES_LIMIT', "Gönderilecek RSS Kayıtları");
define('_TR_BLOG_TRACKBACK', "Trackbacks");
define('_TR_BLOG_COMMENTS_WHERE', "Görüntülenirken");
define('_TR_BLOG_POST_ID_IS', "göderi ID");
define('_TR_BLOG_TITLE_CONTAINS', "başlık içerikleri");
define('_TR_BLOG_COMMENT_CONTAINS', "yorum gövde içerikleri");
define('_TR_BLOG_NAME_CONTAINS', "isim içerikleri");
define('_TR_BLOG_EMAIL_CONTAINS', "e-ileti adresi içerikleri");
define('_TR_BLOG_URL_CONTAINS', "URL içerikleri");
define('_TR_BLOG_IP_IS', "ip adresi ");
define('_TR_BLOG_FILTER', "Ara");
define('_TR_BLOG_NO_COMMENTS_FOUND', "Aradığınız kritere uygun yorum yok.");
define('_TR_BLOG_COMMENT', "Yorum");
define('_TR_BLOG_NEW_CATEGORY', "Yeni Kategori Yarat");
define('_TR_BLOG_EDIT_CATEGORY', "Kategori Düzenle");
define('_TR_BLOG_CATEGORY', "Kategori");
define('_TR_BLOG_PARENT', "Üst");
define('_TR_BLOG_NO_PARENT', "Üst Kategori Yok");
define('_TR_BLOG_ADVANCED_MODE', "Gelişmiş Mod");
define('_TR_BLOG_FASTURL', "Hızlı URL");
define('_TR_BLOG_FASTURL_COMMENT', "Bu kaydı nasıl mı hatırlayacaksınız? Eğer Hatirla_Beni yazarsanız, bu kayda: <i>index.php?Blog/Hatirla_Beni</i>, şeklinde erişebilirsiniz.");
define('_TR_BLOG_READ_MORE', "Daha fazla oku...");
define('_TR_BLOG_POSTED_BY', "Tarafından Gönderildi");
define('_TR_BLOG_POSTED_IN', "Kategorisinde Gönderildi");
define('_TR_BLOG_NO_COMMENT', "Buna yorum yap");
define('_TR_BLOG_LEAVE_COMMENT', "Bir yorum bırak");
define('_TR_BLOG_COMMENTS_XML', "Yorum XML beslemesi");
define('_TR_BLOG_REPLY', "Cevapla");
define('_TR_BLOG_ARCHIVE', "Günlük Arşivi");
define('_TR_BLOG_RECENT_POSTS', "En Son Gönderimler");
define('_TR_BLOG_SHOW', "Göster");
define('_TR_BLOG_PUBLISHED', "Yayınlandı");
define('_TR_BLOG_AUTHOR', "Yazar");
define('_TR_BLOG_DEFAULT_STATUS', "Varsaylan Durum {0}");
define('_TR_BLOG_ENTRY_SUMMARY', "Kayıt Özeti");
define('_TR_BLOG_ENTRY_BODY', "Kayıt Gövde");
define('_TR_BLOG_ALLOW_COMMENTS', "Yorumlara İzin Ver");
define('_TR_BLOG_ENTRY_NOT_SAVED', "Kayıt kaydedilirken bir sorun oluştu");
define('_TR_BLOG_TITLE', "Başlık");
define('_TR_BLOG_MISSING_TITLE', "Başlık kayıp");
define('_TR_BLOG_BODY', "Gövde");
define('_TR_BLOG_UPDATE', "Güncelle");
define('_TR_BLOG_TRACKBACK_DISABLED', "Trackbackler devre dışı bırakıldı.");
define('_TR_BLOG_DELETE_CONFIRM_CATEGORY', "Bu kategoriyi silmek istediğinizden emin misiniz?");
define('_TR_BLOG_DELETE_CONFIRM_ENTRY', "Bu kaydı silmek itediğinizden emin misiniz?");
define('_TR_BLOG_DELETE_MASSIVE_ENTRIES', "Bu kaydı/kayıtları silmek istediğinizden emin misiniz?");
define('_TR_BLOG_DELETE_MASSIVE_COMMENTS', "Bu yorumu/yorumları silmek istediğinizden emin misiniz? ");
define('_TR_BLOG_UPDATE_COMMENT', "Yorumu Güncelle");
define('_TR_BLOG_EDIT_TIMESTAMP', "Yayınlanma Zamanı");
define('_TR_BLOG_SUBMIT_COMMENT', "Yorumu Gönder");
define('_TR_BLOG_MODERATE_COMMENTS', "Yorumları Düzenle");
define('_TR_BLOG_COMMENT_IS_SPAM', "Yorumunuz istenmeyeb e-ileti olarak işaretlendi.");
define('_TR_BLOG_COMMENT_IS_WAITING', "Yorumunuz yönetimde bekletiliyor.");
define('_TR_BLOG_TAGCLOUD', "Kategori Etiket Bulutu");
define('_TR_BLOG_COMMENT_CURRENTLY_UPDATING_FOR', "{0} kaydının yorumunu güncelliyorsunuz");
define('_TR_BLOG_ENTRY_AUTOUPDATED', "Bu kayır otomatik olarak saklandı (taslak olarak)");
define('_TR_BLOG_RECENT_POSTS_BY_CATEGORY', "{0}");
define('_TR_BLOG_ENTRY_VISITS', "Ziyaret: {0}");
define('_TR_BLOG_POPULAR_POSTS', "Popüler Kayıtlar");
define('_TR_BLOG_POSTS_AUTHORS', "Yazar Kayıtları");
define('_TR_BLOG_CATEGORY_ADDED', "Bir kategori eklendi");
define('_TR_BLOG_CATEGORY_UPDATED', "Kategori güncellendi");
define('_TR_BLOG_CATEGORY_DELETED', "Kategori silindi");
define('_TR_BLOG_SETTINGS_SAVED', "Ayarlar kaydedildi");
define('_TR_BLOG_COMMENT_UPDATED', "Yorum kaydedildi");
define('_TR_BLOG_COMMENT_DELETED', "Yorum silindi");
define('_TR_BLOG_ENTRY_ADDED', "Bir kayıt eklendi");
define('_TR_BLOG_ENTRY_UPDATED', "Kayıt güncellendi");
define('_TR_BLOG_ENTRY_DELETED', "Kayıt silindi");
define('_TR_BLOG_COMMENT_MARKED', "Bazı yorumların durumları değişti");
define('_TR_BLOG_TRACKBACK_UPDATED', "Trackbak kaydedildi");
define('_TR_BLOG_TRACKBACK_DELETED', "Trackback silindi");
define('_TR_BLOG_TRACKBACK_MARKED', "Bazı trackbacklerin durumu değişti");
define('_TR_BLOG_ERROR_GETTING_ENTRIES_ASCALENDAR', "Kayıtlar takvim olarak getirilirken bir sorun oluştu");
define('_TR_BLOG_ERROR_ADVANCED_SEARCH', "Arama yapmada bir sorun var");
define('_TR_BLOG_ERROR_GETTING_CATEGORIES', "Kategorileri çekmede bir sorun var");
define('_TR_BLOG_ERROR_GETTING_CATEGORY', "Kategoriyi çekmede bir sorun var");
define('_TR_BLOG_ERROR_CATEGORY_NOT_ADDED', "Kategori eklerken bir sorun oluştu");
define('_TR_BLOG_ERROR_CATEGORY_NOT_UPDATED', "Kategori güncellenirken bir sorun oluştu");
define('_TR_BLOG_ERROR_CATEGORIES_LINKED', "Kategori silinemedi çünkü kategoriye bağlı kayıtlar var");
define('_TR_BLOG_ERROR_CATEGORY_NOT_DELETED', "Kategoriyi silerken bir sorun oluştu");
define('_TR_BLOG_ERROR_SETTINGS_NOT_SAVED', "Ayarları kaydederken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_ENTRIES', "Kayıtları getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_ENTRIES_BYDATE', "Kayıt tarihlerini getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_COMMENTS', "Yorumları getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_RECENT_COMMENTS', "En son yorumları getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_FILTERED_COMMENTS', "Süzülmüş yorumları getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_COMMENT', "Yorumu getiriken br sorun oluştu");
define('_TR_BLOG_ERROR_COMMENT_NOT_ADDED', "Yorumu eklerken bir sorun oluştu");
define('_TR_BLOG_ERROR_COMMENT_NOT_UPDATED', "Yorumu güncellerken bir sorun oluştu");
define('_TR_BLOG_ERROR_COMMENT_NOT_DELETED', "Yorumu silerken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_ENTRIES_ASARCHIVE', "Kayıtları arşiv olarak getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_ENTRIES_ASHISTORY', "Kayıtları geçmiş olarak getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_ENTRIES_ASCATEGORIES', "Kayıtları kategori olarak getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_RECENT_ENTRIES', "En son kayıtları getiriken sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_ATOMSTRUCT', "Atom kayıtlarını getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_WRITING_ATOMFILE', "Atom dosyası kayıtlarını getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_WRITING_RSSFILE', "Kayıtları RSS Dosyasına yazarken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_CATEGORIES_ATOMSTRUCT', "Atom kategorilerini getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_WRITING_CATEGORY_ATOMFILE', "Atom dosyası kategorilerini yazarken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_COMMENTS_ATOMSTRUCT', "Atom Yorumlarını getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_POST_COMMENTS_ATOMSTRUCT', "Atom yorumlarını getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_WRITING_POST_COMMENTS_ATOMFILE', "Yorumları Atom Dosyasına yazarken bir sorun oluştu");
define('_TR_BLOG_ERROR_WRITING_POST_COMMENTS_RSSFILE', "Yorumları RSS dosyasına yazarken bir srun oluştu ");
define('_TR_BLOG_ERROR_GETTING_ENTRIES_BYCATEGORY', "Kategorilerine göre kayıtları getiriken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_ENTRY', "Kaydı getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_LAST_ENTRIES', "En son kayıtları getiriken bir sorun oluştu");
define('_TR_BLOG_ERROR_GETTING_MONTH_ENTRIES', "Aylara göre kayıtları getirirken bir sorun oluştu");
define('_TR_BLOG_ERROR_ENTRY_NOT_ADDED', "Kayıt eklerken bir sorun oluştu");
define('_TR_BLOG_ERROR_ENTRY_NOT_UPDATED', "Kayıt güncellerken bir sorun oluştu");
define('_TR_BLOG_ERROR_ENTRY_NOT_DELETED', "Kayıt silerken bir sorun oluştu");
define('_TR_BLOG_ERROR_TRACKBACK_NOT_ADDED', "Trackback eklerken bir sorun oluştu");
define('_TR_BLOG_ERROR_DOES_NOT_EXISTS', "Kayıt mevcut değil");
define('_TR_BLOG_ERROR_GETTING_TRACKBACKS', "Trackback getiriken bir sorun oluştu");
define('_TR_BLOG_ERROR_XMLRPC_NO_GETTEMPLATE_SUPPORT', "JAWS getTemplate işlevini desteklemiyor");
define('_TR_BLOG_ERROR_XMLRPC_NO_SETTEMPLATE_SUPPORT', "JAWS set Template işlevini desteklemiyor");
define('_TR_BLOG_ERROR_CATEGORY_XML_NOT_GENERATED', "Kategoriler için XML Beslemesi oluşturulmadı ");
define('_TR_BLOG_ERROR_TAGCLOUD_CREATION_FAILED', "Etiket bulutu oluştutulurken bir sorun oluştu");
define('_TR_BLOG_ERROR_TRACKBACK_NOT_UPDATED', "Trackback güncellenirken bir sorun oluştu");
define('_TR_BLOG_ERROR_TRACKBACK_NOT_DELETED', "Trackback silinirken bir sorun oluştu");
define('_TR_BLOG_MAIL_COMMENT_TO_ME', "Bu yorumu e-ileti olarak bana gönder..");
define('_TR_BLOG_COMMENT_REPLY', "[Blog comment] - {0} id'li günlük için");
define('_TR_BLOG_COMMENT_MAIL_VISIT', "See the blog thread at: ");
define('_TR_BLOG_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_TR_BLOG_PAGENAVIGATION_NEXTPAGE', "Sonraki sayfa");
define('_TR_BLOG_PAGENAVIGATION_PREVIOUSPAGE', "Önceki sayfa");
define('_TR_BLOG_MANAGE_TRACKBACKS', "Trackbackler");
define('_TR_BLOG_TRACKBACK_WHERE', "Gösterildiğinde");
define('_TR_BLOG_TRACKBACK_BLOGNAME', "Günlük adı");
define('_TR_BLOG_TRACKBACK_BLOGNAME_CONTAINS', "trackback günlük adını içerir");
define('_TR_BLOG_TRACKBACK_EXCERPT', "Alıntı");
define('_TR_BLOG_TRACKBACK_EXCERPT_CONTAINS', "trackback alıntı içerir");
define('_TR_BLOG_VIEW_TRACKBACK', "Trackback Görünümü");
define('_TR_BLOG_TRACKBACKS_CURRENTLY_UPDATING_FOR', "{0} isimli gönderimin trackback görünümüne bakıyorsunuz");
define('_TR_BLOG_DELETE_MASSIVE_TRACKBACKS', "Bu trackback'i(leri) silmek istediğinizden emin misiniz?");
define('_TR_BLOG_PINGBACK', "Pingback");
define('_TR_BLOG_PINGBACK_DEFAULT_COMMENT', "Pingback comment from {0}");
define('_TR_BLOG_PINGBACK_DEFAULT_TITLE', "Pingback from {0}");
define('_TR_BLOG_PINGBACK_TITLE', "{0} (pingbacklerden)");
define('_TR_BLOG_PINGBACK_COMMENT', "Bu yorum şu pingbacklerden geliyor: {0}");
