<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Phoo"
 * "Last-Translator: Uğur YILDIZ <uguryildiz@kocaeli.edu.tr>, C.Tuemer <info@exceptionz.net>"
 * "Language-Team: TR"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_TR_PHOO_NAME', "Fotoğraflar");
define('_TR_PHOO_DESCRIPTION', "Siteniz için iyi bir fotoğraf düzenleiyici");
define('_TR_PHOO_DEFAULT_VIEW', "Varsayılan görünüm");
define('_TR_PHOO_ALBUM_LIST', "Albüm Listesi");
define('_TR_PHOO_PHOTOBLOG', "Photoblog");
define('_TR_PHOO_RANDOM_IMAGE', "Rasgele  Resim");
define('_TR_PHOO_RANDOM_IMAGE_DESC', "Herhangi bir albümden rasgele bir resim gösterir.");
define('_TR_PHOO_MOBLOG', "Moblog");
define('_TR_PHOO_MOBLOG_DESC', "Moblog albümünü gösterir");
define('_TR_PHOO_ALBUMS', "Albümler");
define('_TR_PHOO_ALBUMS_DESC', "Bütün albüm listelerini görüntüler");
define('_TR_PHOO_UNKNOW_ALBUM', "Albümlerde bulunamadı");
define('_TR_PHOO_WITHOUT_ALBUM', "Albümsüz Fotoğraflar");
define('_TR_PHOO_WITHOUT_ALBUM_DESCRIPTION', "Hiçbir albüme ait olmayan fotoğraflar");
define('_TR_PHOO_NEW_ALBUM', "Yeni Albüm");
define('_TR_PHOO_EDIT_ALBUM', "Albüm Düzenle");
define('_TR_PHOO_ALBUM_CREATION_DATE', "Tarih Oluşturma");
define('_TR_PHOO_EDIT_PHOTO', "Fotoğraf düzenle");
define('_TR_PHOO_FIRST', "İlk");
define('_TR_PHOO_PREVIOUS', "Önceki");
define('_TR_PHOO_NEXT', "Sonraki");
define('_TR_PHOO_LAST', "Son");
define('_TR_PHOO_THUMBS', "Thumbnails");
define('_TR_PHOO_WIDTH', "Genişlik");
define('_TR_PHOO_HEIGHT', "Yükseklik");
define('_TR_PHOO_SIZE', "Boyut");
define('_TR_PHOO_APERTURE', "Açıklık");
define('_TR_PHOO_EXPOSURE_TIME', "Zamanölçer");
define('_TR_PHOO_FOCAL_LENGTH', "Odak uzaklığı");
define('_TR_PHOO_UNKNOWN_CAM', "Bilinmeyen Kamera(Fotoğraf Makinası)");
define('_TR_PHOO_LEAVE_COMMENT', "Yorum yap");
define('_TR_PHOO_PHOTOS', "Fotoğraflar");
define('_TR_PHOO_PHOTO', "{0} . fotoğraf");
define('_TR_PHOO_PHOTO_COUNTER', "{1} Fotoğraftan {0}");
define('_TR_PHOO_PHOTOS_COUNT', "{0} adet fotoğraf");
define('_TR_PHOO_COMMENTS', "Yorumlar");
define('_TR_PHOO_ADDITIONAL_SETTINGS', "Ek Ayarlar");
define('_TR_PHOO_IMPORT', "Dosya Al");
define('_TR_PHOO_NUM_PHOTOS_ALBUM', "Albümdeki resim sayısı {0}");
define('_TR_PHOO_UPLOAD_PHOTOS', "Fotoğraflar Yükle");
define('_TR_PHOO_EDIT_DESCRIPTION', "Tanımlamayı Düzenle");
define('_TR_PHOO_DELETE_ALBUM_CONFIRM', "Bu albümü silmek istediğinizden emin misiniz?");
define('_TR_PHOO_NOT_FOUND', "Bulunamadı");
define('_TR_PHOO_NOT_PUBLISHED', "Yayınlanmamış");
define('_TR_PHOO_START_UPLOADING_PHOTOS', "Fotoğrafları yüklemeye başla");
define('_TR_PHOO_INEXISTENT_ALBUM', "Albüm oluşturulmamış");
define('_TR_PHOO_EMPTY_ALBUMSET', "Albüm yok");
define('_TR_PHOO_PHOTO_TITLE', "Fotoğraf Başlığı");
define('_TR_PHOO_PHOTO_DESCRIPTION', "Fotoğraf tanımlaması");
define('_TR_PHOO_POSTED_BY', "Gönderen");
define('_TR_PHOO_ALBUM', "Albüm");
define('_TR_PHOO_ALLOW_COMMENTS', "Yorum yapılmasına izin ver");
define('_TR_PHOO_STATUS', "Durum");
define('_TR_PHOO_HIDDEN', "Gizli");
define('_TR_PHOO_PUBLISHED', "Yayınlandı");
define('_TR_PHOO_DELETE_PHOTO_CONFIRM', "Bu fotoğrafı silmek istediğinizden emin misiniz?");
define('_TR_PHOO_UPLOAD_FAILURE', "Fotoğraf yüklenemedi");
define('_TR_PHOO_ALBUM_NAME', "Albüm Adı");
define('_TR_PHOO_ALBUM_DESC', "Albüm Tanımlaması");
define('_TR_PHOO_CREATE_NEW_ALBUM', "Yeni Albüm Oluştur");
define('_TR_PHOO_DELETE_ALBUM', "Albüm Sil");
define('_TR_PHOO_KEEP_ORIGINAL', "Orjinal resmi sakla");
define('_TR_PHOO_SHOW_EXIF_INFO', "EXIF bilgisini göster");
define('_TR_PHOO_EXIF_INFO', "EXIF bilgisi");
define('_TR_PHOO_SAVE_CHANGES', "Değişiklikleri kaydet");
define('_TR_PHOO_COMMENTS_WHERE', "Yorumların yeri");
define('_TR_PHOO_ID', "ID is");
define('_TR_PHOO_TITLE_CONTAINS', "başlık içerikleri");
define('_TR_PHOO_COMMENT_CONTAINS', "yorum içerikleri");
define('_TR_PHOO_NAME_CONTAINS', "isim içerikleri");
define('_TR_PHOO_EMAIL_CONTAINS', "e-ileti içerikleri");
define('_TR_PHOO_URL_CONTAINS', "URL içerikleri");
define('_TR_PHOO_IP_CONTAINS', "IP addresi içerikleri");
define('_TR_PHOO_FILTER', "Filitreler");
define('_TR_PHOO_IP_ADDRESS', "IP Adresleri");
define('_TR_PHOO_COMMENT', "Yorum");
define('_TR_PHOO_UPDATE_COMMENT', "Yorum Güncelle");
define('_TR_PHOO_DELETE_COMMENT', "Yorum Sil");
define('_TR_PHOO_REPLY', "Yanıtla");
define('_TR_PHOO_SEND_COMMENT', "Yorumları Gönder");
define('_TR_PHOO_RECENT_COMMENTS', "Bu Fotoğraftaki En Son Yorumlar");
define('_TR_PHOO_RECENT_COMMENTS_DESC', "En son yoruların özetini görüntüler");
define('_TR_PHOO_SAVE_SETTINGS', "Ayarları kaydet");
define('_TR_PHOO_RESIZE_METHOD', "Yeniden boyutlandırma yöntemi");
define('_TR_PHOO_DEFAULT_STATUS', "Varsayılan Durum");
define('_TR_PHOO_MOBLOG_ALBUM', "Moblog Albümü");
define('_TR_PHOO_MOBLOG_LIMIT', "Moblog Sınırı");
define('_TR_PHOO_PHOTOBLOG_ALBUM', "Photoblog Albümü");
define('_TR_PHOO_PHOTOBLOG_LIMIT', "Photoblog Sınırı");
define('_TR_PHOO_THUMBNAIL_LIMIT', "Sayfa Başına Resim");
define('_TR_PHOO_FULL_ALBUM', "Tüm Albüm");
define('_TR_PHOO_READY_TO_IMPORT', "{0} resim alınmak için hazır");
define('_TR_PHOO_IMPORT_MESSAGE', "Import selected images to ");
define('_TR_PHOO_NO_IMAGES_TO_IMPORT', "No images to import");
define('_TR_PHOO_IMPORT_INSTRUCTIONS', "Fotoğraflarınızı data/phoo/import dizinine kopyalayın, sonra burayı tekrar ziyaret edin bu seçenek fotoğraflarını içe aktaracaktır.");
define('_TR_PHOO_IMPORTING', "Importing");
define('_TR_PHOO_IMPORTING_WARNING', "Dosya alınırken bu pencereyi kapatmayın");
define('_TR_PHOO_FINISHED', "Tamamlandı");
define('_TR_PHOO_DELETE_MASSIVE_COMMENTS', "Bu yorumları silmek istediğinizden emin misiniz?");
define('_TR_PHOO_MODERATE_COMMENTS', "Yorumları Uyarla");
define('_TR_PHOO_COMMENT_IS_SPAM', "Yorumunuz bir spam olarak belirlendi.");
define('_TR_PHOO_COMMENT_IS_WAITING', "Yorumunuz denetleme için bekletiliyor.");
define('_TR_PHOO_ALBUMS_ORDER_TYPE', "Albümler için düzen tarzı");
define('_TR_PHOO_PHOTOS_ORDER_TYPE', "Fotoğraf sıralama türü");
define('_TR_PHOO_ORDER_TYPE_BY_CREATETIME', "Oluşturma zamanına göre");
define('_TR_PHOO_ORDER_TYPE_BY_NAME', "Ad'a göre");
define('_TR_PHOO_ORDER_TYPE_BY_ID', "Id'ye göre");
define('_TR_PHOO_ADD_ANOTHER_PHOTO', "Başka fotoğraf ekle");
define('_TR_PHOO_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_TR_PHOO_ALBUM_EMPTY', "Boş albüm");
define('_TR_PHOO_CSS_CLASS', "CSS Sınıfı");
define('_TR_PHOO_THUMB', "Küçük Resim");
define('_TR_PHOO_MEDIUM', "Orta Resim");
define('_TR_PHOO_ORIGINAL', "Orjinal Resim");
define('_TR_PHOO_INSERTIMAGE', "Resim Ekle");
define('_TR_PHOO_IMAGE_LABEL', "Resim");
define('_TR_PHOO_SELECT_OTHER_IMAGE', "Farklı bir resim seç");
define('_TR_PHOO_INCLUDE_LINK_TO_ALBUM', "Albüma bağ içersin");
define('_TR_PHOO_ACL_DEFAULT', "Phoo'yu Yönet");
define('_TR_PHOO_ACL_ADDPHOTOS', "Yeni fotoğraflar ekle");
define('_TR_PHOO_ACL_DELETEPHOTOS', "Fotoğrafları Sil");
define('_TR_PHOO_ACL_MANAGEPHOTOS', "Fotoğrafları Yönet");
define('_TR_PHOO_ACL_MODIFYOTHERSPHOTOS', "Modify photos owned by others");
define('_TR_PHOO_ACL_MANAGECOMMENTS', "Yorumları Yönet");
define('_TR_PHOO_ACL_MANAGEALBUMS', "Albümleri Yönet");
define('_TR_PHOO_ACL_SETTINGS', "Ayarları Değiştir");
define('_TR_PHOO_ACL_IMPORT', "Fotoğrafları Al");
define('_TR_PHOO_ERROR_ADVANCEDSEARCH_QUERY', "Geliştirilmiş Arama Sorgusu çalıştırılırken bir sorun oluştu");
define('_TR_PHOO_ERROR_GETMOBLOG', "MoBlog Sorgusu çalıştırılırken bir sorun oluştu");
define('_TR_PHOO_ERROR_ALBUMLIST', "Album listesi alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_RANDOMIMAGE', "Rasgele resim seçilirken bir sorun oluştu");
define('_TR_PHOO_ERROR_ALBUMINFO', "Album bilgisi alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_ALBUMS', "{0}'e göre albümler seçiliyorken bir sorun oluştu ");
define('_TR_PHOO_ERROR_GETALBUM', "Album alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_GETIMAGE', "Resim alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_GETIMAGEENTRY', "Resim kayıt bilgisi alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_UPLOAD_PHOTO_EXT', "Bu geçerli dosya bir dosya değil. Lütfen (gif|jpeg|png) kulanının");
define('_TR_PHOO_ERROR_CANT_UPDATE_PHOTO', "Fotoğraf güncellenirken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_UPLOAD_PHOTO', "Fotoğraf yüklenirken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_DELETE_PHOTO', "Fotoğraf silinirken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_ADD_ENTRY_TO_ALBUM', "Albüm kayıt bilgisi eklenirken bir sorun oluştu");
define('_TR_PHOO_ERROR_GETASPORTRAIT', "Albüm portre gibi alınırken oluşan sorun devam ediyor");
define('_TR_PHOO_ERROR_ALBUM_NOT_UPDATED', "Albüm güncellenirken bir sorun oluştu");
define('_TR_PHOO_ERROR_ALBUM_NOT_DELETED', "Albüm silinirken bir sorun oluştu");
define('_TR_PHOO_ERROR_ALBUM_NOT_CREATED', "Albüm oluşturulurken bir sorun oluştu");
define('_TR_PHOO_ERROR_GETCOMMENTS', "Yorumlar alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_RECENTCOMMENTS', "En son yapılan yorumlar alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_FILETEREDCOMMENTS', "Filitrelenmiş yorumlar alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_GETCOMMENT', "Yorum alınırken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_ADD_COMMENT', "Yorum eklenirken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_UPDATE_COMMENT', "Yorum güncellenirken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_DELETE_COMMENT', "Yorum silinirken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_UPDATE_SETTINGS', "Ayarlar güncellenirken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_DELETE_IMAGE', "Resim silinirken bir sorun oluştu");
define('_TR_PHOO_ERROR_CANT_FETCH_SETTINGS', "Ayarlar alınırken bir sorun oluştu");
define('_TR_PHOO_ALBUM_CREATED', "Albüm oluşturuldu");
define('_TR_PHOO_ALBUMS_UPDATED', "Albümler güncellendi");
define('_TR_PHOO_ALBUM_UPDATED', "Albüm güncellendi");
define('_TR_PHOO_ALBUM_DELETED', "Albüm silindi");
define('_TR_PHOO_PHOTO_ADDED', "Fotoğraf eklendi");
define('_TR_PHOO_PHOTO_UPDATED', "Fotoğraf güncellendi");
define('_TR_PHOO_PHOTO_DELETED', "Fotoğraf silindi");
define('_TR_PHOO_COMMENT_UPDATED', "Yorum güncellendi");
define('_TR_PHOO_COMMENT_DELETED', "Yorum silindi");
define('_TR_PHOO_SETTINGS_UPDATED', "Ayarlar güncellendi");
