<?php
// General Translation file (i18n) for Poll gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Poll"
 * "Last-Translator: Ciprian Ghenciu <www.osn.ro>"
 * "Language-Team: RO"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_RO_POLL_NAME', "Voteaza");
define('_RO_POLL_DESCRIPTION', "Un sistem de votare care permite vizitatorilor sa supuna voturi in privinta oricarui subiect propus");

/* Strings */
define('_RO_POLL_VOTE', "Voteaza");
define('_RO_POLL_POLLS', "Voturi");
define('_RO_POLL_QUESTION', "Intrebare");
define('_RO_POLL_STATUS', "Statut");
define('_RO_POLL_ANSWER', "Raspuns");
define('_RO_POLL_ANSWERS', "Raspunsuri");
define('_RO_POLL_CONFIRM_DELETE_POLL', "Sigur vrei sa stergi acest subiect de votare?");
define('_RO_POLL_NEW', "Adauga subiect nou de votat");
define('_RO_POLL_EDIT', "Editeaza subiect de vot");
/* Layout */
define('_RO_POLL_LAYOUT_DISPLAY_LAST', "Afiseaza ultimul subiect de vot");
define('_RO_POLL_LAYOUT_DISPLAY_LAST_DESC', "Afiseaza ultimul subiect de votat introdus");
define('_RO_POLL_LAYOUT_LIST_POLLS', "Lista subiectelor de votat");
define('_RO_POLL_LAYOUT_LIST_POLLS_DESC', "Tipareste o lista a tuturor subiectelor de votat deschise");

/* ACL's */
define('_RO_POLL_ACL_DEFAULT', "Administreaza subiect de vot");
define('_RO_POLL_ACL_ADDPOLL', "Adauga subiecte noi de votat");
define('_RO_POLL_ACL_EDITPOLL', "Editeaza subiecte de votat");
define('_RO_POLL_ACL_DELETEPOLL', "Sterge subiecte de votat");

/* Responses */
define('_RO_POLL_ANSWER_ADDED', "A fost adaugat un raspuns");
define('_RO_POLL_ANSWER_UPDATED', "Raspunsul la subiect a fost actualizat");
define('_RO_POLL_POLL_DELETED', "Subiectul de votat a fost actualizat");
define('_RO_POLL_ANSWER_DELETED', "Raspunsul la subiectul de votat a fost sters");
define('_RO_POLL_POLL_ENABLED', "Subiectul de votat a fost activat");
define('_RO_POLL_POLL_DISABLED', "Subiectul de votat a fost dezactivat");
define('_RO_POLL_POLL_ADDED', "Subiectul de votat a fost adaugat");
define('_RO_POLL_POLL_UPDATED', "Subiectul de votat a fost actualizat");

/* Errors */
define('_RO_POLL_ERROR_REQUIRES_QUESTION', "Prima data scrie intrebarea");
define('_RO_POLL_ERROR_REQUIRES_TWO_ANSWERS', "Cel putin doua raspunsuri");
define('_RO_POLL_ERROR_POLL_NOT_ADDED', "A fost o problema la adaugarea subiectului de votat");
define('_RO_POLL_ERROR_POLL_NOT_UPDATED', "A fost o problema la actualizarea subiectului de votare");
define('_RO_POLL_ERROR_POLL_NOT_DISABLED', "A fost o problema la dezactivarea subiectului de votare");
define('_RO_POLL_ERROR_ANSWER_DOES_NOT_EXISTS', "Raspunsul nu exista");
define('_RO_POLL_ERROR_POLL_NOT_ENABLED', "A fost o problema la activarea subiectului de votat");
define('_RO_POLL_ERROR_ANSWER_NOT_DELETED', "A fost o problema la stergerea raspunsului");
define('_RO_POLL_ERROR_ANSWER_NOT_UPDATED', "A fost o problema la actualizarea raspunsului");
define('_RO_POLL_ERROR_EXCEPTION_ANSWER_NOT_DELETED', "Raspunsurile nu au putut fi sterse in timpul stergerii subiectului de votat");
define('_RO_POLL_ERROR_ANSWER_NOT_ADDED', "A fost o problema la adaugarea raspunsului la subiectul de votat");
define('_RO_POLL_ERROR_VOTE_NOT_ADDED', "A fost o problema la adaugarea votului");