<?php
// General Translation file  (i18n) for JMS gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Jms"
 * "Last-Translator: shalibaji <freeyiyi@yahoo.co.uk>"
 * "Language-Team: ZH"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_ZH_COMPONENTS_NAME', "组件管理");
define('_ZH_COMPONENTS_DESCRIPTION', "管理所有Jaws中的组件.");
define('_ZH_COMPONENTS_INSTALLED_COMPONENTS', "安装组件");
define('_ZH_COMPONENTS_UNINSTALLED_COMPONENTS', "卸载组件");
define('_ZH_COMPONENTS_OUTDATED_COMPONENTS', "过期的组件");
define('_ZH_COMPONENTS_KEY', "Key");
define('_ZH_COMPONENTS_VALUE', "评价");
define('_ZH_COMPONENTS_INFORMATION', "信息");
define('_ZH_COMPONENTS_VERSION', "版本");
define('_ZH_COMPONENTS_INSTALL', "安装");
define('_ZH_COMPONENTS_UNINSTALL', "卸载");
define('_ZH_COMPONENTS_PURGE', "清除");
define('_ZH_COMPONENTS_UPDATE', "更新");
define('_ZH_COMPONENTS_ONLY_SHOW', "仅显示: ");

/* ACL */
define('_ZH_COMPONENTS_ACL_MANAGEJMS', "使用组件管理");
define('_ZH_COMPONENTS_ACL_MANAGEGADGETS', "激活/解除 组件");
define('_ZH_COMPONENTS_ACL_MANAGEPLUGINS', "激活/解除 插件");

/* Plugins */
define('_ZH_COMPONENTS_PLUGINS', "插件");
define('_ZH_COMPONENTS_PLUGINS_INSTALLED_PLUGINS', "安装插件");
define('_ZH_COMPONENTS_PLUGINS_NOTINSTALLED_PLUGINS', "不安装插件");

define('_ZH_COMPONENTS_PLUGINS_PLUGIN', "插件");
define('_ZH_COMPONENTS_PLUGINS_USAGE', "插件用法");
define('_ZH_COMPONENTS_PLUGINS_NO_EXAMPLE', "没有示例");
define('_ZH_COMPONENTS_PLUGINS_FRIENDLY', "友好的");
define('_ZH_COMPONENTS_PLUGINS_NOT_FRIENDLY', "不友好的");
define('_ZH_COMPONENTS_PLUGINS_ACCESSKEY', "访问Key");
define('_ZH_COMPONENTS_PLUGINS_NO_ACCESSKEY', "没有发现访问key");
define('_ZH_COMPONENTS_PLUGINS_USE_IN', "插件用法");
define('_ZH_COMPONENTS_PLUGINS_SAVED', "你的插件设置被保存.");
define('_ZH_COMPONENTS_PLUGINS_NOTHING', "没有插件");
define('_ZH_COMPONENTS_PLUGINS_ALWAYS', "永远");
define('_ZH_COMPONENTS_PLUGINS_ONLY_IN_GADGET', "仅在其组件中");
define('_ZH_COMPONENTS_PLUGINS_ENABLED_OK', "{0}组件安装成功");
define('_ZH_COMPONENTS_PLUGINS_ENABLED_FAILURE', "安装{0}插件错误");
define('_ZH_COMPONENTS_PLUGINS_NO_SELECTION', "没有选择插件,请选则");
define('_ZH_COMPONENTS_SIDEBAR_DISABLE_PLUGIN', "未激活的");
define('_ZH_COMPONENTS_SIDEBAR_DISABLE_PLUGINS', "激活的插件");
define('_ZH_COMPONENTS_SIDEBAR_DISABLE_PLUGINS_WAITING', "插件等待被激活");
define('_ZH_COMPONENTS_PLUGINS_DISABLE_FAILURE', "不能激活插件");
define('_ZH_COMPONENTS_PLUGINS_DISABLE_OK', "插件卸载正确");
define('_ZH_COMPONENTS_PLUGINS_PLUGIN_DOESNT_EXISTS', "插件{0}不存在");
define('_ZH_COMPONENTS_PLUGINS_PLUGIN_CANT_HAVE_NAME_CORE', "插件不能具有核心命名,该命名被Jaws保留.");

/* Gadgets */
define('_ZH_COMPONENTS_GADGETS', "组件");
define('_ZH_COMPONENTS_GADGETS_INSTALLED_GADGETS', "安装组件");
define('_ZH_COMPONENTS_GADGETS_NOTINSTALLED_GADGETS', "不安装组件");
define('_ZH_COMPONENTS_GADGETS_NOTHING', "没有组件");
define('_ZH_COMPONENTS_GADGETS_REGISTRY', "登记Keys");
define('_ZH_COMPONENTS_GADGETS_ACL', "ACL规则");
define('_ZH_COMPONENTS_GADGETS_DOESNT_EXISTS', "插件{0}不存在");
define('_ZH_COMPONENTS_GADGETS_UNINSTALL_CONFIRM', "你想卸载这个组件吗? 这个选项不能删除数据");
define('_ZH_COMPONENTS_GADGETS_PURGE_CONFIRM', "你想清除这个组件吗?这个选项将卸载并且删除数据");
define('_ZH_COMPONENTS_GADGETS_NOT_EXISTS', "组件不存在");
define('_ZH_COMPONENTS_GADGETS_NO_SELECTION', "没有组件被选，请选则");
define('_ZH_COMPONENTS_GADGETS_ENABLED_OK', "{0}组件成功安装");
define('_ZH_COMPONENTS_GADGETS_ENABLED_FAILURE', "安装组件{0}错误");
define('_ZH_COMPONENTS_GADGETS_DISABLE_OK', "{0}组件被成功地安装");
define('_ZH_COMPONENTS_GADGETS_DISABLE_FAILURE', "卸载组件{0}错误");
define('_ZH_COMPONENTS_GADGETS_UPDATED_OK', "{0}组件更新成功");
define('_ZH_COMPONENTS_GADGETS_UPDATED_FAILURE', "更新组件{0}错误");
define('_ZH_COMPONENTS_GADGETS_UPDATED_NO_NEED', "没有必要更新{0}组件");

/* Sidebar */
define('_ZH_COMPONENTS_SIDEBAR_ENABLE', "激活");
define('_ZH_COMPONENTS_SIDEBAR_DISABLE', "解除");

/* Gadgets Sidebar */
define('_ZH_COMPONENTS_SIDEBAR_DISABLED_GADGETS', "激活组件");
define('_ZH_COMPONENTS_SIDEBAR_GADGETS_WAITING', "这里有组件等待被激活:");
define('_ZH_COMPONENTS_SIDEBAR_ENABLED_GADGETS', "激活组件");
define('_ZH_COMPONENTS_SIDEBAR_DISABLE_GADGETS_WAITING', "你可以解除以下组件:");

/* Gadget disabling errors */
define('_ZH_COMPONENTS_SIDEBAR_DISABLE_MAIN_FAILURE', "不能解除主要组件");

/* Not updated gadgets sidebar */
define('_ZH_COMPONENTS_SIDEBAR_NOTUPDATED_GADGETS', "过时的组件");
define('_ZH_COMPONENTS_SIDEBAR_NOTUPDATED_SUGESTION', "这里是现在能够升级的组件:");

/* Plugins Sidebar */
define('_ZH_COMPONENTS_SIDEBAR_DISABLED_PLUGINS', "解除插件");
define('_ZH_COMPONENTS_SIDEBAR_PLUGINS_WAITING', "等待激活的插件:");
