<?php
// General Translation file (i18n) for Poll gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: 投票"
 * "Last-Translator: shalibaji <freeyiyi@yahoo.co.uk>"
 * "Language-Team: ZH"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_ZH_POLL_NAME', "投票");
define('_ZH_POLL_DESCRIPTION', "一个投票系统");

/* Strings */
define('_ZH_POLL_VOTE', "投票");
define('_ZH_POLL_POLLS', "投票");
define('_ZH_POLL_QUESTION', "问题");
define('_ZH_POLL_STATUS', "状态");
define('_ZH_POLL_ANSWER', "答案");
define('_ZH_POLL_ANSWERS', "答案");
define('_ZH_POLL_CONFIRM_DELETE_POLL', "你确定要删除这个投票?");
define('_ZH_POLL_NEW', "添加一个新投票");
define('_ZH_POLL_EDIT', "编辑投票");
/* Layout */
define('_ZH_POLL_LAYOUT_DISPLAY_LAST', "显示最新的投票");
define('_ZH_POLL_LAYOUT_DISPLAY_LAST_DESC', "显示最新的投票介绍");
define('_ZH_POLL_LAYOUT_LIST_POLLS', "投票列表");
define('_ZH_POLL_LAYOUT_LIST_POLLS_DESC', "发布一个全部展开的投票列表");

/* ACL's */
define('_ZH_POLL_ACL_DEFAULT', "管理投票");
define('_ZH_POLL_ACL_ADDPOLL', "添加新投票");
define('_ZH_POLL_ACL_EDITPOLL', "编辑投票");
define('_ZH_POLL_ACL_DELETEPOLL', "删除投票");
define('_ZH_POLL_ACL_UPDATEPROPERTIES', "更新特性");

/* Responses */
define('_ZH_POLL_ANSWER_ADDED', "一个问题被添加");
define('_ZH_POLL_ANSWER_UPDATED', "投票答案被更新");
define('_ZH_POLL_POLL_DELETED', "投票被删除");
define('_ZH_POLL_ANSWER_DELETED', "投票答案被删除");
define('_ZH_POLL_POLL_ENABLED', "投票被激活");
define('_ZH_POLL_POLL_DISABLED', "投票被解除");
define('_ZH_POLL_POLL_ADDED', "投票被添加");
define('_ZH_POLL_POLL_UPDATED', "投票被更新");

/* Errors */
define('_ZH_POLL_ERROR_REQUIRES_QUESTION', "首先写问题");
define('_ZH_POLL_ERROR_REQUIRES_TWO_ANSWERS', "最少两个答案");
define('_ZH_POLL_ERROR_POLL_NOT_ADDED', "投票添加错误");
define('_ZH_POLL_ERROR_POLL_NOT_UPDATED', "投票更新错误");
define('_ZH_POLL_ERROR_POLL_NOT_DISABLED', "解除投票错误");
define('_ZH_POLL_ERROR_ANSWER_DOES_NOT_EXISTS', "投票答案不存在");
define('_ZH_POLL_ERROR_POLL_NOT_ENABLED', "投票激活错误");
define('_ZH_POLL_ERROR_ANSWER_NOT_DELETED', "删除答案错误");
define('_ZH_POLL_ERROR_ANSWER_NOT_UPDATED', "更新答案错误");
define('_ZH_POLL_ERROR_EXCEPTION_ANSWER_NOT_DELETED', "当删除投票时答案不能被删除");
define('_ZH_POLL_ERROR_ANSWER_NOT_ADDED', "添加答案错误");
define('_ZH_POLL_ERROR_VOTE_NOT_ADDED', "添加选票错误");
