<?php
// General Translation file (i18n) for Skeleton gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: 纲要"
 * "Last-Translator: shalibaji <freeyiyi@yahoo.co.uk>"
 * "Language-Team: ZH"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_ZH_SKELETON_NAME', "纲要");
define('_ZH_SKELETON_DESCRIPTION', "使用新组件的基础组件.");
define('_ZH_SKELETON_ACTION_DEFAULT', "默认作用");
define('_ZH_SKELETON_ACTION_DISPLAY', "显示版本");
define('_ZH_SKELETON_ACTION_DISPLAY_DESC', "显示你的Jaws安装版本号.");
define('_ZH_SKELETON_DISPLAY_MESSAGE', "你正在运行Jaws {0}"); // {0} = Jaws version
define('_ZH_SKELETON_ADMIN_MESSAGE', "这个组建是一个例子, 因此他没有管理面板.");