<?php
// General Translation file (i18n) for StaticPage gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: 静态页"
 * "Last-Translator: shalibaji <freeyiyi@yahoo.co.uk>"
 * "Language-Team: ZH"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_ZH_STATICPAGE_NAME', "静态页");
define('_ZH_STATICPAGE_DESCRIPTION', "建立和管理静态内容的组件.");

// Actions
define('_ZH_STATICPAGE_ACTION_DEFAULT', "显示默认页面.");
define('_ZH_STATICPAGE_ACTION_INDEX', "显示静态页面的索引.");
define('_ZH_STATICPAGE_ACTION_PAGE', "显示一个独立页.");

// Layout elements
define('_ZH_STATICPAGE_LAYOUT_PAGES_LIST', "列出页面");
define('_ZH_STATICPAGE_LAYOUT_PAGES_LIST_DESCRIPTION', "列出可以得到的静态页面.");

// ACLs
define('_ZH_STATICPAGE_ACL_DEFAULT', "管理静态页");
define('_ZH_STATICPAGE_ACL_ADDPAGE', "添加页面");
define('_ZH_STATICPAGE_ACL_EDITPAGE', "编辑页面");
define('_ZH_STATICPAGE_ACL_DELETEPAGE', "删除页面");

// Errors
define('_ZH_STATICPAGE_ERROR_PAGE_NOT_ADDED', "添加页错误.");
define('_ZH_STATICPAGE_ERROR_PAGE_NOT_UPDATED', "更新页错误.");
define('_ZH_STATICPAGE_ERROR_PAGE_NOT_DELETED', "删除页错误.");
define('_ZH_STATICPAGE_ERROR_PAGE_NOT_FOUND', "请求的页面不能找到.");
define('_ZH_STATICPAGE_ERROR_UNKNOWN_COLUMN', "未知的种类专栏被提供.");
///FIXME they should not have the same translation.
define('_ZH_STATICPAGE_ERROR_PAGES_NOT_RETRIEVED', "页面索引不能载入.");
define('_ZH_STATICPAGE_ERROR_INDEX_NOT_LOADED', "页面索引不能载入.");
define('_ZH_STATICPAGE_ERROR_PAGE_NOT_MASSIVE_DELETED', "删除页错误");

// Strings
define('_ZH_STATICPAGE_PAGES_LIST', "页面索引");
define('_ZH_STATICPAGE_TITLE_NOT_FOUND', "页面没有找到");
define('_ZH_STATICPAGE_CONTENT_NOT_FOUND', "被请求的页面没有找到，如果你确信它存在，请联络站点管理员.");
define('_ZH_STATICPAGE_TITLE_INDEX', "页面索引"); // ? Where is this used.
define('_ZH_STATICPAGE_MENU_PAGES', "管理页面");
define('_ZH_STATICPAGE_MENU_ADDPAGE', "增加页面");
define('_ZH_STATICPAGE_LAST_UPDATE', "最新更新");
define('_ZH_STATICPAGE_NO_PAGES', "没有找到页面.");
define('_ZH_STATICPAGE_PAGE_CREATED', "页面被创建.");
define('_ZH_STATICPAGE_PAGE_UPDATED', "页面被更新.");
define('_ZH_STATICPAGE_PAGE_DELETED', "页面被删除.");
define('_ZH_STATICPAGE_PAGE_MASSIVE_DELETED', "页面被删除");
define('_ZH_STATICPAGE_PAGE_AUTOUPDATED', "页面被自动保存");
define('_ZH_STATICPAGE_ADD_PAGE', "添加页");
define('_ZH_STATICPAGE_UPDATE_PAGE', "更新页");
define('_ZH_STATICPAGE_PAGE', "页");
define('_ZH_STATICPAGE_CONFIRM_DELETE_PAGE', "你确定要删除这个页面?");
define('_ZH_STATICPAGE_CONFIRM_MASIVE_DELETE_PAGE', "你确定要删除所选页面?");
define('_ZH_STATICPAGE_FASTURL', "Fast URL");
define('_ZH_STATICPAGE_DRAFT', "草稿");
define('_ZH_STATICPAGE_PUBLISHED', "发布的");
define('_ZH_STATICPAGE_STATUS', "状态");
define('_ZH_STATICPAGE_SHOW_TITLE', "显示标题");
