<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Users"
 * "Last-Translator: Ali Fazelzadeh <afz@php.net>"
 * "Language-Team: FA"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_FA_USERS_NAME', "کاربران");
define('_FA_USERS_DESCRIPTION', "راهبری کاربران");
define('_FA_USERS_ACL_DEFAULT', "دسترسی به ابزار راهبری کاربران");
define('_FA_USERS_ACL_MANAGEUSERS', "راهبری کاربران");
define('_FA_USERS_ACL_MANAGEGROUPS', "راهبری گروههای کاربری");
define('_FA_USERS_ACL_MANAGEONLINEUSERS', "راهبری کاربران برخط");
define('_FA_USERS_ACL_MANAGEPROPERTIES', "ویرایش تنظیمات ابزار کاربران");
define('_FA_USERS_ACL_MANAGEUSERACLS', "ویرایش دسترسیهای کاربران");
define('_FA_USERS_ACL_MANAGEGROUPACLS', "ویرایش دسترسیهای گروههای کاربری");
define('_FA_USERS_ACL_EDITUSERNAME', "ویرایش نام کاربری از سوی کاربر");
define('_FA_USERS_ACL_EDITUSERNICKNAME', "ویرایش نام نمایشی از سوی کاربر");
define('_FA_USERS_ACL_EDITUSEREMAIL', "ویرایش نشانی ایمیل از سوی کاربر");
define('_FA_USERS_ACL_EDITUSERPASSWORD', "ویرایش گذرواژه از سوی کاربر");
define('_FA_USERS_ACL_EDITUSERPERSONAL', "ویرایش شناسه‌های فردی از سوی کاربر");
define('_FA_USERS_ACL_EDITUSERCONTACT', "ویرایش شناسه‌های تماس از سوی کاربر");
define('_FA_USERS_ACL_EDITUSERPREFERENCES', "ویرایش تنظیمات از سوی کاربر");
define('_FA_USERS_ACL_MANAGEAUTHENTICATIONMETHOD', "ویرایش روش تایید اعتبار کاربران");
define('_FA_USERS_LAYOUT_LOGINBOX', "بلوک لاگین");
define('_FA_USERS_LAYOUT_LOGINBOX_DESC', "نمایش بلوک لاگین");
define('_FA_USERS_LAYOUT_LOGINLINKS', "پیوندهای کاربری");
define('_FA_USERS_LAYOUT_LOGINLINKS_DESC', "نمایش پیوندهای کاربری");
define('_FA_USERS_LAYOUT_ONLINE_USERS', "کاربران برخط");
define('_FA_USERS_LAYOUT_ONLINE_USERS_DESC', "نمایش فهرست کاربران برخط");
define('_FA_USERS_LAYOUT_ONLINE_STATISTICS', "آمار کاربران برخط");
define('_FA_USERS_LAYOUT_ONLINE_STATISTICS_DESC', "نمایش آمار کاربران هموند و مهمان");
define('_FA_USERS_LAYOUT_LATEST_REGISTERED', "کاربران تازه");
define('_FA_USERS_LAYOUT_LATEST_REGISTERED_DESC', "نمایش فهرست کاربران تازه عضو شده");
define('_FA_USERS_LAYOUT_PROFILE', "درباره کاربر");
define('_FA_USERS_LAYOUT_PROFILE_DESC', "نمایش پروفایل کاربر");
define('_FA_USERS_GROUPS_GROUPNAME', "نام گروه");
define('_FA_USERS_GROUPS_GROUPID', "شناسه گروه");
define('_FA_USERS_GROUPS_GROUP', "گروه");
define('_FA_USERS_GROUPS_GROUPS', "گروههای کاربری");
define('_FA_USERS_GROUPS_ALL_GROUPS', "همه گروهها");
define('_FA_USERS_GROUPS_ADD', "افزودن گروه");
define('_FA_USERS_GROUPS_NOGROUP', "بدون گروه");
define('_FA_USERS_GROUPS_NO_SELECTION', "خواهشمند است یک گروه کاربری را گزینش کنید");
define('_FA_USERS_GROUPS_GROUP_INFO', "اطلاعات گروه کاربری");
define('_FA_USERS_GROUPS_ALREADY_EXISTS', "گروه {0} تکراری است");
define('_FA_USERS_GROUPS_INCOMPLETE_FIELDS', "خواهشمند است نام گروه را وارد کنید");
define('_FA_USERS_GROUPS_UPDATE', "ثبت تغییرات گروه");
define('_FA_USERS_GROUPS_EDIT', "ویرایش گروه");
define('_FA_USERS_GROUPS_DELETE', "زدودن گروه");
define('_FA_USERS_GROUPS_PERMISSIONS', "دسترسیهای گروه");
define('_FA_USERS_GROUPS_ACL_UPDATED', "تغییرات دسترسیهای گروه ثبت شد ");
define('_FA_USERS_GROUPS_GROUP_NOT_EXIST', "گروه دلخواه شما یافت نشد");
define('_FA_USERS_GROUPS_MEMBERS', "کاربران هموند");
define('_FA_USERS_GROUPS_ADD_USER', "افزودن کاربر به یک گروه");
define('_FA_USERS_GROUPS_CONFIRM_DELETE', "آیا می خواهید این گروه را پاک کنید؟");
define('_FA_USERS_GROUPS_CURRENTLY_EDITING_GROUP', "گروه {0} الان در حال ویرایش است");
define('_FA_USERS_GROUPS_MARK_USERS', "کاربرانی را که میخواهید به گروه افزوده شوند را گزینش کنید");
define('_FA_USERS_GROUPS_ACL_RESETED', "دسترسیهای گروه دلخواه شما ریست شد");
define('_FA_USERS_GROUPS_CREATED', "گروه {0} ساخته شد");
define('_FA_USERS_GROUPS_UPDATED', "تغییرات گروه {0} ثبت شد");
define('_FA_USERS_GROUPS_DELETED', "گروه {0} زدوده شد");
define('_FA_USERS_GROUPS_UPDATED_USERS', "تغییرات مربوط به ارتباط بین کاربر و گروه ثبت شد");
define('_FA_USERS_GROUPS_NOT_CREATED', "خطا هنگام ساختن گروه {0}");
define('_FA_USERS_GROUPS_NOT_UPDATED', "خطا هنگام ثبت تغییرات گروه {0}");
define('_FA_USERS_GROUPS_CANT_DELETE', "خطا هنگام زدون گروه {0}");
define('_FA_USERS_USERS', "کاربران");
define('_FA_USERS_ACCOUNT_INFO', "اطلاعات کاربری");
define('_FA_USERS_PERSONAL_INFO', "اطلاعات شخصی");
define('_FA_USERS_PROFILE_INFO', "پروفایل کاربر");
define('_FA_USERS_USERS_ADD', "ایجاد کاربر");
define('_FA_USERS_ACCOUNT_EDIT', "ویرایش کاربر");
define('_FA_USERS_ACCOUNT_DELETE', "زدودن کاربر");
define('_FA_USERS_USERS_GROUPS', "هموندی در گروههای کاربری");
define('_FA_USERS_ACLRULES', "موارد دسترسی");
define('_FA_USERS_USERS_USERNAME', "نام کاربری");
define('_FA_USERS_USERS_PASSWORD', "گذرواژه");
define('_FA_USERS_USERS_NICKNAME', "نام نمایشی");
define('_FA_USERS_USERS_FIRSTNAME', "نام");
define('_FA_USERS_USERS_LASTNAME', "نام خانوادگی");
define('_FA_USERS_USERS_USERID', "شناسه کاربر");
define('_FA_USERS_USERS_TYPE', "نوع");
define('_FA_USERS_USERS_TYPE_SUPERADMIN', "مدیریت کامل");
define('_FA_USERS_USERS_TYPE_NORMAL', "معمولی");
define('_FA_USERS_USERS_STATUS_0', "از کار افتاده");
define('_FA_USERS_USERS_STATUS_1', "پويا");
define('_FA_USERS_USERS_STATUS_2', "وارسی نشده");
define('_FA_USERS_USERS_PRIVACY', "نگهداری داده ها");
define('_FA_USERS_USERS_GENDER', "جنسیت");
define('_FA_USERS_USERS_GENDER_0', "ناشناخته");
define('_FA_USERS_USERS_GENDER_1', "مرد");
define('_FA_USERS_USERS_GENDER_2', "زن");
define('_FA_USERS_USERS_BIRTHDAY', "زادروز");
define('_FA_USERS_USERS_BIRTHDAY_SAMPLE', "مانند: 18 - 05 - 1360");
define('_FA_USERS_USERS_ABOUT', "درباره خود");
define('_FA_USERS_USERS_EXPERIENCES', "کاردانی و توانمندی");
define('_FA_USERS_USERS_OCCUPATIONS', "پیشینه کاری");
define('_FA_USERS_USERS_INTERESTS', "دلبستگی ها");
define('_FA_USERS_USERS_SHOW_ALL', "دیدن همه");
define('_FA_USERS_USERS_CONCURRENT_LOGINS', "تعداد ورود همزمان");
define('_FA_USERS_USERS_EXPIRY_DATE', "زمان پایان");
define('_FA_USERS_USERS_REGISTRATION_DATE', "زمان نام نویسی");
define('_FA_USERS_USERS_SEARCH_TERM', "گزاره");
define('_FA_USERS_USERS_ORDER_TYPE', "چیدمان");
define('_FA_USERS_USERS_SEND_AUTO_PASSWORD', "برای فرستادن گذرواژه تصادفی به ایمیل شما، آنرا خالی بگذارید");
define('_FA_USERS_USERS_PASSWORD_VERIFY', "کنترل مجدد گذرواژه");
define('_FA_USERS_USERS_PASSWORD_OLD', "گذرواژه پیشین");
define('_FA_USERS_USERS_NO_SELECTION', "لطفا، یک کاربر انتخاب کنید");
define('_FA_USERS_USERS_PASSWORDS_DONT_MATCH', "گذرواژه و تایپ مجدد آن با هم یکسان نیستند");
define('_FA_USERS_USERS_INCOMPLETE_FIELDS', "برخی از فیلدها به درستی کامل نشده‌اند");
define('_FA_USERS_USERS_ALREADY_EXISTS', "نام کاربری تکراری است");
define('_FA_USERS_EMAIL_ALREADY_EXISTS', "ایمیل وارد شده تکراری است");
define('_FA_USERS_USERS_CONFIRM_NO_CHANGES', "آیا میخواهید این اطلاعات ذخیره نشود؟ ");
define('_FA_USERS_USERS_SELECT_A_USER', "لطفا، ابتدا یک کاربر را انتخاب کنید");
define('_FA_USERS_USER_NOT_EXIST', "کاربر دلخواه شما یافت نشد");
define('_FA_USERS_USERS_EDIT', "ویرایش کاربر");
define('_FA_USERS_USERS_ACCOUNT_INFO', "اطلاعات کاربر");
define('_FA_USERS_USERS_ACCOUNT_PREF', "تنظیمات اختصاصی");
define('_FA_USERS_USERS_ACCOUNT_UPDATE', "ثبت تغییرات کاربر");
define('_FA_USERS_USERS_PERMISSIONS', "دسترسیها");
define('_FA_USERS_USER_CONFIRM_DELETE', "آیا این کاربر و تمام دادههای فرستادن شده بدست او پاک شوند؟");
define('_FA_USERS_USER_MEMBER_OF_GROUPS', "کاربر {0} هموند گروههای زیر است");
define('_FA_USERS_USER_MEMBER_OF_NO_GROUPS', "کاربر {0} هموند هیچ گروهی نیست");
define('_FA_USERS_THIS_USER', "این کاربر");
define('_FA_USERS_USER_CANT_AUTO_TURN_OFF_CP', "شما نمی‌توانید دسترسی به کنترل پنل را از خود بگیرید");
define('_FA_USERS_GROUPS', "گروههای کاربران");
define('_FA_USERS_USER_CURRENTLY_EDITING', "شما هم اکنون در حال ویرایش کاربر {0} میباشید");
define('_FA_USERS_LOGIN_TITLE', "ورود");
define('_FA_USERS_NOCHANGE_PASSWORD', "اگر تصمیم به تغییر گذرواژه ندارید، آنرا خالی بگذارید");
define('_FA_USERS_USERS_MARK_GROUPS', "انتخاب گروههایی که این کاربر میبایستی هموند آنها باشد");
define('_FA_USERS_RESET_ACL', "ریست دسترسیها");
define('_FA_USERS_RESET_ACL_CONFIRM', "آیا میخواهید دسترسیها را ریست کنید؟");
define('_FA_USERS_PERSONAL', "اطلاعات شخصی");
define('_FA_USERS_PREFERENCES', "تنظیمات کاربر");
define('_FA_USERS_ADVANCED_OPTS_EDITOR', "ویرایشگر کاربر");
define('_FA_USERS_ADVANCED_OPTS_LANGUAGE', "زبان پیش‌فرض");
define('_FA_USERS_ADVANCED_OPTS_THEME', "قالب پیش‌فرض");
define('_FA_USERS_ADVANCED_OPTS_NOT_YET', "هیچ گزینه‌ای انتخاب نشده است");
define('_FA_USERS_USERS_PERMISSION_ALLOW', "اجازه دسترسی");
define('_FA_USERS_USERS_PERMISSION_DENY', "عدم دسترسی");
define('_FA_USERS_USERS_PERMISSION_NONE', "پیش فرض");
define('_FA_USERS_MYACCOUNT_UPDATED', "تغییرات در مشخصات کاربری شما ثبت شد ");
define('_FA_USERS_MYACCOUNT_PASSWORDS_DONT_MATCH', "گذرواژه و تایپ مجدد آن با هم یکسان نیستند");
define('_FA_USERS_MYACCOUNT_INCOMPLETE_FIELDS', "لطفا تمام فیلدها را به درستی پر کنید");
define('_FA_USERS_MYACCOUNT', "مشخصات کاربری من");
define('_FA_USERS_EDIT_ACCOUNT', "ویرایش مشخصات کاربری");
define('_FA_USERS_EDIT_PERSONAL', "ویرایش مشخصات فردی");
define('_FA_USERS_CONTROLPANEL', "صفحه کنترل");
define('_FA_USERS_EDIT_PREFERENCES', "ویرایش تنظیمات ویژه");
define('_FA_USERS_PREFERENCES_UPDATED', "تنظمیات شما ثبت شد");
define('_FA_USERS_LOGINLINKS', "پیوندهای کاربری");
define('_FA_USERS_WELCOME', "خوش آمدید");
define('_FA_USERS_USERS_CREATED', "کاربر {0} ساخته شد");
define('_FA_USERS_USERS_UPDATED', "تغییرات کاربر {0} ثبت شد");
define('_FA_USERS_USERS_ACL_UPDATED', "تغییرات دسترسیها ثبت شد");
define('_FA_USERS_USER_DELETED', "کاربر {0} حذف شد");
define('_FA_USERS_USERS_ACL_RESETED', "دسترسیهای کاربر ریست شد");
define('_FA_USERS_USERS_PERSONALINFO_UPDATED', "تنظیمات شخصی کاربر ثبت شد");
define('_FA_USERS_USERS_ADVANCED_UPDATED', "تنظیمات کاربر ثبت شد");
define('_FA_USERS_USERS_NOT_CREATED', "خطا هنگام ساختن کاربر {0}");
define('_FA_USERS_USERS_NOT_UPDATED', "خطا هنگام ثبت تغییرات مشخصات کاربر {0}");
define('_FA_USERS_USERS_CANT_DELETE', "خطا هنگام حذف کاربر {0}");
define('_FA_USERS_USERS_CANT_DELETE_SELF', "کد کاربری خود را نمیتوانید حذف کنید");
define('_FA_USERS_USERS_PERSONALINFO_NOT_UPDATED', "خطا هنگام ثبت تغییرات مربوط به تنظیمات شخصی کاربر");
define('_FA_USERS_USERS_NOT_ADVANCED_UPDATED', "خطا هنگام ثبت تغییرات مربوط به تنظیمات کاربر");
define('_FA_USERS_ONLINE_USERS', "کاربران برخط");
define('_FA_USERS_ONLINE_ADMIN', "سرپرست");
define('_FA_USERS_ONLINE_ANONY', "ناشناس");
define('_FA_USERS_ONLINE_ACTIVE', "پویا");
define('_FA_USERS_ONLINE_INACTIVE', "ناپویا");
define('_FA_USERS_ONLINE_LAST_ACTIVETIME', "واپسین زمان پویایی");
define('_FA_USERS_ONLINE_BLOCKING_IP', "بستن IP");
define('_FA_USERS_ONLINE_BLOCKING_AGENT', "بستن Agent");
define('_FA_USERS_ONLINE_CONFIRM_THROWOUT', "آیا شما می خواهید این کاربر را بیرون نمایید؟");
define('_FA_USERS_ONLINE_CONFIRM_BLOCKIP', "آیا شما می خواهید این IP را ببندید؟");
define('_FA_USERS_ONLINE_CONFIRM_BLOCKAGENT', "آیا شما می خواهید این Agent را ببندید؟");
define('_FA_USERS_ONLINE_SESSION_DELETED', "نشست دلخواه شما زدوده شد");
define('_FA_USERS_ONLINE_SESSION_NOT_DELETED', "نارسایی در زدودن نشست دلخواه شما روی داد");
define('_FA_USERS_ONLINE_NO_ONLINE', "هیچ کاربر برخطی یافت نشد");
define('_FA_USERS_ONLINE_REGISTERED_COUNT', "کاربران برخط");
define('_FA_USERS_ONLINE_GUESTS_COUNT', "مهمانان برخط");
define('_FA_USERS_PROPERTIES_ANON_REGISTER', "توانایی هموند شدن بازید کنندگان");
define('_FA_USERS_PROPERTIES_ANON_REPETITIVE_EMAIL', "امکان استفاده از ایمیل تکراری برای هموند شدن");
define('_FA_USERS_PROPERTIES_ANON_ACTIVATION', "شیوه فعال‌سازی ");
define('_FA_USERS_PROPERTIES_ACTIVATION_AUTO', "خودکار");
define('_FA_USERS_PROPERTIES_ACTIVATION_BY_USER', "بدست کاربر");
define('_FA_USERS_PROPERTIES_ACTIVATION_BY_ADMIN', "بدست مدیران سایت");
define('_FA_USERS_PROPERTIES_ANON_GROUP', "گروه پیش فرض برای کاربر هموند شده");
define('_FA_USERS_PROPERTIES_PASS_RECOVERY', "توانایی بازیابی گذرواژه");
define('_FA_USERS_PROPERTIES_UPDATED', "تغییرات مشخصات این ابزار، ثبت شد");
define('_FA_USERS_PROPERTIES_CANT_UPDATE', "خطا هنگام بروزرسانی مشخصات");
define('_FA_USERS_NO_PERMISSION_TITLE', "حق دسترسی وجود ندارد");
define('_FA_USERS_NO_PERMISSION_DESC', "متاسفانه دسترسی شما برای اجرای ({0}::{1}) کافی نیست");
define('_FA_USERS_NO_PERMISSION_ANON_DESC', "این به این دلیل است که شما به شکل ناشناس وارد شده‌اید. برای حل این مشکل باید با یک شناسه کاربری معتبر <a href=\"{0}\">لاگین</a> کنید");
define('_FA_USERS_REGISTER', "نام نویسی");
define('_FA_USERS_REGISTER_NOT_ENABLED', "متاسفانه عضوگیری غیر فعال شده است، درخواست خود را به شیوه دیگری به اطلاع مدیریت سایت برسانید.");
define('_FA_USERS_REGISTER_ALREADY_LOGGED', "شما در حال حاضر با یک شناسه کاربری لاگین نموده‌اید، اگر قصد خروج دارید روی <a href=\"{0}\">اینجا</a> کلیک نمایید");
define('_FA_USERS_REGISTER_VALID_USERNAMES', "بکارگیری نشانه های زیر مجاز نمیباشد: ممیز، ممیز برعکس، پرانتز باز و بسته، $ و ...");
define('_FA_USERS_REGISTER_EMAIL_NOT_VALID', "ایمیل وارد شده درست نیست، دوباره بررسی کنید");
define('_FA_USERS_REGISTER_SUBJECT', "نام نویسی - {0}");
define('_FA_USERS_REGISTER_HELLO', "{0} سلام");
define('_FA_USERS_REGISTER_ADMIN_MAIL_MSG', "یک کاربر تازه با ویژگیهای زیر در سایت شما نام نویسی کرده است:");
define('_FA_USERS_REGISTER_MAIL_MSG', "این پیام در برگیرنده مشخصات شناسه کاربری شما می باشد.\n");
define('_FA_USERS_REGISTER_ACTIVATION_MAIL_MSG', "ما یک درخواست نام نویسی با پست الکترونیکی شما دریافت کردیم. برای تکمیل فرآیند ثبت‌نام و فعال شدن شناسه کاربری خود از لینک فعالسازی استفاده نمایید.");
define('_FA_USERS_REGISTER_ACTIVATION_SENDMAIL_FAILED', "هنگام فرستادن لینک فعالسازی به ایمیل شما خطا رخ داد، از این روی به دلایل امنیتی نام کاربری شما از بانک اطلاعاتی حذف گردید.");
define('_FA_USERS_REGISTER_RANDOM_MAIL_MSG', "ما یک درخواست نام نویسی با پست الکترونیکی شما دریافت کردیم. مشخصات شناسه کاربری شما به قرار زیر است. در ضمن از آنجا که گذرواژه خود را به هنگام تکمیل فرم ثبت‌نام  وارد نکردید، پیام دریافتی در برگیرنده گذرواژه شما (که بصورت تصادفی تولید شده است) نیز می باشد.");
define('_FA_USERS_REGISTER_BY_ADMIN_RANDOM_MAIL_MSG', "ما یک درخواست نام نویسی با پست الکترونیکی شما دریافت کردیم. مشخصات شناسه کاربری شما به قرار زیر است ولی قبل از استفاده از آن می بایست توسط گروه مدیران تأیید اعتبار شوید. پس از آن قادر خواهید بود به وب سایت لاگین نمایید.\nدر ضمن از آنجا که گذرواژه خود را به هنگام تکمیل فرم ثبت‌نام  وارد نکردید، این پیام دریافتی در برگیرنده گذرواژه شما (که بصورت تصادفی تولید شده است) نیز می باشد.");
define('_FA_USERS_REGISTER_BY_USER_RANDOM_MAIL_MSG', "ما یک درخواست نام نویسی با پست الکترونیکی شما دریافت کردیم. برای تکمیل فرآیند ثبت‌نام و فعال شدن شناسه کاربری خود از لینک فعالسازی استفاده نمایید.\nدر ضمن از آنجا که گذرواژه خود را به هنگام تکمیل فرم ثبت‌نام  وارد نکردید، این پیام دریافتی در برگیرنده گذرواژه شما (که بصورت تصادفی تولید شده است) نیز می باشد.");
define('_FA_USERS_REGISTER_RANDOM_SENDMAIL_FAILED', "متأسفانه هنگام فرستادن گذرواژه به ایمیل شما خطایی رخ داد. از این روی به دلایل امنیتی نام کاربری شما از بانک اطلاعاتی حذف شد.");
define('_FA_USERS_REGISTER_REGISTERED', "شناسه کاربری شما ساخته شد.");
define('_FA_USERS_REGISTER_REGISTERED_MSG', "شناسه کاربری شما ساخته شد. شما هر زمان که بخواهید می توانید به وب سایت <a href=\"{0}\">لاگین</a> نمایید.\nدر صورتی که گذرواژه برای خود انتخاب نکرده باشید، یک پیام در برگیرنده گذرواژه (که بصورت تصادفی تولید شده) به نشانی پست الکترونیک شما فرستاده می شود، از این روی می بایست پست الکترونیکی خود را برای اطلاع از گذرواژه بررسی نمایید.");
define('_FA_USERS_ACTIVATE_ACTIVATION_LINK', "لینک فعالسازی");
define('_FA_USERS_ACTIVATE_ACTIVATION_BY_ADMIN_MSG', "شناسه کاربری شما ساخته شد، ولی برای فعال شدن آن نیاز به تأیید گروه مدیران سایت می‌باشد. از این رو درخواست شما برای ایشان فرستاده شده است. پس از فعال شدن شناسه کاربری شما، پیامی به پست الکترونیکی شما فرستاده خواهد شد.");
define('_FA_USERS_ACTIVATE_ACTIVATION_BY_USER_MSG', "شناسه کاربری شما ساخته شد، ولی برای فعال شدن آن نیاز به تأیید اعتبار می‌باشد. از این رو پیامی در برگیرنده لینک فعالسازی به ایمیل شما فرستاده می شود. لطفاً برای اطلاعات بیشتر ایمیل خود را بررسی نمایید.");
define('_FA_USERS_ACTIVATE_ACTIVATED_BY_USER_MSG', "شناسه کاربری شما فعال گردید. شما هر زمان که بخواهید می‌توانید به وب سایت <a href=\"{0}\">لاگین</a> نمایید");
define('_FA_USERS_ACTIVATE_ACTIVATED_BY_ADMIN_MSG', "شناسه کاربری فعال گردید");
define('_FA_USERS_ACTIVATE_ACTIVATED_MAIL_MSG', "شناسه کاربری شما فعال گردید. هر زمان که بخواهید می توانید به وب سایت لاگین نمایید.");
define('_FA_USERS_ACTIVATE_NOT_ACTIVATED_SENDMAIL', "متأسفانه هنگام فرستادن لینک فعالسازی خطایی رخ داد. از این روی به دلایل امنیتی نام کاربری شما از بانک اطلاعاتی حذف شد.");
define('_FA_USERS_ACTIVATION_KEY_NOT_VALID', "کلید فعال سازی معتبر نمی‌باشد");
define('_FA_USERS_ACTIVATION_ERROR_ACTIVATION', "بروز خطا هنگام فعالسازی شناسه کاربری");
define('_FA_USERS_FORGOT_LOGIN', "گذرواژه خود را فراموش کرده‌اید؟");
define('_FA_USERS_FORGOT_REMEMBER', "بازیابی گذرواژه");
define('_FA_USERS_FORGOT_REMEMBER_INFO', "برای دریافت اطلاعات کاربری، نشانی ایمیل خود را وارد نمایید.");
define('_FA_USERS_FORGOT_MAIL_SENT', "پیامی بهمراه اطلاعات لازم برای تغییر گذرواژه به ایمیل فرستاده شد.");
define('_FA_USERS_FORGOT_ERROR_SENDING_MAIL', "هنگام فرستادن پیام گذرواژه به پست الکترونیکی شما خطایی رخ داده است، در صورتی که از عملکرد خود مطمئن هستید با مدیر سایت تماس بگیرید.");
define('_FA_USERS_FORGOT_MAIL_MESSAGE', "ما در خواستی مبنی بر اینکه شما گذرواژه خود را فراموش کرده‌اید، دریافت نموده‌ایم. برای تغییر گذرواژه خود از لینک زیر استفاده نمایید. وگرنه به این پیام اعتنایی نکنید.");
define('_FA_USERS_FORGOT_KEY_NOT_VALID', "متاسفانه این کلید معتبر نیست.");
define('_FA_USERS_FORGOT_PASSWORD_CHANGED', "گذرواژه تازه به پست الکترونیکی شما فرستاده شد");
define('_FA_USERS_FORGOT_PASSWORD_CHANGED_SUBJECT', "گذرواژه فرستادن");
define('_FA_USERS_FORGOT_PASSWORD_CHANGED_MESSAGE', "گذرواژه فرستاده شده برای شناسه کاربری شما تعریف شد. شما می توانید گذرواژه خود را در زیر ببینید. برای ویرایش آن با نام کاربری و گذرواژه زیر لاگین کنید.");
define('_FA_USERS_FORGOT_ERROR_CHANGING_PASSWORD', "بروز خطا هنگام تغییر گذرواژه");
