<?php
// General Translation file (i18n) for Skeleton gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Skeleton"
 * "Last-Translator: Ciprian Ghenciu <www.osn.ro>"
 * "Language-Team: RO"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_RO_SKELETON_NAME', "Schelet");
define('_RO_SKELETON_DESCRIPTION', "Un gadget de baza pentru a dezvolta noi gadget-uri.");
define('_RO_SKELETON_ACTION_DEFAULT', "Actiunea de baza");
define('_RO_SKELETON_ACTION_DISPLAY', "Afiseaza versiune");
define('_RO_SKELETON_ACTION_DISPLAY_DESC', "Afiseaza numarul versiunii Jaws instalate.");
define('_RO_SKELETON_DISPLAY_MESSAGE', "Rulati Jaws {0}"); // {0} = Jaws version
define('_RO_SKELETON_ADMIN_MESSAGE', "Acest gadget este numai un exemplu, deci nu are un gadget in Panoul de Control.");