<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Blog"
 * "Last-Translator: Tadashi Jokagi <elf2000@users.sourceforge.net>"
 * "Language-Team: JA"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_JA_BLOG_NAME', "ブログ");
define('_JA_BLOG_DESCRIPTION', "マルチユーザーのブログシステムです。トラックバック、コメント、XML フィードをサポートしています。");
define('_JA_BLOG_ACL_DEFAULT', "ブログ管理");
define('_JA_BLOG_ACL_ADDENTRIES', "エントリーを追加する");
define('_JA_BLOG_ACL_MODIFYOTHERSENTRIES', "その他のエントリーを修正する");
define('_JA_BLOG_ACL_DELETEENTRIES', "エントリーを削除する");
define('_JA_BLOG_ACL_PUBLISHENTRIES', "エントリーを公開する");
define('_JA_BLOG_ACL_MANAGECOMMENTS', "コメントを管理する");
define('_JA_BLOG_ACL_MANAGETRACKBACKS', "トラックバック管理");
define('_JA_BLOG_ACL_MANAGECATEGORIES', "カテゴリーを管理する");
define('_JA_BLOG_ACL_SETTINGS', "設定を変更する");
define('_JA_BLOG_XMLRPC', "Blogger と MetaWeblog API がサポートを提供する Blog XML-RPC サービスです。");
define('_JA_BLOG_WEBSERVICE', "Blog ウェブサービスです。");
define('_JA_BLOG_WSDL', "Blog WSDL サービスです。");
define('_JA_BLOG_LAYOUT_MONTHLY', "月間ビュー");
define('_JA_BLOG_LAYOUT_MONTHLY_DESC', "ブログエントリーの月間の要約を表示します。");
define('_JA_BLOG_LAYOUT_CATEGORIES', "カテゴリー一覧");
define('_JA_BLOG_LAYOUT_CATEGORIES_DESC', "ブログカテゴリーの一覧を表示します。");
define('_JA_BLOG_LAYOUT_RECENT', "最近のエントリー");
define('_JA_BLOG_LAYOUT_RECENT_DESC', "最近のエントリーの要約を表示します。");
define('_JA_BLOG_LAYOUT_RECENTCOMMENTS', "最近のコメント");
define('_JA_BLOG_LAYOUT_RECENTCOMMENTS_DESC', "最近のコメントの要約を表示します。");
define('_JA_BLOG_LAYOUT_CALENDAR', "ブログカレンダー");
define('_JA_BLOG_LAYOUT_CALENDAR_DESC', "マークしたブログエントリーと今月のカレンダーを表示します。");
define('_JA_BLOG_LAYOUT_RSS', "RSS ボタン");
define('_JA_BLOG_LAYOUT_RSS_DESC', "RSS フィードへのリンクを表示します。");
define('_JA_BLOG_LAYOUT_ATOM', "Atom ボタン");
define('_JA_BLOG_LAYOUT_ATOM_DESC', "Atom フィードへのリンクを表示します。");
define('_JA_BLOG_LAYOUT_COMMENTS_RSS', "コメント RSS ボタン");
define('_JA_BLOG_LAYOUT_COMMENTS_RSS_DESC', "コメントの RSS フィードへのリンクを表示します。");
define('_JA_BLOG_LAYOUT_COMMENTS_ATOM', "コメント Atom ボタン");
define('_JA_BLOG_LAYOUT_COMMENTS_ATOM_DESC', "コメントの Atom フィードへのリンクを表示します。");
define('_JA_BLOG_LAYOUT_TAGCLOUD', "ブログのカテゴリークラウド");
define('_JA_BLOG_LAYOUT_TAGCLOUD_DESC', "カテゴリーの投稿に基づいてカテゴリークラウドを表示します");
define('_JA_BLOG_LAYOUT_ENTRIES_BY_CATEGORY', "{0} のエントリー");
define('_JA_BLOG_LAYOUT_ENTRIES_BY_CATEGORY_DESC', "このカテゴリーの最後のエントリーを表示する");
define('_JA_BLOG_ENTRY', "エントリー");
define('_JA_BLOG_RECENT_COMMENTS', "最近のコメント");
define('_JA_BLOG_COMMENTS_ON_POST', "記事のコメント");
define('_JA_BLOG_SUMMARY', "要約");
define('_JA_BLOG_NEW_ENTRY', "新規エントリー");
define('_JA_BLOG_LIST_ENTRIES', "エントリー一覧");
define('_JA_BLOG_ENTRIES_COUNT', "{0} 件のエントリー");
define('_JA_BLOG_COMMENTS', "コメント");
define('_JA_BLOG_HAS_N_COMMENTS', "{0} 個のコメント");
define('_JA_BLOG_MANAGE_COMMENTS', "コメント管理");
define('_JA_BLOG_CATEGORIES', "カテゴリー");
define('_JA_BLOG_SETTINGS', "設定");
define('_JA_BLOG_STATS', "統計");
define('_JA_BLOG_FIRST_ENTRY', "最初のエントリー:");
define('_JA_BLOG_LAST_ENTRY', "最後のエントリー:");
define('_JA_BLOG_TOTAL_ENTRIES', "総エントリー:");
define('_JA_BLOG_AVERAGE_ENTRIES', "一週間あたりの平均エントリー数:");
define('_JA_BLOG_COMMENTS_RECEIVED', "受信コメント数:");
define('_JA_BLOG_RECENT_ENTRIES', "最近のエントリー");
define('_JA_BLOG_DRAFT', "草稿");
define('_JA_BLOG_ADDITIONAL_SETTINGS', "追加設定");
define('_JA_BLOG_DEFAULT_VIEW', "標準の表示");
define('_JA_BLOG_MONTHLY', "月間");
define('_JA_BLOG_LATEST_ENTRY', "最新のエントリー");
define('_JA_BLOG_LAST_ENTRIES', "最近のエントリー一覧");
define('_JA_BLOG_LAST_ENTRIES_LIMIT', "表示するエントリー数");
define('_JA_BLOG_LAST_RECENTENTIES_LIMIT', "表示する最近のエントリー数");
define('_JA_BLOG_LAST_COMMENTS_LIMIT', "表示するコメント数");
define('_JA_BLOG_LAST_RECENTCOMMENTS_LIMIT', "表示する最近のコメント数");
define('_JA_BLOG_DEFAULT_CATEGORY', "標準のカテゴリー");
define('_JA_BLOG_RSS_ENTRIES_LIMIT', "送信する RSS エントリー数");
define('_JA_BLOG_TRACKBACK', "トラックバック");
define('_JA_BLOG_COMMENTS_WHERE', "どこのコメントを表示する");
define('_JA_BLOG_POST_ID_IS', "投稿 ID が");
define('_JA_BLOG_TITLE_CONTAINS', "題名に含む");
define('_JA_BLOG_COMMENT_CONTAINS', "コメント本文に含む");
define('_JA_BLOG_NAME_CONTAINS', "名前を含む");
define('_JA_BLOG_EMAIL_CONTAINS', "電子メールアドレスに含む");
define('_JA_BLOG_URL_CONTAINS', "URL に含む");
define('_JA_BLOG_IP_IS', "IP アドレスが");
define('_JA_BLOG_FILTER', "検索");
define('_JA_BLOG_NO_COMMENTS_FOUND', "検索に一致するコメントはありません。");
define('_JA_BLOG_COMMENT', "コメント");
define('_JA_BLOG_NEW_CATEGORY', "新規カテゴリーを作成する");
define('_JA_BLOG_EDIT_CATEGORY', "カテゴリーを編集する");
define('_JA_BLOG_CATEGORY', "カテゴリー");
define('_JA_BLOG_PARENT', "親");
define('_JA_BLOG_NO_PARENT', "親カテゴリーなし");
define('_JA_BLOG_ADVANCED_MODE', "高度なモード");
define('_JA_BLOG_FASTURL', "Fast URL");
define('_JA_BLOG_FASTURL_COMMENT', "このエントリーを覚えますか? もし「Remember_Me」にした場合、\n例えば <i>index.php?Blog/Remember_Me</i> に移動することでこのエントリーを読むことができます。");
define('_JA_BLOG_READ_MORE', "もっと読む...");
define('_JA_BLOG_POSTED_BY', "Posted by");
define('_JA_BLOG_POSTED_IN', "Posted in");
define('_JA_BLOG_NO_COMMENT', "これにコメントする");
define('_JA_BLOG_LEAVE_COMMENT', "コメントを残す");
define('_JA_BLOG_COMMENTS_XML', "コメント XML フィード");
define('_JA_BLOG_REPLY', "返事");
define('_JA_BLOG_ARCHIVE', "ブログ書庫");
define('_JA_BLOG_RECENT_POSTS', "最近の投稿");
define('_JA_BLOG_SHOW', "見る");
define('_JA_BLOG_PUBLISHED', "公開");
define('_JA_BLOG_AUTHOR', "著作者");
define('_JA_BLOG_DEFAULT_STATUS', "標準の {0} の状態");
define('_JA_BLOG_ENTRY_BODY', "エントリー本文");
define('_JA_BLOG_ALLOW_COMMENTS', "コメントを許可する");
define('_JA_BLOG_ENTRY_NOT_SAVED', "エントリーの保存中に問題です。");
define('_JA_BLOG_TITLE', "題名");
define('_JA_BLOG_MISSING_TITLE', "題名がありません");
define('_JA_BLOG_BODY', "本文");
define('_JA_BLOG_UPDATE', "更新");
define('_JA_BLOG_TRACKBACK_DISABLED', "トラックバックを無効にしました。");
define('_JA_BLOG_DELETE_CONFIRM_CATEGORY', "本当にこのカテゴリーを削除しますか?");
define('_JA_BLOG_DELETE_CONFIRM_ENTRY', "本当にこのエントリーを削除しますか?");
define('_JA_BLOG_DELETE_MASSIVE_COMMENTS', "これらのコメントを本当に削除しますか?");
define('_JA_BLOG_UPDATE_COMMENT', "コメントを更新する");
define('_JA_BLOG_EDIT_TIMESTAMP', "公開日付");
define('_JA_BLOG_SUBMIT_COMMENT', "コメントを送信する");
define('_JA_BLOG_MODERATE_COMMENTS', "コメントをモデレートする");
define('_JA_BLOG_COMMENT_IS_SPAM', "コメントはスパムとマークされました。");
define('_JA_BLOG_COMMENT_IS_WAITING', "コメントはモデレート待ちになりました。");
define('_JA_BLOG_TAGCLOUD', "カテゴリークラウド");
define('_JA_BLOG_COMMENT_CURRENTLY_UPDATING_FOR', "現在投稿 {0} のコメントを更新中");
define('_JA_BLOG_ENTRY_AUTOUPDATED', "エントリーは(草稿として)自動保存です");
define('_JA_BLOG_RECENT_POSTS_BY_CATEGORY', "{0} のエントリー");
define('_JA_BLOG_ENTRY_VISITS', "Visits: {0}");
define('_JA_BLOG_CATEGORY_ADDED', "カテゴリーを追加しました。");
define('_JA_BLOG_CATEGORY_UPDATED', "カテゴリーを更新しました。");
define('_JA_BLOG_CATEGORY_DELETED', "カテゴリーを削除しました。");
define('_JA_BLOG_SETTINGS_SAVED', "設定を保存しました。");
define('_JA_BLOG_COMMENT_UPDATED', "コメントを保存しました。");
define('_JA_BLOG_COMMENT_DELETED', "コメントを削除しました。");
define('_JA_BLOG_ENTRY_ADDED', "エントリーを追加しました。");
define('_JA_BLOG_ENTRY_UPDATED', "エントリーを更新しました。");
define('_JA_BLOG_ENTRY_DELETED', "エントリーを削除しました。");
define('_JA_BLOG_COMMENT_MARKED', "いくつかのコメントは状態を変更しました");
define('_JA_BLOG_TRACKBACK_UPDATED', "トラックバックは保存されました");
define('_JA_BLOG_TRACKBACK_DELETED', "トラックバックは削除されました");
define('_JA_BLOG_TRACKBACK_MARKED', "いくつかのトラックバックは状態を変更されました");
define('_JA_BLOG_ERROR_GETTING_ENTRIES_ASCALENDAR', "エントリーをカレンダーとして取得中にエラーです。");
define('_JA_BLOG_ERROR_ADVANCED_SEARCH', "検索中のエラーです。");
define('_JA_BLOG_ERROR_GETTING_CATEGORIES', "カテゴリーの取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_CATEGORY', "カテゴリーの取得中にエラーです。");
define('_JA_BLOG_ERROR_CATEGORY_NOT_ADDED', "カテゴリーの追加中に問題です。");
define('_JA_BLOG_ERROR_CATEGORY_NOT_UPDATED', "カテゴリーの更新中に問題です。");
define('_JA_BLOG_ERROR_CATEGORIES_LINKED', "エントリーがカテゴリーにリンクしている為、カテゴリーを削除できません。");
define('_JA_BLOG_ERROR_CATEGORY_NOT_DELETED', "カテゴリーの削除中にエラーです。");
define('_JA_BLOG_ERROR_SETTINGS_NOT_SAVED', "設定の保存中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_ENTRIES', "エントリーを取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_ENTRIES_BYDATE', "日付でエントリーを取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_COMMENTS', "コメントを取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_RECENT_COMMENTS', "より最近のコメントを取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_FILTERED_COMMENTS', "フィルターされたコメントを取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_COMMENT', "コメントを取得中にエラーです。");
define('_JA_BLOG_ERROR_COMMENT_NOT_ADDED', "コメントを追加中にエラーです。");
define('_JA_BLOG_ERROR_COMMENT_NOT_UPDATED', "コメントを更新中にエラーです。");
define('_JA_BLOG_ERROR_COMMENT_NOT_DELETED', "コメントを削除中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_ENTRIES_ASARCHIVE', "エントリーを書庫として取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_ENTRIES_ASHISTORY', "エントリーを履歴として取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_ENTRIES_ASCATEGORIES', "エントリーをカテゴリーとして取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_RECENT_ENTRIES', "より最近のエントリーを取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_ATOMSTRUCT', "エントリーの Atom 構造を取得中にエラーです。");
define('_JA_BLOG_ERROR_WRITING_ATOMFILE', "エントリーの Atom ファイルを書き込み中にエラーです。");
define('_JA_BLOG_ERROR_WRITING_RSSFILE', "エントリーの RSS ファイルを書き込み中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_CATEGORIES_ATOMSTRUCT', "Atom 構造を取得中にエラーです。");
define('_JA_BLOG_ERROR_WRITING_CATEGORY_ATOMFILE', "カテゴリーの Atom ファイルを書き込み中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_COMMENTS_ATOMSTRUCT', "カテゴリーの RSS ファイルを書き込み中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_POST_COMMENTS_ATOMSTRUCT', "コメントの Atom 構造を取得中にエラーです。");
define('_JA_BLOG_ERROR_WRITING_POST_COMMENTS_ATOMFILE', "コメントの Atom ファイルを書き込み中にエラーです。");
define('_JA_BLOG_ERROR_WRITING_POST_COMMENTS_RSSFILE', "コメントの RSS ファイルを書き込み中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_ENTRIES_BYCATEGORY', "カテゴリーでエントリーを取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_ENTRY', "エントリーを取得中にエラーでs。");
define('_JA_BLOG_ERROR_GETTING_LAST_ENTRIES', "最後のエントリーを取得中にエラーです。");
define('_JA_BLOG_ERROR_GETTING_MONTH_ENTRIES', "エントリーの月間を取得中にエラーです。");
define('_JA_BLOG_ERROR_ENTRY_NOT_ADDED', "エントリーを追加中にエラーです。");
define('_JA_BLOG_ERROR_ENTRY_NOT_UPDATED', "エントリーを更新中にエラーです。");
define('_JA_BLOG_ERROR_ENTRY_NOT_DELETED', "エントリーを削除中にエラーです。");
define('_JA_BLOG_ERROR_TRACKBACK_NOT_ADDED', "トラックバックを追加中にエラーです。");
define('_JA_BLOG_ERROR_DOES_NOT_EXISTS', "エントリーが存在しません。");
define('_JA_BLOG_ERROR_GETTING_TRACKBACKS', "トラックバックを取得中にエラーです。");
define('_JA_BLOG_ERROR_XMLRPC_NO_GETTEMPLATE_SUPPORT', "JAWS は getTemplate 関数をサポートしていません。");
define('_JA_BLOG_ERROR_XMLRPC_NO_SETTEMPLATE_SUPPORT', "JAWS は setTemplate 関数をサポートしていません。");
define('_JA_BLOG_ERROR_CATEGORY_XML_NOT_GENERATED', "カテゴリーの XML フィードを生成しませんでした");
define('_JA_BLOG_ERROR_TAGCLOUD_CREATION_FAILED', "タグクラウドを作成中にエラーです");
define('_JA_BLOG_ERROR_TRACKBACK_NOT_UPDATED', "トラックバックの更新中にエラーです。");
define('_JA_BLOG_ERROR_TRACKBACK_NOT_DELETED', "トラックバックの削除中にエラーです。");
define('_JA_BLOG_MAIL_COMMENT_TO_ME', "このコメントを自分にメールする...");
define('_JA_BLOG_COMMENT_REPLY', "[ブログコメント] - ブログ ID : {0}");
define('_JA_BLOG_COMMENT_MAIL_VISIT', "ブログのスレッドを参照してください: ");
define('_JA_BLOG_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_JA_BLOG_PAGENAVIGATION_NEXTPAGE', "次のページ");
define('_JA_BLOG_PAGENAVIGATION_PREVIOUSPAGE', "前のページ");
define('_JA_BLOG_MANAGE_TRACKBACKS', "トラックバック");
define('_JA_BLOG_TRACKBACK_WHERE', "表示のとき");
define('_JA_BLOG_TRACKBACK_BLOGNAME', "ブログ名");
define('_JA_BLOG_TRACKBACK_BLOGNAME_CONTAINS', "トラックバックにブログ名を含む");
define('_JA_BLOG_TRACKBACK_EXCERPT', "抜粋");
define('_JA_BLOG_TRACKBACK_EXCERPT_CONTAINS', "トラックバックに抜粋を含む");
define('_JA_BLOG_VIEW_TRACKBACK', "トラックバックの閲覧");
define('_JA_BLOG_TRACKBACKS_CURRENTLY_UPDATING_FOR', "投稿「{0}」のトラックバックを現在閲覧しています");
define('_JA_BLOG_DELETE_MASSIVE_TRACKBACKS', "このトラックバックを本当に削除しますか?");
define('_JA_BLOG_PINGBACK', "ピングバック");
define('_JA_BLOG_PINGBACK_DEFAULT_COMMENT', "{0} のコメントのピングバック");
define('_JA_BLOG_PINGBACK_DEFAULT_TITLE', "{0} のピングバック");
define('_JA_BLOG_PINGBACK_TITLE', "{0} (ピングバック)");
define('_JA_BLOG_PINGBACK_COMMENT', "このコメントはピングバックから来ました: {0}");
