<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Blog"
 * "Last-Translator: ian <ianthelazy[at]gmail[dot]com>"
 * "Language-Team: FR"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_FR_BLOG_NAME', "Blog");
define('_FR_BLOG_DESCRIPTION', "Un système de blog multi-utilisateur. Supporte les trackbacks, les commentaires et les sources de XML.");
define('_FR_BLOG_ACL_DEFAULT', "Administrer le blog");
define('_FR_BLOG_ACL_ADDENTRIES', "Ajouter des articles");
define('_FR_BLOG_ACL_MODIFYOTHERSENTRIES', "Modifier les articles des autres");
define('_FR_BLOG_ACL_DELETEENTRIES', "Éliminer des entrées");
define('_FR_BLOG_ACL_PUBLISHENTRIES', "Publier les articles");
define('_FR_BLOG_ACL_MANAGECOMMENTS', "Administrer les commentaires");
define('_FR_BLOG_ACL_MANAGETRACKBACKS', "Administrer les trackbacks");
define('_FR_BLOG_ACL_MANAGECATEGORIES', "Administrer les catégories");
define('_FR_BLOG_ACL_SETTINGS', "Changer les préférences");
define('_FR_BLOG_XMLRPC', "Service Blog XML-RPC, procure le support de l'API de Blogger et MetaWeblog.");
define('_FR_BLOG_WEBSERVICE', "Blog service web.");
define('_FR_BLOG_WSDL', "Blog service WSDL.");
define('_FR_BLOG_LAYOUT_MONTHLY', "Vue Mensuelle");
define('_FR_BLOG_LAYOUT_MONTHLY_DESC', "Affiche un résumé mensuel des articles du blog.");
define('_FR_BLOG_LAYOUT_CATEGORIES', "Liste des Catégories");
define('_FR_BLOG_LAYOUT_CATEGORIES_DESC', "Affiche une liste des catégories du blog.");
define('_FR_BLOG_LAYOUT_RECENT', "Articles récents");
define('_FR_BLOG_LAYOUT_RECENT_DESC', "Affiche un résumé des articles récents.");
define('_FR_BLOG_LAYOUT_RECENTCOMMENTS', "Commentaires récents");
define('_FR_BLOG_LAYOUT_RECENTCOMMENTS_DESC', "Affiche un résumé des commentaires récents.");
define('_FR_BLOG_LAYOUT_CALENDAR', "Calendrier du Blog");
define('_FR_BLOG_LAYOUT_CALENDAR_DESC', "Affiche un calendrier de ce mois, en marquant les articles du blog.");
define('_FR_BLOG_LAYOUT_RSS', "Bouton RSS");
define('_FR_BLOG_LAYOUT_RSS_DESC', "Affiche un lien vers le flux RSS.");
define('_FR_BLOG_LAYOUT_ATOM', "Bouton Atom");
define('_FR_BLOG_LAYOUT_ATOM_DESC', "Affiche un lien vers la source Atom.");
define('_FR_BLOG_LAYOUT_COMMENTS_RSS', "Bouton de commentaires RSS");
define('_FR_BLOG_LAYOUT_COMMENTS_RSS_DESC', "Affiche un lien vers le bouton de commentaires RSS.");
define('_FR_BLOG_LAYOUT_COMMENTS_ATOM', "Bouton de commentaires Atom");
define('_FR_BLOG_LAYOUT_COMMENTS_ATOM_DESC', "Affiche un lien vers la source de commentaires Atom.");
define('_FR_BLOG_LAYOUT_TAGCLOUD', "Ensemble de catégories de blog");
define('_FR_BLOG_LAYOUT_TAGCLOUD_DESC', "Affiche un ensemble de catégories basé sur les catégories des articles");
define('_FR_BLOG_LAYOUT_ENTRIES_BY_CATEGORY', "Articles de {0}");
define('_FR_BLOG_LAYOUT_ENTRIES_BY_CATEGORY_DESC', "Montrer les derniers articles de cette catégorie");
define('_FR_BLOG_LAYOUT_POPULAR_POSTS', "Articles populaires");
define('_FR_BLOG_LAYOUT_POPULAR_POSTS_DESC', "Afficher la liste des articles populaires");
define('_FR_BLOG_LAYOUT_POSTS_AUTHORS', "Auteurs des articles");
define('_FR_BLOG_LAYOUT_POSTS_AUTHORS_DESC', "Afficher la liste des auteurs");
define('_FR_BLOG_ENTRY', "Article");
define('_FR_BLOG_RECENT_COMMENTS', "Commentaires récents du blog");
define('_FR_BLOG_COMMENTS_ON_POST', "Commentaires sur l'article");
define('_FR_BLOG_SUMMARY', "Résumé");
define('_FR_BLOG_NEW_ENTRY', "Nouvel article");
define('_FR_BLOG_LIST_ENTRIES', "Lister les articles");
define('_FR_BLOG_ENTRIES_COUNT', "{0} articles");
define('_FR_BLOG_COMMENTS', "Commentaires");
define('_FR_BLOG_HAS_N_COMMENTS', "{0} commentaires");
define('_FR_BLOG_MANAGE_COMMENTS', "Commentaires");
define('_FR_BLOG_CATEGORIES', "Catégories");
define('_FR_BLOG_SETTINGS', "Préférences");
define('_FR_BLOG_STATS', "Statistiques");
define('_FR_BLOG_FIRST_ENTRY', "Premier article :");
define('_FR_BLOG_LAST_ENTRY', "Dernier article :");
define('_FR_BLOG_TOTAL_ENTRIES', "Total d'articles :");
define('_FR_BLOG_AVERAGE_ENTRIES', "Moyenne hebdomadaire des articles :");
define('_FR_BLOG_COMMENTS_RECEIVED', "Commentaires reçus :");
define('_FR_BLOG_RECENT_ENTRIES', "Articles récents");
define('_FR_BLOG_DRAFT', "Brouillon");
define('_FR_BLOG_ADDITIONAL_SETTINGS', "Préférences additionnelles");
define('_FR_BLOG_DEFAULT_VIEW', "Vue par défaut");
define('_FR_BLOG_MONTHLY', "Mensuel");
define('_FR_BLOG_LATEST_ENTRY', "Dernier article");
define('_FR_BLOG_LAST_ENTRIES', "Articles récents");
define('_FR_BLOG_LAST_ENTRIES_LIMIT', "Articles à afficher");
define('_FR_BLOG_POPULAR_ENTRIES_LIMIT', "Articles populaires à afficher");
define('_FR_BLOG_LAST_RECENTENTIES_LIMIT', "Articles récents à afficher");
define('_FR_BLOG_LAST_COMMENTS_LIMIT', "Commentaires à afficher");
define('_FR_BLOG_LAST_RECENTCOMMENTS_LIMIT', "Commentaires récents à afficher");
define('_FR_BLOG_DEFAULT_CATEGORY', "Catégorie par défaut");
define('_FR_BLOG_RSS_ENTRIES_LIMIT', "Limite d'articles dans le flux RSS");
define('_FR_BLOG_TRACKBACK', "Trackbacks");
define('_FR_BLOG_COMMENTS_WHERE', "Afficher quand");
define('_FR_BLOG_POST_ID_IS', "l'ID du billet est");
define('_FR_BLOG_TITLE_CONTAINS', "le titre contient");
define('_FR_BLOG_COMMENT_CONTAINS', "le corps du commentaire contient");
define('_FR_BLOG_NAME_CONTAINS', "le nom contient");
define('_FR_BLOG_EMAIL_CONTAINS', "l'adresse e-mail contient");
define('_FR_BLOG_URL_CONTAINS', "l'URL contient");
define('_FR_BLOG_IP_IS', "l'adresse IP est");
define('_FR_BLOG_FILTER', "Rechercher");
define('_FR_BLOG_NO_COMMENTS_FOUND', "Aucun Commentaire ne correspond à votre recherche.");
define('_FR_BLOG_COMMENT', "Commentaire");
define('_FR_BLOG_NEW_CATEGORY', "Créer une nouvelle catégorie");
define('_FR_BLOG_EDIT_CATEGORY', "Éditer la catégorie");
define('_FR_BLOG_CATEGORY', "Catégorie");
define('_FR_BLOG_PARENT', "Parent");
define('_FR_BLOG_NO_PARENT', "Il n'existe pas de catégorie parent");
define('_FR_BLOG_ADVANCED_MODE', "Mode avancé");
define('_FR_BLOG_FASTURL', "URL rapide");
define('_FR_BLOG_FASTURL_COMMENT', "Comment voulez-vous que soit stockée cette article ? Si vous écrivez: Me_rappeler, alors vous pourrez lire cette entrée en allant à : <i>index.php?Blog/Me_rappeler</i>, par exemple.");
define('_FR_BLOG_READ_MORE', "Lire la suite...");
define('_FR_BLOG_POSTED_BY', "Posté par");
define('_FR_BLOG_POSTED_IN', "Posté dans");
define('_FR_BLOG_NO_COMMENT', "Commenter à ce sujet");
define('_FR_BLOG_LEAVE_COMMENT', "Laisser un commentaire");
define('_FR_BLOG_COMMENTS_XML', "Source XML de commentaire");
define('_FR_BLOG_REPLY', "Répondre");
define('_FR_BLOG_ARCHIVE', "Archive du Blog");
define('_FR_BLOG_RECENT_POSTS', "Articles récents");
define('_FR_BLOG_SHOW', "Montrer");
define('_FR_BLOG_PUBLISHED', "Publié");
define('_FR_BLOG_AUTHOR', "Auteur");
define('_FR_BLOG_DEFAULT_STATUS', "Statut par défaut {0}");
define('_FR_BLOG_ENTRY_SUMMARY', "Résumé");
define('_FR_BLOG_ENTRY_BODY', "Corps de l'article");
define('_FR_BLOG_ALLOW_COMMENTS', "Autoriser les commentaires");
define('_FR_BLOG_ENTRY_NOT_SAVED', "Il y a eu un problème lors de la sauvegarde de l'article.");
define('_FR_BLOG_TITLE', "Titre");
define('_FR_BLOG_MISSING_TITLE', "Le titre est absent");
define('_FR_BLOG_BODY', "Corps");
define('_FR_BLOG_UPDATE', "Mettre à jour");
define('_FR_BLOG_TRACKBACK_DISABLED', "Les Trackbacks sont désactivés.");
define('_FR_BLOG_DELETE_CONFIRM_CATEGORY', "Êtes-vous sûr de vouloir supprimer cette catégorie?");
define('_FR_BLOG_DELETE_CONFIRM_ENTRY', "Êtes-vous sûr de vouloir supprimer cet article ?");
define('_FR_BLOG_DELETE_MASSIVE_ENTRIES', "Êtes-vous sûr de vouloir supprimer cet/ces article(s) ?");
define('_FR_BLOG_DELETE_MASSIVE_COMMENTS', "Êtes-vous sûr de vouloir supprimer ce/ces commentaire(s)?");
define('_FR_BLOG_UPDATE_COMMENT', "Commentaire de mise à jour");
define('_FR_BLOG_EDIT_TIMESTAMP', "Date de publication");
define('_FR_BLOG_SUBMIT_COMMENT', "Envoyer le commentaire");
define('_FR_BLOG_MODERATE_COMMENTS', "Modérer les commentaires");
define('_FR_BLOG_COMMENT_IS_SPAM', "Votre commentaire a été marqué comme spam.");
define('_FR_BLOG_COMMENT_IS_WAITING', "Votre commentaire est en attente de modération.");
define('_FR_BLOG_TAGCLOUD', "Ensemble de catégorie");
define('_FR_BLOG_COMMENT_CURRENTLY_UPDATING_FOR', "Vous mettez actuellement à jour un commentaire pour le billet {0}");
define('_FR_BLOG_ENTRY_AUTOUPDATED', "L'article a été sauvegardée automatiquement (en tant que brouillon)");
define('_FR_BLOG_RECENT_POSTS_BY_CATEGORY', "Articles de {0}");
define('_FR_BLOG_ENTRY_VISITS', "Visites: {0}");
define('_FR_BLOG_POPULAR_POSTS', "Articles populaires");
define('_FR_BLOG_POSTS_AUTHORS', "Auteurs");
define('_FR_BLOG_CATEGORY_ADDED', "Une catégorie a été ajoutée");
define('_FR_BLOG_CATEGORY_UPDATED', "La catégorie a été mise à jour");
define('_FR_BLOG_CATEGORY_DELETED', "La catégorie a été supprimée");
define('_FR_BLOG_SETTINGS_SAVED', "Les préférences ont été sauvegardées");
define('_FR_BLOG_COMMENT_UPDATED', "Le commentaire a été sauvegardé");
define('_FR_BLOG_COMMENT_DELETED', "Le commentaire a été supprimé");
define('_FR_BLOG_ENTRY_ADDED', "Un article a été ajouté");
define('_FR_BLOG_ENTRY_UPDATED', "L'article a été mis à jour");
define('_FR_BLOG_ENTRY_DELETED', "L'article a été supprimé");
define('_FR_BLOG_COMMENT_MARKED', "Certains commentaires ont changés de statut");
define('_FR_BLOG_TRACKBACK_UPDATED', "Le trackback a été sauvegardé");
define('_FR_BLOG_TRACKBACK_DELETED', "Le trackback a été supprimé");
define('_FR_BLOG_TRACKBACK_MARKED', "Certains trackbacks ont changés de statut");
define('_FR_BLOG_ERROR_GETTING_ENTRIES_ASCALENDAR', "Une erreur est survenue lors de la récupération des articles comme calendrier");
define('_FR_BLOG_ERROR_ADVANCED_SEARCH', "Une erreur de recherche est survenue");
define('_FR_BLOG_ERROR_GETTING_CATEGORIES', "Une erreur est survenue lors de la récupération des catégories");
define('_FR_BLOG_ERROR_GETTING_CATEGORY', "Une erreur est survenue lors de la récupération de la catégorie");
define('_FR_BLOG_ERROR_CATEGORY_NOT_ADDED', "Une erreur est survenue lors de l'ajout de la catégorie");
define('_FR_BLOG_ERROR_CATEGORY_NOT_UPDATED', "Une erreur est survenue lors de la mise à jour de la catégorie");
define('_FR_BLOG_ERROR_CATEGORIES_LINKED', "Il n'a pas été possible d'effacer la catégorie car elle a des articles liés");
define('_FR_BLOG_ERROR_CATEGORY_NOT_DELETED', "Une erreur est survenue lors de la suppression de la catégorie");
define('_FR_BLOG_ERROR_SETTINGS_NOT_SAVED', "Une erreur est survenue lors de la sauvegarde des préférences");
define('_FR_BLOG_ERROR_GETTING_ENTRIES', "Une erreur est survenue lors de la récupération des articles");
define('_FR_BLOG_ERROR_GETTING_ENTRIES_BYDATE', "Une erreur est survenue lors de la récupération des articles par date");
define('_FR_BLOG_ERROR_GETTING_COMMENTS', "Une erreur est survenue lors de la récupération des commentaires");
define('_FR_BLOG_ERROR_GETTING_RECENT_COMMENTS', "Une erreur est survenue lors de la récupération des commentaires récents");
define('_FR_BLOG_ERROR_GETTING_FILTERED_COMMENTS', "Une erreur est survenue lors de la récupération des commentaires filtrés");
define('_FR_BLOG_ERROR_GETTING_COMMENT', "Une erreur est survenue lors de la récupération des commentaires");
define('_FR_BLOG_ERROR_COMMENT_NOT_ADDED', "Une erreur est survenue lors de l'ajout du commentaire");
define('_FR_BLOG_ERROR_COMMENT_NOT_UPDATED', "Une erreur est survenue lors de la mise à jour du commentaire");
define('_FR_BLOG_ERROR_COMMENT_NOT_DELETED', "Une erreur est survenue lors de la suppression du commentaire");
define('_FR_BLOG_ERROR_GETTING_ENTRIES_ASARCHIVE', "Une erreur est survenue lors de la récupération des articles comme archive");
define('_FR_BLOG_ERROR_GETTING_ENTRIES_ASHISTORY', "Une erreur est survenue lors de la récupération des articles comme historique");
define('_FR_BLOG_ERROR_GETTING_ENTRIES_ASCATEGORIES', "Une erreur est survenue lors de la récupération des articles comme catégories");
define('_FR_BLOG_ERROR_GETTING_RECENT_ENTRIES', "Une erreur est survenue lors de l'acquisition des entrées récentes");
define('_FR_BLOG_ERROR_GETTING_ATOMSTRUCT', "Une erreur est survenue lors de la récupération de la structure Atom des articles");
define('_FR_BLOG_ERROR_WRITING_ATOMFILE', "Une erreur est survenue lors de l'écriture de l'archive Atom des articles");
define('_FR_BLOG_ERROR_WRITING_RSSFILE', "Une erreur est survenue lors de l'écriture du fichier RSS d'articles");
define('_FR_BLOG_ERROR_GETTING_CATEGORIES_ATOMSTRUCT', "Une erreur est survenue lors de la récupération de la structure Atom des catégories");
define('_FR_BLOG_ERROR_WRITING_CATEGORY_ATOMFILE', "Une erreur est survenue lors de l'écriture deu fichier Atom des catégories");
define('_FR_BLOG_ERROR_GETTING_COMMENTS_ATOMSTRUCT', "Une erreur est survenue lors de l'écriture du fichier RSS des catégories");
define('_FR_BLOG_ERROR_GETTING_POST_COMMENTS_ATOMSTRUCT', "Une erreur est survenue lors de la récupération de la structure Atom des commentaires");
define('_FR_BLOG_ERROR_WRITING_POST_COMMENTS_ATOMFILE', "Une erreur est survenue lors de l'écriture du fichier Atom des commentaires");
define('_FR_BLOG_ERROR_WRITING_POST_COMMENTS_RSSFILE', "Une erreur est survenue lors de l'écriture du fichier RSS des commentaires");
define('_FR_BLOG_ERROR_GETTING_ENTRIES_BYCATEGORY', "Une erreur est survenue lors de la récupération des articles par catégorie");
define('_FR_BLOG_ERROR_GETTING_ENTRY', "Une erreur est survenue lors de la récupération de l'article");
define('_FR_BLOG_ERROR_GETTING_LAST_ENTRIES', "Une erreur est survenue lors de la récupération des derniers articles");
define('_FR_BLOG_ERROR_GETTING_MONTH_ENTRIES', "Une erreur est survenue lors de la récupération du mois des articles");
define('_FR_BLOG_ERROR_ENTRY_NOT_ADDED', "Une erreur est survenue lors de l'ajout de l'article");
define('_FR_BLOG_ERROR_ENTRY_NOT_UPDATED', "Une erreur est survenue lors de la mise à jour de l'article");
define('_FR_BLOG_ERROR_ENTRY_NOT_DELETED', "Une erreur est survenue lors de la suppression de l'article");
define('_FR_BLOG_ERROR_TRACKBACK_NOT_ADDED', "Une erreur est survenue lors de l'ajout du trackback");
define('_FR_BLOG_ERROR_DOES_NOT_EXISTS', "L'article n'existe pas");
define('_FR_BLOG_ERROR_GETTING_TRACKBACKS', "Une erreur est survenue lors de la récupération des trackbacks");
define('_FR_BLOG_ERROR_XMLRPC_NO_GETTEMPLATE_SUPPORT', "JAWS ne supporte pas la fonction getTemplate");
define('_FR_BLOG_ERROR_XMLRPC_NO_SETTEMPLATE_SUPPORT', "JAWS ne supporte pas la fonction  setTemplate");
define('_FR_BLOG_ERROR_CATEGORY_XML_NOT_GENERATED', "La source XML de la catégorie n'a pas été générée");
define('_FR_BLOG_ERROR_TAGCLOUD_CREATION_FAILED', "Une erreur est survenue lors de la création du nuage de tags");
define('_FR_BLOG_ERROR_TRACKBACK_NOT_UPDATED', "Une erreur est survenue lors de la mise à jour du trackback");
define('_FR_BLOG_ERROR_TRACKBACK_NOT_DELETED', "Une erreur est survenue lors de la suppression du trackback");
define('_FR_BLOG_MAIL_COMMENT_TO_ME', "Envoyez-moi ce commentaire par e-mail...");
define('_FR_BLOG_COMMENT_REPLY', "[Commentaire de blog] - pour l'ID de blog: {0}");
define('_FR_BLOG_COMMENT_MAIL_VISIT', "Voir le fil du blog à: ");
define('_FR_BLOG_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_FR_BLOG_PAGENAVIGATION_NEXTPAGE', "Page suivante");
define('_FR_BLOG_PAGENAVIGATION_PREVIOUSPAGE', "Page précédente");
define('_FR_BLOG_MANAGE_TRACKBACKS', "Trackbacks");
define('_FR_BLOG_TRACKBACK_WHERE', "Afficher quand");
define('_FR_BLOG_TRACKBACK_BLOGNAME', "Le nom du blog");
define('_FR_BLOG_TRACKBACK_BLOGNAME_CONTAINS', "le nom du blog du trackback contient");
define('_FR_BLOG_TRACKBACK_EXCERPT', "Extrait");
define('_FR_BLOG_TRACKBACK_EXCERPT_CONTAINS', "l'extrait du trackback contient");
define('_FR_BLOG_VIEW_TRACKBACK', "Voir le trackback");
define('_FR_BLOG_TRACKBACKS_CURRENTLY_UPDATING_FOR', "Vous lisez actuellement un trackback pour l'article {0}");
define('_FR_BLOG_DELETE_MASSIVE_TRACKBACKS', "Voulez vous vraiment supprimer ce/ces trackback(s) ?");
define('_FR_BLOG_PINGBACK', "Pingback");
define('_FR_BLOG_PINGBACK_DEFAULT_COMMENT', "Commentaire pingback de {0}");
define('_FR_BLOG_PINGBACK_DEFAULT_TITLE', "Pingback de {0}");
define('_FR_BLOG_PINGBACK_TITLE', "{0} (depuis le pingback)");
define('_FR_BLOG_PINGBACK_COMMENT', "Ce commentaire provient du pingback {0}");
