<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Blog"
 * "Last-Translator: Alessio Calafiore <lex@iokoi.com>"
 * "Language-Team: IT"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_IT_BLOG_NAME', "Blog");
define('_IT_BLOG_DESCRIPTION', "Un sistema di blog multi-utente. Supporta trackbacks, commenti, e feed XML.");
define('_IT_BLOG_ACL_DEFAULT', "Amministra blog");
define('_IT_BLOG_ACL_ADDENTRIES', "Aggiungi post");
define('_IT_BLOG_ACL_MODIFYOTHERSENTRIES', "Modifica altri post");
define('_IT_BLOG_ACL_DELETEENTRIES', "Elimina post");
define('_IT_BLOG_ACL_PUBLISHENTRIES', "Pubblica post");
define('_IT_BLOG_ACL_MANAGECOMMENTS', "Gestione commenti");
define('_IT_BLOG_ACL_MANAGETRACKBACKS', "Gestione trackbacks");
define('_IT_BLOG_ACL_MANAGECATEGORIES', "Gestione categorie");
define('_IT_BLOG_ACL_SETTINGS', "Cambia impostazioni");
define('_IT_BLOG_XMLRPC', "Servizio Blog XML-RPC, integra il supporto per le API di Blogger e MetaWeblog.");
define('_IT_BLOG_WEBSERVICE', "Servizio web Blog.");
define('_IT_BLOG_WSDL', "Servizio Blog WSDL.");
define('_IT_BLOG_LAYOUT_MONTHLY', "Vista mensile");
define('_IT_BLOG_LAYOUT_MONTHLY_DESC', "Visualizza un riassunto mensile dei post.");
define('_IT_BLOG_LAYOUT_CATEGORIES', "Lista categorie");
define('_IT_BLOG_LAYOUT_CATEGORIES_DESC', "Visualizza l'elenco delle categorie del blog.");
define('_IT_BLOG_LAYOUT_RECENT', "Post recenti");
define('_IT_BLOG_LAYOUT_RECENT_DESC', "Visualizza un elenco di post recenti.");
define('_IT_BLOG_LAYOUT_RECENTCOMMENTS', "Commenti recenti");
define('_IT_BLOG_LAYOUT_RECENTCOMMENTS_DESC', "Visualizza un elenco di commenti recenti.");
define('_IT_BLOG_LAYOUT_CALENDAR', "Calendario del Blog");
define('_IT_BLOG_LAYOUT_CALENDAR_DESC', "Visualizza un calendario del mese in corso, con i post in evidenza.");
define('_IT_BLOG_LAYOUT_RSS', "Pulsante RSS");
define('_IT_BLOG_LAYOUT_RSS_DESC', "Visualizza un collegamento al feed RSS.");
define('_IT_BLOG_LAYOUT_ATOM', "Pulsante Atom");
define('_IT_BLOG_LAYOUT_ATOM_DESC', "Visualizza un collegamento al feed Atom.");
define('_IT_BLOG_LAYOUT_COMMENTS_RSS', "Pulsante commenti RSS");
define('_IT_BLOG_LAYOUT_COMMENTS_RSS_DESC', "Visualizza un collegamento al feed RSS dei commenti.");
define('_IT_BLOG_LAYOUT_COMMENTS_ATOM', "Pulsante commenti Atom");
define('_IT_BLOG_LAYOUT_COMMENTS_ATOM_DESC', "Visualizza un collegamento al feed Atom dei commenti.");
define('_IT_BLOG_LAYOUT_TAGCLOUD', "Lista Pesata Categorie (Tag cloud)");
define('_IT_BLOG_LAYOUT_TAGCLOUD_DESC', "Mostra una Lista Pesata (Tag Cloud) in base alle categorie di post");
define('_IT_BLOG_LAYOUT_ENTRIES_BY_CATEGORY', "Post di {0}");
define('_IT_BLOG_LAYOUT_ENTRIES_BY_CATEGORY_DESC', "Mostra gli ultimi post di questa categoria");
define('_IT_BLOG_ENTRY', "Post");
define('_IT_BLOG_RECENT_COMMENTS', "Commenti recenti");
define('_IT_BLOG_COMMENTS_ON_POST', "Commenti sul Post");
define('_IT_BLOG_SUMMARY', "Riassunto");
define('_IT_BLOG_NEW_ENTRY', "Nuovo Post");
define('_IT_BLOG_LIST_ENTRIES', "Elenco Post");
define('_IT_BLOG_ENTRIES_COUNT', "{0} post");
define('_IT_BLOG_COMMENTS', "Commenti");
define('_IT_BLOG_HAS_N_COMMENTS', "{0} commenti");
define('_IT_BLOG_MANAGE_COMMENTS', "Gestisci Commenti");
define('_IT_BLOG_CATEGORIES', "Categorie");
define('_IT_BLOG_SETTINGS', "Impostazioni");
define('_IT_BLOG_STATS', "Statistiche");
define('_IT_BLOG_FIRST_ENTRY', "Primo post:");
define('_IT_BLOG_LAST_ENTRY', "Ultimo Post:");
define('_IT_BLOG_TOTAL_ENTRIES', "Post Totali:");
define('_IT_BLOG_AVERAGE_ENTRIES', "Media post per Settimana:");
define('_IT_BLOG_COMMENTS_RECEIVED', "Commenti Ricevuti:");
define('_IT_BLOG_RECENT_ENTRIES', "Post Recenti");
define('_IT_BLOG_DRAFT', "Bozza");
define('_IT_BLOG_ADDITIONAL_SETTINGS', "Impostazioni Aggiuntive");
define('_IT_BLOG_DEFAULT_VIEW', "Vista predefinita");
define('_IT_BLOG_MONTHLY', "Mensile");
define('_IT_BLOG_LATEST_ENTRY', "Ultimo Post");
define('_IT_BLOG_LAST_ENTRIES', "Post Recenti");
define('_IT_BLOG_LAST_ENTRIES_LIMIT', "Post da Visualizzare");
define('_IT_BLOG_LAST_RECENTENTIES_LIMIT', "Post recenti da Visualizzare");
define('_IT_BLOG_LAST_COMMENTS_LIMIT', "Commenti da visualizzare");
define('_IT_BLOG_LAST_RECENTCOMMENTS_LIMIT', "Commenti recenti da visualizzare");
define('_IT_BLOG_DEFAULT_CATEGORY', "Categoria predefinita");
define('_IT_BLOG_RSS_ENTRIES_LIMIT', "Post RSS da inviare");
define('_IT_BLOG_TRACKBACK', "Trackbacks");
define('_IT_BLOG_COMMENTS_WHERE', "Visualizza quando");
define('_IT_BLOG_POST_ID_IS', "l'ID del post e'");
define('_IT_BLOG_TITLE_CONTAINS', "il titolo contiene");
define('_IT_BLOG_COMMENT_CONTAINS', "il corpo del commento contiene");
define('_IT_BLOG_NAME_CONTAINS', "il nome contiene");
define('_IT_BLOG_EMAIL_CONTAINS', "l'indirizzo e-mail contiene");
define('_IT_BLOG_URL_CONTAINS', "l'URL contiene");
define('_IT_BLOG_IP_IS', "l'indirizzo ip e'");
define('_IT_BLOG_FILTER', "Cerca");
define('_IT_BLOG_NO_COMMENTS_FOUND', "Nessun commento trovato.");
define('_IT_BLOG_COMMENT', "Commento");
define('_IT_BLOG_NEW_CATEGORY', "Crea nuova categoria");
define('_IT_BLOG_EDIT_CATEGORY', "Modifica Categora");
define('_IT_BLOG_CATEGORY', "Categoria");
define('_IT_BLOG_PARENT', "Superiore");
define('_IT_BLOG_NO_PARENT', "Nessuna categoria superiore");
define('_IT_BLOG_ADVANCED_MODE', "Modalita' Avanzata");
define('_IT_BLOG_FASTURL', "URL Rapido");
define('_IT_BLOG_FASTURL_COMMENT', "Come vuoi ricordare questo post? Se scrivi: Ricordami, puoi in seguito leggere questo post andando: <i>index.php?Blog/Ricordami</i>, per esempio.");
define('_IT_BLOG_READ_MORE', "Leggi tutto...");
define('_IT_BLOG_POSTED_BY', "Pubblicato da");
define('_IT_BLOG_POSTED_IN', "Pubblicato in");
define('_IT_BLOG_NO_COMMENT', "Commenta questo");
define('_IT_BLOG_LEAVE_COMMENT', "Lascia un Commento");
define('_IT_BLOG_COMMENTS_XML', "Commento feed XML");
define('_IT_BLOG_REPLY', "Rispondi");
define('_IT_BLOG_ARCHIVE', "Archivio Blog");
define('_IT_BLOG_RECENT_POSTS', "Post recenti");
define('_IT_BLOG_SHOW', "Visualizza");
define('_IT_BLOG_PUBLISHED', "Pubblicato");
define('_IT_BLOG_AUTHOR', "Autore");
define('_IT_BLOG_DEFAULT_STATUS', "Stato {0} Predefinito");
define('_IT_BLOG_ENTRY_BODY', "Corpo del post");
define('_IT_BLOG_ALLOW_COMMENTS', "Abilita Commenti");
define('_IT_BLOG_ENTRY_NOT_SAVED', "Si e' verificato un problema salvando il post.");
define('_IT_BLOG_TITLE', "Titolo");
define('_IT_BLOG_MISSING_TITLE', "Manca il titolo");
define('_IT_BLOG_BODY', "Corpo");
define('_IT_BLOG_UPDATE', "Aggiorna");
define('_IT_BLOG_TRACKBACK_DISABLED', "I Trackbacks sono stati disabilitati.");
define('_IT_BLOG_DELETE_CONFIRM_CATEGORY', "Sei sicuro di voler eliminare questa categoria?");
define('_IT_BLOG_DELETE_CONFIRM_ENTRY', "Sei sicuro di voler eliminare questo post?");
define('_IT_BLOG_DELETE_MASSIVE_COMMENTS', "Sei sicuro di voler cancellare questo/questi commento/i?");
define('_IT_BLOG_UPDATE_COMMENT', "Aggiorna Commento");
define('_IT_BLOG_EDIT_TIMESTAMP', "Data di pubblicazione");
define('_IT_BLOG_SUBMIT_COMMENT', "Invia commento");
define('_IT_BLOG_MODERATE_COMMENTS', "Modera i commenti");
define('_IT_BLOG_COMMENT_IS_SPAM', "Il tuo commento e' stato segnato come spam.");
define('_IT_BLOG_COMMENT_IS_WAITING', "Il tuo commento e' in attesa di moderazione.");
define('_IT_BLOG_TAGCLOUD', "Tags Categorie");
define('_IT_BLOG_COMMENT_CURRENTLY_UPDATING_FOR', "Stai aggiornando il commento per il post {0}");
define('_IT_BLOG_ENTRY_AUTOUPDATED', "Il testo e' stato salvato automaticamente (come bozza)");
define('_IT_BLOG_RECENT_POSTS_BY_CATEGORY', "Post in {0}");
define('_IT_BLOG_ENTRY_VISITS', "Visite: {0}");
define('_IT_BLOG_CATEGORY_ADDED', "Una categoria e' stata aggiunta");
define('_IT_BLOG_CATEGORY_UPDATED', "La categoria e' stata aggiornata");
define('_IT_BLOG_CATEGORY_DELETED', "La categoria e' stata eliminata");
define('_IT_BLOG_SETTINGS_SAVED', "Le impostazioni sono state salvate");
define('_IT_BLOG_COMMENT_UPDATED', "Il commento e' stato salvato");
define('_IT_BLOG_COMMENT_DELETED', "Il commento e' stato eliminato");
define('_IT_BLOG_ENTRY_ADDED', "Il post e' stato aggiunto");
define('_IT_BLOG_ENTRY_UPDATED', "Il post e' stato aggiornato");
define('_IT_BLOG_ENTRY_DELETED', "Il post e' stato eliminato");
define('_IT_BLOG_COMMENT_MARKED', "Alcuni commenti hanno cambiato il loro stato");
define('_IT_BLOG_TRACKBACK_UPDATED', "Il trackback e' stato salvato");
define('_IT_BLOG_TRACKBACK_DELETED', "Il trackback e' stato cancellato");
define('_IT_BLOG_TRACKBACK_MARKED', "Alcuni trackback hanno cambiato il loro stato");
define('_IT_BLOG_ERROR_GETTING_ENTRIES_ASCALENDAR', "Si e' verificato un problema aprendo i post nel calendario");
define('_IT_BLOG_ERROR_ADVANCED_SEARCH', "Si e' verificato un problema nella ricerca");
define('_IT_BLOG_ERROR_GETTING_CATEGORIES', "Si e' verificato un errore caricando le categorie");
define('_IT_BLOG_ERROR_GETTING_CATEGORY', "Si e' verificato un errore caricando la categoria");
define('_IT_BLOG_ERROR_CATEGORY_NOT_ADDED', "Si e' verificato un errore aggiungendo la categoria");
define('_IT_BLOG_ERROR_CATEGORY_NOT_UPDATED', "Si e' verificato un errore aggiornando la categoria");
define('_IT_BLOG_ERROR_CATEGORIES_LINKED', "Non e' possibile eliminare la categoria perche' ci sono post collegati");
define('_IT_BLOG_ERROR_CATEGORY_NOT_DELETED', "Si e' verificato un errore eliminando la categoria");
define('_IT_BLOG_ERROR_SETTINGS_NOT_SAVED', "Si e' verificato un errore salvando le impostazioni");
define('_IT_BLOG_ERROR_GETTING_ENTRIES', "Si e' verificato un errore caricando i post");
define('_IT_BLOG_ERROR_GETTING_ENTRIES_BYDATE', "Si e' verificato un errore caricando i post per data");
define('_IT_BLOG_ERROR_GETTING_COMMENTS', "Si e' verificato un errore caricando i commenti");
define('_IT_BLOG_ERROR_GETTING_RECENT_COMMENTS', "Si e' verificato un errore caricando i commenti piu' recenti");
define('_IT_BLOG_ERROR_GETTING_FILTERED_COMMENTS', "Si e' verificato un errore caricando i commenti filtrati");
define('_IT_BLOG_ERROR_GETTING_COMMENT', "Si e' verificato un errore caricando il commento");
define('_IT_BLOG_ERROR_COMMENT_NOT_ADDED', "Si e' verificato un errore aggiungendo il commento");
define('_IT_BLOG_ERROR_COMMENT_NOT_UPDATED', "Si e' verificato un errore aggiornando il commento");
define('_IT_BLOG_ERROR_COMMENT_NOT_DELETED', "Si e' verificato un errore eliminando il commento");
define('_IT_BLOG_ERROR_GETTING_ENTRIES_ASARCHIVE', "Si e' verificato un errore caricando i post come archivio");
define('_IT_BLOG_ERROR_GETTING_ENTRIES_ASHISTORY', "Si e' verificato un errore caricando i post come storico");
define('_IT_BLOG_ERROR_GETTING_ENTRIES_ASCATEGORIES', "Si e' verificato un errore caricando i post per categorie");
define('_IT_BLOG_ERROR_GETTING_RECENT_ENTRIES', "Si e' verificato un errore caricando i post piu' recenti");
define('_IT_BLOG_ERROR_GETTING_ATOMSTRUCT', "Si e' verificato un errore caricando la struttura Atom dei post");
define('_IT_BLOG_ERROR_WRITING_ATOMFILE', "Si e' verificato un errore scrivendo il file Atom dei post");
define('_IT_BLOG_ERROR_WRITING_RSSFILE', "Si e' verificato un errore scrivendo il file RSS dei post");
define('_IT_BLOG_ERROR_GETTING_CATEGORIES_ATOMSTRUCT', "Si e' verificato un errore caricando la struttura Atom delle categorie");
define('_IT_BLOG_ERROR_WRITING_CATEGORY_ATOMFILE', "Si e' verificato un errore scrivendo il file Atom della categoria");
define('_IT_BLOG_ERROR_GETTING_COMMENTS_ATOMSTRUCT', "Si e' verificato un errore caricando la struttura Atom dei commenti");
define('_IT_BLOG_ERROR_GETTING_POST_COMMENTS_ATOMSTRUCT', "Si e' verificato un errore caricando la struttura Atom dei commenti");
define('_IT_BLOG_ERROR_WRITING_POST_COMMENTS_ATOMFILE', "Si e' verificato un errore scrivendo il file Atom dei commenti");
define('_IT_BLOG_ERROR_WRITING_POST_COMMENTS_RSSFILE', "Si e' verificato un errore scrivendo il file RSS dei commenti");
define('_IT_BLOG_ERROR_GETTING_ENTRIES_BYCATEGORY', "Si e' verificato un errore caricando i post per categoria");
define('_IT_BLOG_ERROR_GETTING_ENTRY', "Si e' verificato un errore caricando il post");
define('_IT_BLOG_ERROR_GETTING_LAST_ENTRIES', "Si e' verificato un errore caricando gli ultimi post");
define('_IT_BLOG_ERROR_GETTING_MONTH_ENTRIES', "Si e' verificato un errore caricando i mesi sei post");
define('_IT_BLOG_ERROR_ENTRY_NOT_ADDED', "Si e' verificato un errore aggiungendo il post");
define('_IT_BLOG_ERROR_ENTRY_NOT_UPDATED', "Si e' verificato un errore aggiornando il post");
define('_IT_BLOG_ERROR_ENTRY_NOT_DELETED', "Si e' verificato un errore eliminando il post");
define('_IT_BLOG_ERROR_TRACKBACK_NOT_ADDED', "Si e' verificato un errore aggiungendo il trackback");
define('_IT_BLOG_ERROR_DOES_NOT_EXISTS', "Il post non esiste");
define('_IT_BLOG_ERROR_GETTING_TRACKBACKS', "Si e' verificato un errore caricando il trackbacks");
define('_IT_BLOG_ERROR_XMLRPC_NO_GETTEMPLATE_SUPPORT', "JAWS non supporta la funzione getTemplate");
define('_IT_BLOG_ERROR_XMLRPC_NO_SETTEMPLATE_SUPPORT', "JAWS non supporta la funzione setTemplate");
define('_IT_BLOG_ERROR_CATEGORY_XML_NOT_GENERATED', "XML Feed della categoria non generato");
define('_IT_BLOG_ERROR_TAGCLOUD_CREATION_FAILED', "Si e' verificato un errore nella creazione della lista pesata (tag cloud)");
define('_IT_BLOG_ERROR_TRACKBACK_NOT_UPDATED', "Si e' verificato un errore nell'aggiornamento del trackback");
define('_IT_BLOG_ERROR_TRACKBACK_NOT_DELETED', "Si e' verificato un errore nella cancellazione del trackback");
define('_IT_BLOG_MAIL_COMMENT_TO_ME', "Inviami questo commento..");
define('_IT_BLOG_COMMENT_REPLY', "[Commento del Blog] - per il blog: {0}");
define('_IT_BLOG_COMMENT_MAIL_VISIT', "Leggi la discussione sul blog: ");
define('_IT_BLOG_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_IT_BLOG_PAGENAVIGATION_NEXTPAGE', "Prossima pagina");
define('_IT_BLOG_PAGENAVIGATION_PREVIOUSPAGE', "Pagina precedente");
define('_IT_BLOG_MANAGE_TRACKBACKS', "Trackbacks");
define('_IT_BLOG_TRACKBACK_WHERE', "Mostra quando");
define('_IT_BLOG_TRACKBACK_BLOGNAME', "Nome del blog");
define('_IT_BLOG_TRACKBACK_BLOGNAME_CONTAINS', "Nome del blog trackback contiene");
define('_IT_BLOG_TRACKBACK_EXCERPT', "Estratto");
define('_IT_BLOG_TRACKBACK_EXCERPT_CONTAINS', "Estratto del trackback contiene");
define('_IT_BLOG_VIEW_TRACKBACK', "Visualizza Trackback");
define('_IT_BLOG_TRACKBACKS_CURRENTLY_UPDATING_FOR', "Stai visualizzando un trackback per il post {0}");
define('_IT_BLOG_DELETE_MASSIVE_TRACKBACKS', "Sei sicuro di voler eliminare questo/questi trackback(s)?");
define('_IT_BLOG_PINGBACK', "Pingback");
define('_IT_BLOG_PINGBACK_DEFAULT_COMMENT', "Commento Pingback da {0}");
define('_IT_BLOG_PINGBACK_DEFAULT_TITLE', "Pingback da {0}");
define('_IT_BLOG_PINGBACK_TITLE', "{0} (da pingback)");
define('_IT_BLOG_PINGBACK_COMMENT', "Questo commento proviene da un pingback: {0}");
