<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Phoo"
 * "Last-Translator: Erwin Gjaltema <erwin@gjaltema-online.nl>"
 * "Language-Team: NL"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_NL_PHOO_NAME', "Foto Album");
define('_NL_PHOO_DESCRIPTION', "Een leuke foto album voor je site");
define('_NL_PHOO_DEFAULT_VIEW', "Standaard weergave");
define('_NL_PHOO_ALBUM_LIST', "Album lijst");
define('_NL_PHOO_PHOTOBLOG', "Fotoblog");
define('_NL_PHOO_RANDOM_IMAGE', "Willekeurige Foto");
define('_NL_PHOO_RANDOM_IMAGE_DESC', "Weergeeft een willekeurige foto van een album");
define('_NL_PHOO_MOBLOG', "Moblog");
define('_NL_PHOO_MOBLOG_DESC', "Weergeeft de Moblog album");
define('_NL_PHOO_ALBUMS', "Albums");
define('_NL_PHOO_ALBUMS_DESC', "Weergeeft alle albums lijst");
define('_NL_PHOO_UNKNOW_ALBUM', "Niet gevonden in een album");
define('_NL_PHOO_WITHOUT_ALBUM', "Geadopteerde Foto's");
define('_NL_PHOO_WITHOUT_ALBUM_DESCRIPTION', "Foto's die niet in een album horen");
define('_NL_PHOO_NEW_ALBUM', "Nieuwe album");
define('_NL_PHOO_EDIT_ALBUM', "Wijzig album");
define('_NL_PHOO_ALBUM_CREATION_DATE', "Creatie datum");
define('_NL_PHOO_EDIT_PHOTO', "Wijzig Foto");
define('_NL_PHOO_FIRST', "Eerste");
define('_NL_PHOO_PREVIOUS', "Vorige");
define('_NL_PHOO_NEXT', "Volgende");
define('_NL_PHOO_LAST', "Laatste");
define('_NL_PHOO_THUMBS', "Thumbnails");
define('_NL_PHOO_WIDTH', "Breedte");
define('_NL_PHOO_HEIGHT', "Hoogte");
define('_NL_PHOO_SIZE', "Grote");
define('_NL_PHOO_APERTURE', "Aperture");
define('_NL_PHOO_EXPOSURE_TIME', "Sluiter tijd");
define('_NL_PHOO_FOCAL_LENGTH', "Focal Lengte");
define('_NL_PHOO_UNKNOWN_CAM', "Onbekende Camera");
define('_NL_PHOO_LEAVE_COMMENT', "Laat een reactie achter");
define('_NL_PHOO_PHOTOS', "Foto's");
define('_NL_PHOO_PHOTO', "Foto {0}");
define('_NL_PHOO_PHOTO_COUNTER', "Foto {0} van {1}");
define('_NL_PHOO_PHOTOS_COUNT', "{0} Foto's");
define('_NL_PHOO_COMMENTS', "Reacties");
define('_NL_PHOO_ADDITIONAL_SETTINGS', "Extra Instellingen");
define('_NL_PHOO_IMPORT', "Importeer");
define('_NL_PHOO_NUM_PHOTOS_ALBUM', "{0} foto's in album");
define('_NL_PHOO_UPLOAD_PHOTOS', "Upload foto's");
define('_NL_PHOO_EDIT_DESCRIPTION', "Wijzig Beschrijving");
define('_NL_PHOO_DELETE_ALBUM_CONFIRM', "Weet je zeker dat je deze album wilt verwijderen?");
define('_NL_PHOO_NOT_PUBLISHED', "Niet Gepubliceerd");
define('_NL_PHOO_START_UPLOADING_PHOTOS', "Start foto's uploaden");
define('_NL_PHOO_INEXISTENT_ALBUM', "De album bestaat niet");
define('_NL_PHOO_EMPTY_ALBUMSET', "Er zijn geen albums");
define('_NL_PHOO_PHOTO_TITLE', "Foto Titel");
define('_NL_PHOO_PHOTO_DESCRIPTION', "Foto Beschrijving");
define('_NL_PHOO_ALBUM', "Album");
define('_NL_PHOO_ALLOW_COMMENTS', "Reacties Toestaan");
define('_NL_PHOO_STATUS', "Status");
define('_NL_PHOO_HIDDEN', "Verborgen");
define('_NL_PHOO_PUBLISHED', "Gepubliceerd");
define('_NL_PHOO_DELETE_PHOTO_CONFIRM', "Weet je zeker dat je deze foto wilt verwijderen?");
define('_NL_PHOO_UPLOAD_FAILURE', "Kan de foto niet uploaden");
define('_NL_PHOO_ALBUM_NAME', "Album Naam");
define('_NL_PHOO_ALBUM_DESC', "Album Beschrijving");
define('_NL_PHOO_CREATE_NEW_ALBUM', "Creëer nieuwe album");
define('_NL_PHOO_DELETE_ALBUM', "Verwijder album");
define('_NL_PHOO_KEEP_ORIGINAL', "Hou originele foto");
define('_NL_PHOO_SHOW_EXIF_INFO', "weergeef EXIF info");
define('_NL_PHOO_EXIF_INFO', "EXIF info");
define('_NL_PHOO_SAVE_CHANGES', "Veranderingen Opslaan");
define('_NL_PHOO_COMMENTS_WHERE', "Reacties waar");
define('_NL_PHOO_ID', "ID is");
define('_NL_PHOO_TITLE_CONTAINS', "titel bevat");
define('_NL_PHOO_COMMENT_CONTAINS', "reactie bevat");
define('_NL_PHOO_NAME_CONTAINS', "naam bevat");
define('_NL_PHOO_EMAIL_CONTAINS', "email bevat");
define('_NL_PHOO_URL_CONTAINS', "URL bevat");
define('_NL_PHOO_IP_CONTAINS', "IP adres bevat");
define('_NL_PHOO_FILTER', "Filter");
define('_NL_PHOO_IP_ADDRESS', "IP Adres");
define('_NL_PHOO_COMMENT', "Reactie");
define('_NL_PHOO_UPDATE_COMMENT', "Reactie Bijwerken");
define('_NL_PHOO_DELETE_COMMENT', "Reactie Verwijderen");
define('_NL_PHOO_REPLY', "Antwoord");
define('_NL_PHOO_SEND_COMMENT', "Reactie Verzenden");
define('_NL_PHOO_RECENT_COMMENTS', "Recente Reacties");
define('_NL_PHOO_RECENT_COMMENTS_DESC', "Weergeeft een opsomming van recente reacties.");
define('_NL_PHOO_SAVE_SETTINGS', "Instellingen Opslaan");
define('_NL_PHOO_RESIZE_METHOD', "Resize Methode");
define('_NL_PHOO_DEFAULT_STATUS', "Standaard Status");
define('_NL_PHOO_MOBLOG_ALBUM', "Moblog Album");
define('_NL_PHOO_MOBLOG_LIMIT', "Moblog Limiet");
define('_NL_PHOO_PHOTOBLOG_ALBUM', "Fotoblog Album");
define('_NL_PHOO_PHOTOBLOG_LIMIT', "Fotoblog Limiet");
define('_NL_PHOO_THUMBNAIL_LIMIT', "Foto's per pagina");
define('_NL_PHOO_FULL_ALBUM', "Volledige Album");
define('_NL_PHOO_READY_TO_IMPORT', "Klaar om {0} foto's te importeren");
define('_NL_PHOO_IMPORT_MESSAGE', "Importeer geselecteerde foto's naar");
define('_NL_PHOO_NO_IMAGES_TO_IMPORT', "Geen foto's te importeren");
define('_NL_PHOO_IMPORT_INSTRUCTIONS', "Copiëer foto's naar data/phoo/import, bezoek daarna deze pagina om je afbeeldingen te importeren.");
define('_NL_PHOO_IMPORTING', "Importeren");
define('_NL_PHOO_IMPORTING_WARNING', "Sluit dit venster niet onder het importeren");
define('_NL_PHOO_FINISHED', "Klaar");
define('_NL_PHOO_DELETE_MASSIVE_COMMENTS', "Weet je zeker dat je deze reactie(s) wilt verwijderen?");
define('_NL_PHOO_MODERATE_COMMENTS', "Modereer reacties");
define('_NL_PHOO_COMMENT_IS_SPAM', "Je reactie is gemarkeerd als spam.");
define('_NL_PHOO_COMMENT_IS_WAITING', "Je reactie wacht op moderatie.");
define('_NL_PHOO_ALBUMS_ORDER_TYPE', "Order type voor albums");
define('_NL_PHOO_PHOTOS_ORDER_TYPE', "Order type voor foto's");
define('_NL_PHOO_ORDER_TYPE_BY_CREATETIME', "Op creatiedatum");
define('_NL_PHOO_ORDER_TYPE_BY_NAME', "Op naam");
define('_NL_PHOO_ORDER_TYPE_BY_ID', "Op id");
define('_NL_PHOO_ADD_ANOTHER_PHOTO', "Nog een foto toevoegen");
define('_NL_PHOO_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_NL_PHOO_ALBUM_EMPTY', "Leeg album");
define('_NL_PHOO_CSS_CLASS', "CSS Classe");
define('_NL_PHOO_THUMB', "Thumb");
define('_NL_PHOO_MEDIUM', "Middel");
define('_NL_PHOO_ORIGINAL', "Origineel");
define('_NL_PHOO_INSERTIMAGE', "Afbeelding invoegen");
define('_NL_PHOO_IMAGE_LABEL', "Afbeelding");
define('_NL_PHOO_SELECT_OTHER_IMAGE', "Selecteer een andere afbeelding");
define('_NL_PHOO_INCLUDE_LINK_TO_ALBUM', "Link naar album bijvoegen");
define('_NL_PHOO_ACL_DEFAULT', "Beheer Phoo");
define('_NL_PHOO_ACL_ADDPHOTOS', "Nieuwe foto's toevoegen");
define('_NL_PHOO_ACL_DELETEPHOTOS', "Verwijder foto's");
define('_NL_PHOO_ACL_MANAGEPHOTOS', "Behaar foto's");
define('_NL_PHOO_ACL_MODIFYOTHERSPHOTOS', "Wijzig foto's beheerd door anderen");
define('_NL_PHOO_ACL_MANAGECOMMENTS', "Beheer reacties");
define('_NL_PHOO_ACL_MANAGEALBUMS', "Behaar Alums");
define('_NL_PHOO_ACL_SETTINGS', "Wijzig Instellingen");
define('_NL_PHOO_ACL_IMPORT', "Importeer foto's");
define('_NL_PHOO_ERROR_ADVANCEDSEARCH_QUERY', "Er was een probleem bij het uitvoeren van de Geavanceerde Zoek Opdracht");
define('_NL_PHOO_ALBUM_CREATED', "De album is gemaakt");
define('_NL_PHOO_ALBUMS_UPDATED', "De albums zijn bijgewerkt");
define('_NL_PHOO_ALBUM_UPDATED', "De album is bijgewerkt");
define('_NL_PHOO_ALBUM_DELETED', "De album is verwijderd");
define('_NL_PHOO_PHOTO_ADDED', "De foto is toegevoegd");
define('_NL_PHOO_PHOTO_UPDATED', "De foto is bijgewerkt");
define('_NL_PHOO_PHOTO_DELETED', "De foto is verwijderd");
define('_NL_PHOO_COMMENT_UPDATED', "De reactie is bijgewerkt");
define('_NL_PHOO_COMMENT_DELETED', "De reactie is verwijderd");
define('_NL_PHOO_SETTINGS_UPDATED', "De instellingen zijn bijgewerkt");
