<?php
// General Translation file  (i18n) for JMS gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Jms"
 * "Last-Translator: Alessio Calafiore <lex@iokoi.com>"
 * "Language-Team: IT"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_IT_COMPONENTS_NAME', "Gestione Componenti");
define('_IT_COMPONENTS_DESCRIPTION', "Gestisce tutti i componenti di Jaws.");
define('_IT_COMPONENTS_INSTALLED_COMPONENTS', "Componenti installati");
define('_IT_COMPONENTS_UNINSTALLED_COMPONENTS', "Componenti disinstallati");
define('_IT_COMPONENTS_OUTDATED_COMPONENTS', "Componenti obsoleti");
define('_IT_COMPONENTS_KEY', "Chiave");
define('_IT_COMPONENTS_VALUE', "Valore");
define('_IT_COMPONENTS_INFORMATION', "Informazioni");
define('_IT_COMPONENTS_VERSION', "Versione");
define('_IT_COMPONENTS_INSTALL', "Installa");
define('_IT_COMPONENTS_UNINSTALL', "Disinstalla");
define('_IT_COMPONENTS_PURGE', "Elimina");
define('_IT_COMPONENTS_UNINSTALLED', "Disinstallati");
define('_IT_COMPONENTS_PURGED', "Eliminati");
define('_IT_COMPONENTS_UPDATE', "Aggiorna");
define('_IT_COMPONENTS_ONLY_SHOW', "Mostra solo: ");

/* ACL */
define('_IT_COMPONENTS_ACL_MANAGEJMS', "Usa gestione componenti");
define('_IT_COMPONENTS_ACL_MANAGEGADGETS', "Abilita/Disabilita gadgets");
define('_IT_COMPONENTS_ACL_MANAGEPLUGINS', "Abilita/Disabilita plugins");

/* Plugins */
define('_IT_COMPONENTS_PLUGINS', "Plugins");
define('_IT_COMPONENTS_PLUGINS_INSTALLED_PLUGINS', "Plugin installati");
define('_IT_COMPONENTS_PLUGINS_NOTINSTALLED_PLUGINS', "Plugin non installati");

define('_IT_COMPONENTS_PLUGINS_PLUGIN', "Plugin");
define('_IT_COMPONENTS_PLUGINS_USAGE', "Utilizzo Plugin");
define('_IT_COMPONENTS_PLUGINS_NO_EXAMPLE', "Nessun esempio trovato");
define('_IT_COMPONENTS_PLUGINS_FRIENDLY', "Friendly");
define('_IT_COMPONENTS_PLUGINS_NOT_FRIENDLY', "Non friendly");
define('_IT_COMPONENTS_PLUGINS_ACCESSKEY', "Chiave di accesso");
define('_IT_COMPONENTS_PLUGINS_NO_ACCESSKEY', "Nessuna chiave di accesso trovata");
define('_IT_COMPONENTS_PLUGINS_USE_IN', "Utilizzo Plugin");
define('_IT_COMPONENTS_PLUGINS_SAVED', "Impostazioni plugin salvate.");
define('_IT_COMPONENTS_PLUGINS_NOTHING', "Nessun plugin disponibile");
define('_IT_COMPONENTS_PLUGINS_ALWAYS', "Sempre");
define('_IT_COMPONENTS_PLUGINS_ONLY_IN_GADGET', "Solo in gadget predisposti");
define('_IT_COMPONENTS_PLUGINS_ENABLED_OK', "Plugin {0} installato con successo");
define('_IT_COMPONENTS_PLUGINS_ENABLED_FAILURE', "Si e' verificato un problema installando il plugin {0}");
define('_IT_COMPONENTS_PLUGINS_NO_SELECTION', "Nessun plugin selezionato, selezionane uno");
define('_IT_COMPONENTS_SIDEBAR_DISABLE_PLUGIN', "Disabilita");
define('_IT_COMPONENTS_SIDEBAR_DISABLE_PLUGINS', "Plugin abilitati");
define('_IT_COMPONENTS_SIDEBAR_DISABLE_PLUGINS_WAITING', "Plugin in attesa di disabilitazione");
define('_IT_COMPONENTS_PLUGINS_DISABLE_FAILURE', "Impossibile disabilitare il plugin");
define('_IT_COMPONENTS_PLUGINS_DISABLE_OK', "Plugin disinstallato correttamente");
define('_IT_COMPONENTS_PLUGINS_PLUGIN_DOESNT_EXISTS', "Il plugin {0} non esiste");
define('_IT_COMPONENTS_PLUGINS_PLUGIN_CANT_HAVE_NAME_CORE', "Il plugin non puo' avere il nome Core, e' riservato per Jaws.");
define('_IT_COMPONENTS_PLUGINS_UNINSTALL_CONFIRM', "Vuoi disinstallare questo plugin?");

/* Gadgets */
define('_IT_COMPONENTS_GADGETS', "Gadgets");
define('_IT_COMPONENTS_GADGETS_INSTALLED_GADGETS', "Gadget installati");
define('_IT_COMPONENTS_GADGETS_NOTINSTALLED_GADGETS', "Gadget non installati");
define('_IT_COMPONENTS_GADGETS_NOTHING', "Nessun gadget");
define('_IT_COMPONENTS_GADGETS_REGISTRY', "Chiavi di registro");
define('_IT_COMPONENTS_GADGETS_ACL', "Regole ACL");
define('_IT_COMPONENTS_GADGETS_DOESNT_EXISTS', "Il gadget {0} non esiste");
define('_IT_COMPONENTS_GADGETS_UNINSTALL_CONFIRM', "Vuoi disinstallare il gadget? Non verranno cancellati dati");
define('_IT_COMPONENTS_GADGETS_PURGE_CONFIRM', "Vuoi eliminare il gadget? Tutti i dati relativi verranno persi");
define('_IT_COMPONENTS_GADGETS_NOT_EXISTS', "Il gadget non esiste");
define('_IT_COMPONENTS_GADGETS_NO_SELECTION', "Nessun gadget selezionato, selezonane uno");
define('_IT_COMPONENTS_GADGETS_ENABLED_OK', "Gadget {0} installato con successo");
define('_IT_COMPONENTS_GADGETS_ENABLED_FAILURE', "Si e' verificato un problema abilitando il gadget {0} ");
define('_IT_COMPONENTS_GADGETS_DISABLE_OK', "il gadget {0} e' stato disinstallato con successo");
define('_IT_COMPONENTS_GADGETS_DISABLE_FAILURE', "Si e' verificato un problema disinstallando il gadget {0}");
define('_IT_COMPONENTS_GADGETS_UPDATED_OK', "Il gadget {0} e' stato aggiornato con successo");
define('_IT_COMPONENTS_GADGETS_UPDATED_FAILURE', "Si e' verificato un problema aggiornando il gadget {0}");
define('_IT_COMPONENTS_GADGETS_UPDATED_NO_NEED', "Non e' necessario aggiornare il gadget {0}");
define('_IT_COMPONENTS_GADGETS_REQUIRES_X_GADGET', "{0} necessita che siano installati i seguenti gadget per funzionare: {1}");
define('_IT_COMPONENTS_GADGETS_REQUIRES_X_DEPENDENCY', "{0} non puo' essere {2} perche' {1} gadget(s) ne dipende");

/* Sidebar */
define('_IT_COMPONENTS_SIDEBAR_ENABLE', "Abilita");
define('_IT_COMPONENTS_SIDEBAR_DISABLE', "Disabilita");

/* Gadgets Sidebar */
define('_IT_COMPONENTS_SIDEBAR_DISABLED_GADGETS', "Gadget disabilitati");
define('_IT_COMPONENTS_SIDEBAR_GADGETS_WAITING', "Gadget in attesa di abilitazione:");
define('_IT_COMPONENTS_SIDEBAR_ENABLED_GADGETS', "Gadget abilitati");
define('_IT_COMPONENTS_SIDEBAR_DISABLE_GADGETS_WAITING', "Gadget che puoi disabilitare:");

/* Gadget disabling errors */
define('_IT_COMPONENTS_SIDEBAR_DISABLE_MAIN_FAILURE', "Impossibile disabilitare il gadget principale");

/* Not updated gadgets sidebar */
define('_IT_COMPONENTS_SIDEBAR_NOTUPDATED_GADGETS', "Gadget Obsoleti");
define('_IT_COMPONENTS_SIDEBAR_NOTUPDATED_SUGESTION', "Gadget che puoi aggiornare adesso:");

/* Plugins Sidebar */
define('_IT_COMPONENTS_SIDEBAR_DISABLED_PLUGINS', "Plugin Disabilitati");
define('_IT_COMPONENTS_SIDEBAR_PLUGINS_WAITING', "Plugin in attesa di abilitazione:");
