<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Phoo"
 * "Last-Translator: Igor Feghali <ifeghali@php.net>"
 * "Language-Team: PT-BR"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_PT-BR_PHOO_NAME', "Organizador de Fotos");
define('_PT-BR_PHOO_DESCRIPTION', "Um organizador legal de fotos para o seu site");
define('_PT-BR_PHOO_DEFAULT_VIEW', "Visão padrão");
define('_PT-BR_PHOO_ALBUM_LIST', "Listagem de álbuns");
define('_PT-BR_PHOO_PHOTOBLOG', "Fotolog");
define('_PT-BR_PHOO_RANDOM_IMAGE', "Imagem aleatória");
define('_PT-BR_PHOO_RANDOM_IMAGE_DESC', "Mostra uma imagem aleatória de qualquer álbum");
define('_PT-BR_PHOO_MOBLOG', "Moblog");
define('_PT-BR_PHOO_MOBLOG_DESC', "Exibe o álbum do moblog");
define('_PT-BR_PHOO_ALBUMS', "Álbuns");
define('_PT-BR_PHOO_ALBUMS_DESC', "Exibe a listagem de álbuns");
define('_PT-BR_PHOO_UNKNOW_ALBUM', "Álbum não encontrado");
define('_PT-BR_PHOO_WITHOUT_ALBUM', "Fotos Órfãs");
define('_PT-BR_PHOO_WITHOUT_ALBUM_DESCRIPTION', "Fotos que não pertencem à nenhum álbum");
define('_PT-BR_PHOO_NEW_ALBUM', "Novo álbum");
define('_PT-BR_PHOO_EDIT_ALBUM', "Editar álbum");
define('_PT-BR_PHOO_ALBUM_CREATION_DATE', "Data de criação");
define('_PT-BR_PHOO_EDIT_PHOTO', "Editar foto");
define('_PT-BR_PHOO_FIRST', "Primeira");
define('_PT-BR_PHOO_PREVIOUS', "Anterior");
define('_PT-BR_PHOO_NEXT', "Próxima");
define('_PT-BR_PHOO_LAST', "Última");
define('_PT-BR_PHOO_THUMBS', "Miniaturas");
define('_PT-BR_PHOO_WIDTH', "Largura");
define('_PT-BR_PHOO_HEIGHT', "Altura");
define('_PT-BR_PHOO_SIZE', "Tamanho");
define('_PT-BR_PHOO_APERTURE', "Abertura");
define('_PT-BR_PHOO_EXPOSURE_TIME', "Exposição");
define('_PT-BR_PHOO_FOCAL_LENGTH', "Foco");
define('_PT-BR_PHOO_UNKNOWN_CAM', "Câmera desconhecida");
define('_PT-BR_PHOO_LEAVE_COMMENT', "Comentar");
define('_PT-BR_PHOO_PHOTOS', "Fotos");
define('_PT-BR_PHOO_PHOTO', "Foto {0}");
define('_PT-BR_PHOO_PHOTO_COUNTER', "Foto {0} de {1}");
define('_PT-BR_PHOO_PHOTOS_COUNT', "{0} fotos");
define('_PT-BR_PHOO_COMMENTS', "Comentários");
define('_PT-BR_PHOO_ADDITIONAL_SETTINGS', "Configurações Adicionais");
define('_PT-BR_PHOO_IMPORT', "Importar");
define('_PT-BR_PHOO_NUM_PHOTOS_ALBUM', "{0} imagens no álbum");
define('_PT-BR_PHOO_UPLOAD_PHOTOS', "Enviar fotos");
define('_PT-BR_PHOO_EDIT_DESCRIPTION', "Editar descrição");
define('_PT-BR_PHOO_DELETE_ALBUM_CONFIRM', "Você tem certeza que deseja excluir este álbum?");
define('_PT-BR_PHOO_NOT_PUBLISHED', "Não publicado");
define('_PT-BR_PHOO_START_UPLOADING_PHOTOS', "Enviar fotos");
define('_PT-BR_PHOO_INEXISTENT_ALBUM', "O álbum não existe");
define('_PT-BR_PHOO_EMPTY_ALBUMSET', "Nenhum álbum encontrado");
define('_PT-BR_PHOO_PHOTO_TITLE', "Título da Foto");
define('_PT-BR_PHOO_PHOTO_DESCRIPTION', "Descrição da foto");
define('_PT-BR_PHOO_POSTED_BY', "Enviado por");
define('_PT-BR_PHOO_ALBUM', "Álbum");
define('_PT-BR_PHOO_ALLOW_COMMENTS', "Permitir comentários");
define('_PT-BR_PHOO_STATUS', "Estado");
define('_PT-BR_PHOO_HIDDEN', "Oculto");
define('_PT-BR_PHOO_PUBLISHED', "Publicado");
define('_PT-BR_PHOO_DELETE_PHOTO_CONFIRM', "Você tem certeza que deseja excluir esta foto?");
define('_PT-BR_PHOO_UPLOAD_FAILURE', "Houve um erro ao enviar a foto");
define('_PT-BR_PHOO_ALBUM_NAME', "Nome do álbum");
define('_PT-BR_PHOO_ALBUM_DESC', "Descrição do álbum");
define('_PT-BR_PHOO_CREATE_NEW_ALBUM', "Novo");
define('_PT-BR_PHOO_DELETE_ALBUM', "Excluir álbum");
define('_PT-BR_PHOO_KEEP_ORIGINAL', "Manter imagem original");
define('_PT-BR_PHOO_SHOW_EXIF_INFO', "Mostrar EXIF");
define('_PT-BR_PHOO_EXIF_INFO', "Informação EXIF");
define('_PT-BR_PHOO_SAVE_CHANGES', "Salvar modificações");
define('_PT-BR_PHOO_COMMENTS_WHERE', "Comentar onde");
define('_PT-BR_PHOO_ID', "Qual é o ID?");
define('_PT-BR_PHOO_TITLE_CONTAINS', "título contém");
define('_PT-BR_PHOO_COMMENT_CONTAINS', "comentários contém");
define('_PT-BR_PHOO_NAME_CONTAINS', "nome contém");
define('_PT-BR_PHOO_EMAIL_CONTAINS', "email contém");
define('_PT-BR_PHOO_URL_CONTAINS', "URL contém");
define('_PT-BR_PHOO_IP_CONTAINS', "Endereço IP contém");
define('_PT-BR_PHOO_FILTER', "Filtro");
define('_PT-BR_PHOO_IP_ADDRESS', "Endereço IP");
define('_PT-BR_PHOO_COMMENT', "Comentário");
define('_PT-BR_PHOO_UPDATE_COMMENT', "Atualizar comentário");
define('_PT-BR_PHOO_DELETE_COMMENT', "Excluir comentário");
define('_PT-BR_PHOO_REPLY', "Responder");
define('_PT-BR_PHOO_SEND_COMMENT', "Enviar comentários");
define('_PT-BR_PHOO_RECENT_COMMENTS', "Comentários recentes");
define('_PT-BR_PHOO_RECENT_COMMENTS_DESC', "Exibe um sumário dos comentários mais recentes");
define('_PT-BR_PHOO_SAVE_SETTINGS', "Salvar configurações");
define('_PT-BR_PHOO_RESIZE_METHOD', "Redimensionar método");
define('_PT-BR_PHOO_DEFAULT_STATUS', "Estado padrão");
define('_PT-BR_PHOO_MOBLOG_ALBUM', "Álbum do moblog");
define('_PT-BR_PHOO_MOBLOG_LIMIT', "Limite do moblog");
define('_PT-BR_PHOO_PHOTOBLOG_ALBUM', "Álbum do fotolog");
define('_PT-BR_PHOO_PHOTOBLOG_LIMIT', "Limite do fotolog");
define('_PT-BR_PHOO_THUMBNAIL_LIMIT', "Imagens por página");
define('_PT-BR_PHOO_FULL_ALBUM', "Álbum completo");
define('_PT-BR_PHOO_READY_TO_IMPORT', "Pronto para importar {0} imagens");
define('_PT-BR_PHOO_IMPORT_MESSAGE', "Importar imagens selecionadas para");
define('_PT-BR_PHOO_NO_IMAGES_TO_IMPORT', "Não há imagens para importar");
define('_PT-BR_PHOO_IMPORT_INSTRUCTIONS', "Copie as imagens para data/phoo/import, então volte aqui novamente");
define('_PT-BR_PHOO_IMPORTING', "Importando");
define('_PT-BR_PHOO_IMPORTING_WARNING', "Não feche esta janela enquanto estiver importando");
define('_PT-BR_PHOO_FINISHED', "Finalizado");
define('_PT-BR_PHOO_DELETE_MASSIVE_COMMENTS', "Você tem certeza que deseja excluir este(s) comentário(s)?");
define('_PT-BR_PHOO_MODERATE_COMMENTS', "Moderar comentários");
define('_PT-BR_PHOO_COMMENT_IS_SPAM', "Seu comentário foi marcado como SPAM");
define('_PT-BR_PHOO_COMMENT_IS_WAITING', "Seu comentário está aguardando moderação");
define('_PT-BR_PHOO_ALBUMS_ORDER_TYPE', "Ordenar álbuns");
define('_PT-BR_PHOO_PHOTOS_ORDER_TYPE', "Ordenar fotos");
define('_PT-BR_PHOO_ORDER_TYPE_BY_CREATETIME', "por data");
define('_PT-BR_PHOO_ORDER_TYPE_BY_NAME', "por nome");
define('_PT-BR_PHOO_ORDER_TYPE_BY_ID', "por ID");
define('_PT-BR_PHOO_ADD_ANOTHER_PHOTO', "Adicionar nova foto");
define('_PT-BR_PHOO_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_PT-BR_PHOO_ALBUM_EMPTY', "Álbum Vazio");
define('_PT-BR_PHOO_CSS_CLASS', "Classe CSS");
define('_PT-BR_PHOO_THUMB', "Miniatura");
define('_PT-BR_PHOO_MEDIUM', "Médio");
define('_PT-BR_PHOO_ORIGINAL', "Original");
define('_PT-BR_PHOO_INSERTIMAGE', "Inserir Imagem");
define('_PT-BR_PHOO_IMAGE_LABEL', "Imagem");
define('_PT-BR_PHOO_SELECT_OTHER_IMAGE', "Selecione uma imagem diferente");
define('_PT-BR_PHOO_INCLUDE_LINK_TO_ALBUM', "Incluir link para o álbum");
define('_PT-BR_PHOO_ACL_DEFAULT', "Administrar Organizador de Fotos");
define('_PT-BR_PHOO_ACL_ADDPHOTOS', "Adicionar novas fotos");
define('_PT-BR_PHOO_ACL_DELETEPHOTOS', "Excluir fotos");
define('_PT-BR_PHOO_ACL_MANAGEPHOTOS', "Gerenciar fotos");
define('_PT-BR_PHOO_ACL_MODIFYOTHERSPHOTOS', "Atualizar fotos de terceiros");
define('_PT-BR_PHOO_ACL_MANAGECOMMENTS', "Gerenciar comentários");
define('_PT-BR_PHOO_ACL_MANAGEALBUMS', "Gerenciar álbuns");
define('_PT-BR_PHOO_ACL_SETTINGS', "Atualizar configurações");
define('_PT-BR_PHOO_ACL_IMPORT', "Importar fotos");
define('_PT-BR_PHOO_ERROR_ADVANCEDSEARCH_QUERY', "Houve um erro ao executar a consulta da busca avançada");
define('_PT-BR_PHOO_ERROR_GETMOBLOG', "Houve um erro ao executar a consulta moblog");
define('_PT-BR_PHOO_ERROR_ALBUMLIST', "Houve um erro ao obter a listagem de álbuns");
define('_PT-BR_PHOO_ERROR_RANDOMIMAGE', "Houve um erro ao escolher uma imagem aleatória");
define('_PT-BR_PHOO_ERROR_ALBUMINFO', "Houve um erro ao obter as informações do álbum");
define('_PT-BR_PHOO_ERROR_ALBUMS', "Houve um erro ao obter os álbuns de {0}");
define('_PT-BR_PHOO_ERROR_GETALBUM', "Houve um erro ao obter os álbuns");
define('_PT-BR_PHOO_ERROR_GETIMAGE', "Houve um erro ao obter a imagem");
define('_PT-BR_PHOO_ERROR_GETIMAGEENTRY', "Houve um erro ao obter a entrada da imagem");
define('_PT-BR_PHOO_ERROR_CANT_UPLOAD_PHOTO_EXT', "Arquivo não é válido. Formatos aceitos (gif|jpeg|png)");
define('_PT-BR_PHOO_ERROR_CANT_UPDATE_PHOTO', "Não foi possível atualizar a foto");
define('_PT-BR_PHOO_ERROR_CANT_UPLOAD_PHOTO', "Não foi possível enviar a foto");
define('_PT-BR_PHOO_ERROR_CANT_DELETE_PHOTO', "Não foi possível excluir a foto");
define('_PT-BR_PHOO_ERROR_CANT_ADD_ENTRY_TO_ALBUM', "Houve um erro ao adicionar a entrada ao álbum");
define('_PT-BR_PHOO_ERROR_GETASPORTRAIT', "Houve um erro ao obter o álgum como retrato");
define('_PT-BR_PHOO_ERROR_ALBUM_NOT_UPDATED', "Houve um erro ao atualizar o álbum");
define('_PT-BR_PHOO_ERROR_ALBUM_NOT_DELETED', "Houve um erro ao excluir o álbum");
define('_PT-BR_PHOO_ERROR_ALBUM_NOT_CREATED', "Houve um erro ao criar o álbum");
define('_PT-BR_PHOO_ERROR_GETCOMMENTS', "Houve um erro ao obter os comentários");
define('_PT-BR_PHOO_ERROR_RECENTCOMMENTS', "Houve um erro ao obter os comentários mais recentes");
define('_PT-BR_PHOO_ERROR_FILETEREDCOMMENTS', "Houve um erro ao filtrar os comentário");
define('_PT-BR_PHOO_ERROR_GETCOMMENT', "Houve um erro ao obter o comentário");
define('_PT-BR_PHOO_ERROR_CANT_ADD_COMMENT', "Houve um erro ao adicionar o comentário");
define('_PT-BR_PHOO_ERROR_CANT_UPDATE_COMMENT', "Não foi possível atualizar o comentário");
define('_PT-BR_PHOO_ERROR_CANT_DELETE_COMMENT', "Não foi possível excluir o comentário");
define('_PT-BR_PHOO_ERROR_CANT_UPDATE_SETTINGS', "Não foi possível atualizar as configurações");
define('_PT-BR_PHOO_ERROR_CANT_DELETE_IMAGE', "Não foi possível excluir a imagem");
define('_PT-BR_PHOO_ERROR_CANT_FETCH_SETTINGS', "Não foi possível obter as informações");
define('_PT-BR_PHOO_ALBUM_CREATED', "O álbum foi criado");
define('_PT-BR_PHOO_ALBUMS_UPDATED', "Os álbuns foram atualizados");
define('_PT-BR_PHOO_ALBUM_UPDATED', "O álbum foi atualizado");
define('_PT-BR_PHOO_ALBUM_DELETED', "O álbum foi excluído");
define('_PT-BR_PHOO_PHOTO_ADDED', "A foto foi adicionada");
define('_PT-BR_PHOO_PHOTO_UPDATED', "A foto foi atualizada");
define('_PT-BR_PHOO_PHOTO_DELETED', "A foto foi excluída");
define('_PT-BR_PHOO_COMMENT_UPDATED', "O comentário foi atualizado");
define('_PT-BR_PHOO_COMMENT_DELETED', "O comentário foi excluído");
define('_PT-BR_PHOO_SETTINGS_UPDATED', "As configurações foram atualizadas");
