<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Users"
 * "Last-Translator: Igor Feghali <ifeghali@php.net>"
 * "Language-Team: PT-BR"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_PT-BR_USERS_NAME', "Usuários");
define('_PT-BR_USERS_DESCRIPTION', "Administração de usuários");
define('_PT-BR_USERS_ACL_DEFAULT', "Administrar Usuários");
define('_PT-BR_USERS_ACL_MANAGEUSERS', "Gerenciar usuários");
define('_PT-BR_USERS_ACL_MANAGEGROUPS', "Gerenciar grupos");
define('_PT-BR_USERS_ACL_MANAGEPROPERTIES', "Gerenciamento de propriedades");
define('_PT-BR_USERS_ACL_MANAGEUSERACLS', "Gerenciamento de ACL de usuários");
define('_PT-BR_USERS_ACL_MANAGEGROUPACLS', "Gerenciamento de ACL de grupos");
define('_PT-BR_USERS_LAYOUT_LOGINBOX', "Caixa de login");
define('_PT-BR_USERS_LAYOUT_LOGINBOX_DESC', "Exibe a caixa de login");
define('_PT-BR_USERS_GROUPS_GROUPNAME', "Nome do grupo");
define('_PT-BR_USERS_GROUPS_GROUPID', "ID do Grupo");
define('_PT-BR_USERS_GROUPS_GROUP', "Grupo");
define('_PT-BR_USERS_GROUPS_GROUPS', "Grupo");
define('_PT-BR_USERS_GROUPS_ALL_GROUPS', "Todos os Grupos");
define('_PT-BR_USERS_GROUPS_ADD', "Adicionar grupo");
define('_PT-BR_USERS_GROUPS_NOGROUP', "Sem Grupo");
define('_PT-BR_USERS_GROUPS_NO_SELECTION', "Por favor escolha um grupo à sua esquerda");
define('_PT-BR_USERS_GROUPS_GROUP_INFO', "Informação do grupo");
define('_PT-BR_USERS_GROUPS_ALREADY_EXISTS', "Já existe um outro grupo com o mesmo nome ({0}).");
define('_PT-BR_USERS_GROUPS_INCOMPLETE_FIELDS', "Por favor preencha o nome do grupo");
define('_PT-BR_USERS_GROUPS_UPDATE', "Atualizar grupo");
define('_PT-BR_USERS_GROUPS_EDIT', "Editar grupo");
define('_PT-BR_USERS_GROUPS_DELETE', "Excluir grupo");
define('_PT-BR_USERS_GROUPS_PERMISSIONS', "Permissões do grupo");
define('_PT-BR_USERS_GROUPS_ACL_UPDATED', "Os privilégios do grupo foram atualizados");
define('_PT-BR_USERS_GROUPS_GROUP_NOT_EXIST', "Grupo não encontrado");
define('_PT-BR_USERS_GROUPS_MEMBERS', "Adicionar usuários");
define('_PT-BR_USERS_GROUPS_ADD_USER', "Adicionar usuário ao grupo");
define('_PT-BR_USERS_GROUPS_CONFIRM_DELETE', "Você tem certeza que deseja excluir este grupo?");
define('_PT-BR_USERS_GROUPS_CURRENTLY_EDITING_GROUP', "Você está atualizando o grupo {0}");
define('_PT-BR_USERS_GROUPS_MARK_USERS', "Selecione os usuário que você quer adicionar ao grupo");
define('_PT-BR_USERS_GROUPS_ACL_RESETED', "Os privilégios do grupo foram reiniciados");
define('_PT-BR_USERS_GROUPS_CREATED', "O grupo {0} foi criado");
define('_PT-BR_USERS_GROUPS_UPDATED', "As informações do grupo {0} foram atualizadas");
define('_PT-BR_USERS_GROUPS_DELETED', "O grupo {0} foi excluído");
define('_PT-BR_USERS_GROUPS_UPDATED_USERS', "O relacionamento entre usuários e grupos foi atualizado");
define('_PT-BR_USERS_GROUPS_NOT_CREATED', "Houve um erro ao criar o grupo {0}");
define('_PT-BR_USERS_GROUPS_NOT_UPDATED', "Houve um erro ao atualizar o grupo {0}");
define('_PT-BR_USERS_GROUPS_CANT_DELETE', "Houve um erro ao excluir o grupo {0}");
define('_PT-BR_USERS_ACCOUNT_INFO', "Informações da Conta");
define('_PT-BR_USERS_PERSONAL_INFO', "Informações Pessoais");
define('_PT-BR_USERS_USERS_ADD', "Adicionar usuário");
define('_PT-BR_USERS_ACCOUNT_EDIT', "Editar usuário");
define('_PT-BR_USERS_ACCOUNT_DELETE', "Excluir usuário");
define('_PT-BR_USERS_ACLRULES', "Regras ACL");
define('_PT-BR_USERS_USERS_USERNAME', "Nome do usuário");
define('_PT-BR_USERS_USERS_PASSWORD', "Senha");
define('_PT-BR_USERS_USERS_NICKNAME', "Nome real");
define('_PT-BR_USERS_USERS_FIRSTNAME', "Nome");
define('_PT-BR_USERS_USERS_LASTNAME', "Sobrenome");
define('_PT-BR_USERS_USERS_USERID', "ID do usuário");
define('_PT-BR_USERS_USERS_TYPE', "Tipo");
define('_PT-BR_USERS_USERS_TYPE_SUPERADMIN', "Super administrador");
define('_PT-BR_USERS_USERS_TYPE_ADMIN', "Administrador");
define('_PT-BR_USERS_USERS_TYPE_NORMAL', "Usuário comum");
define('_PT-BR_USERS_USERS_GENDER', "Gênero");
define('_PT-BR_USERS_USERS_GENDER_1', "Masculino");
define('_PT-BR_USERS_USERS_GENDER_2', "Feminino");
define('_PT-BR_USERS_USERS_BIRTHDAY', "Aniversário");
define('_PT-BR_USERS_USERS_BIRTHDAY_SAMPLE', "ex. 2009/08/31");
define('_PT-BR_USERS_USERS_SHOW_ALL', "Mostrar tudo");
define('_PT-BR_USERS_FIND_USER', "Buscar usuário");
define('_PT-BR_USERS_USERS_SEND_AUTO_PASSWORD', "Deixe vazio para enviar uma senha aleatória para o seu email");
define('_PT-BR_USERS_USERS_PASSWORD_VERIFY', "Repita a senha");
define('_PT-BR_USERS_USERS_NO_SELECTION', "Por favor escolha um usuário");
define('_PT-BR_USERS_USERS_PASSWORDS_DONT_MATCH', "Senhas não coincidem");
define('_PT-BR_USERS_USERS_INCOMPLETE_FIELDS', "Alguns campos não foram (corretamente) preenchidos");
define('_PT-BR_USERS_USERS_ALREADY_EXISTS', "Já existe um outro usuário com o mesmo nome ({0}).");
define('_PT-BR_USERS_EMAIL_ALREADY_EXISTS', "Já existe outro usuário com o mesmo email ({0}).");
define('_PT-BR_USERS_USERS_CONFIRM_NO_CHANGES', "Você tem certeza que não deseja salvar os dados?");
define('_PT-BR_USERS_USERS_SELECT_A_USER', "Selecione um usuário à esquerda");
define('_PT-BR_USERS_USER_NOT_EXIST', "Usuário não encontrado");
define('_PT-BR_USERS_USERS_EDIT', "Editar usuário");
define('_PT-BR_USERS_USERS_ACCOUNT_INFO', "Informação da conta");
define('_PT-BR_USERS_USERS_ACCOUNT_PREF', "Preferências da Conta");
define('_PT-BR_USERS_USERS_ACCOUNT_UPDATE', "Atualizar conta");
define('_PT-BR_USERS_USERS_PERMISSIONS', "Permissões");
define('_PT-BR_USERS_USER_CONFIRM_DELETE', "Excluir este usuário e todas as informações que ele enviou?");
define('_PT-BR_USERS_USER_MEMBER_OF_GROUPS', "{0} é membro dos grupos abaixo");
define('_PT-BR_USERS_USER_MEMBER_OF_NO_GROUPS', "Atualmente {0} não é membro de nenhum grupo");
define('_PT-BR_USERS_THIS_USER', "Este usuário");
define('_PT-BR_USERS_USER_CANT_AUTO_TURN_OFF_CP', "Não é permitido que você retire todos os seus privilégios");
define('_PT-BR_USERS_GROUPS', "Grupos de usuários");
define('_PT-BR_USERS_USER_CURRENTLY_EDITING', "Você está editando o usuário {0}");
define('_PT-BR_USERS_LOGIN_TITLE', "Login");
define('_PT-BR_USERS_NOCHANGE_PASSWORD', "Deixe vazio se você não quer mudar");
define('_PT-BR_USERS_RESET_ACL', "Reiniciar ACL");
define('_PT-BR_USERS_RESET_ACL_CONFIRM', "Você tem certeza que deseja reiniciar (excluir) as permissões?");
define('_PT-BR_USERS_PERSONAL', "Informações Pessoais");
define('_PT-BR_USERS_PREFERENCES', "Opções do usuário");
define('_PT-BR_USERS_ADVANCED_OPTS_EDITOR', "Editor de usuário");
define('_PT-BR_USERS_ADVANCED_OPTS_LANGUAGE', "Idioma preferencial");
define('_PT-BR_USERS_ADVANCED_OPTS_THEME', "Tema preferido");
define('_PT-BR_USERS_ADVANCED_OPTS_NOT_YET', "Nenhum valor definido");
define('_PT-BR_USERS_MYACCOUNT_UPDATED', "Os detalhes da sua conta foram atualizados");
define('_PT-BR_USERS_MYACCOUNT_PASSWORDS_DONT_MATCH', "Senhas não conferem");
define('_PT-BR_USERS_MYACCOUNT_INCOMPLETE_FIELDS', "Por favor preencha todos os campos");
define('_PT-BR_USERS_MYACCOUNT', "Minha conta");
define('_PT-BR_USERS_EDIT_PERSONAL', "Editar Perfil");
define('_PT-BR_USERS_EDIT_PREFERENCES', "Editar Preferências");
define('_PT-BR_USERS_PREFERENCES_UPDATED', "Preferências atualizadas com sucesso.");
define('_PT-BR_USERS_CONTROLPANEL', "Painel de Controle");
define('_PT-BR_USERS_USERS_CREATED', "Usuário {0} foi criado");
define('_PT-BR_USERS_USERS_UPDATED', "O usuário {0} foi atualizado");
define('_PT-BR_USERS_USERS_ACL_UPDATED', "Os privilégios do usário foram atualizados");
define('_PT-BR_USERS_USER_DELETED', "O usuário {0} foi excluído");
define('_PT-BR_USERS_USERS_ACL_RESETED', "Os privilégios do usuário foram reiniciados");
define('_PT-BR_USERS_USERS_PERSONALINFO_UPDATED', "Informações pessoais atualizadas com sucesso.");
define('_PT-BR_USERS_USERS_ADVANCED_UPDATED', "As opções avançadas do usuário foram atualizadas");
define('_PT-BR_USERS_USERS_NOT_CREATED', "Houve um erro ao criar o usuário {0}");
define('_PT-BR_USERS_USERS_NOT_UPDATED', "Houve um erro ao atualizar o usuário {0}");
define('_PT-BR_USERS_USERS_CANT_DELETE', "Houve um erro ao excluir o usuário {0}");
define('_PT-BR_USERS_USERS_CANT_DELETE_SELF', "Não é permitido excluir o seu próprio usuário");
define('_PT-BR_USERS_USERS_PERSONALINFO_NOT_UPDATED', "Houve um erro ao atualizar as informações pessoais.");
define('_PT-BR_USERS_USERS_NOT_ADVANCED_UPDATED', "Houve um erro ao atualizar as opções avançadas do usuário");
define('_PT-BR_USERS_PROPERTIES_ANON_REGISTER', "Usuários anônimos podem se registrar");
define('_PT-BR_USERS_PROPERTIES_ANON_REPETITIVE_EMAIL', "Anônimo pode se registrar com email repetido");
define('_PT-BR_USERS_PROPERTIES_ANON_ACTIVATION', "Tipo de ativação");
define('_PT-BR_USERS_PROPERTIES_ACTIVATION_AUTO', "Auto");
define('_PT-BR_USERS_PROPERTIES_ACTIVATION_BY_USER', "Pelo usuário");
define('_PT-BR_USERS_PROPERTIES_ACTIVATION_BY_ADMIN', "Pelo administrador");
define('_PT-BR_USERS_PROPERTIES_ANON_GROUP', "Grupo padrão para novos usuários");
define('_PT-BR_USERS_PROPERTIES_PASS_RECOVERY', "Usuários podem recuperar suas senhas");
define('_PT-BR_USERS_PROPERTIES_UPDATED', "As propriedades foram atualizadas");
define('_PT-BR_USERS_PROPERTIES_CANT_UPDATE', "Houve um erro ao atualizar as propriedades");
define('_PT-BR_USERS_NO_PERMISSION_TITLE', "Nenhuma permissão");
define('_PT-BR_USERS_NO_PERMISSION_DESC', "Me desculpe mas você não tem permissão para executar esta ação ({0}::{1}).");
define('_PT-BR_USERS_NO_PERMISSION_ANON_DESC', "Você não está autenticado. Por favor <a href=\"{0}\">entre</a> no sistema com um usuário válido.");
define('_PT-BR_USERS_REGISTER', "Criar conta");
define('_PT-BR_USERS_REGISTER_NOT_ENABLED', "Desculpe mas o registro está desabilitado. Por favor solicite uma conta ao administrador");
define('_PT-BR_USERS_REGISTER_ALREADY_LOGGED', "Você já está autenticando, clique <a href=\"{0}\">aqui</a> para sair do sistema");
define('_PT-BR_USERS_REGISTER_VALID_USERNAMES', "Underscore, pontuação, travessão e símbolos (@) não são aceitos...");
define('_PT-BR_USERS_REGISTER_EMAIL_NOT_VALID', "O formato do email não é válido");
define('_PT-BR_USERS_REGISTER_SUBJECT', "Registro do usuário - {0}");
define('_PT-BR_USERS_REGISTER_HELLO', "Olá {0}");
define('_PT-BR_USERS_REGISTER_ADMIN_MAIL_MSG', "Uma nova conta foi criada");
define('_PT-BR_USERS_REGISTER_MAIL_MSG', "Recebemos uma solicitação de criação de conta com seu endereço de email. Se não foi você que fez tal solicitação, por favor nos informe do erro.");
define('_PT-BR_USERS_REGISTER_ACTIVATION_MAIL_MSG', "Sua conta foi criada com sucesso. Para continuar você precisa ativá-la.");
define('_PT-BR_USERS_REGISTER_ACTIVATION_SENDMAIL_FAILED', "Houve um erro ao enviar a ativação para {0}. Por motivos de segurança removemos a sua conta do banco de dados.");
define('_PT-BR_USERS_REGISTER_RANDOM_MAIL_MSG', "Recebemos uma solicitação para cadastrar um conta com seu email e gerar e uma senha aleatória segura. Se não foi você quem solicitou esta conta, por favor responda esta mensagem nos informando o ocorrido.");
define('_PT-BR_USERS_REGISTER_BY_USER_RANDOM_MAIL_MSG', "Recebemos uma solicitação de criação de conta com seu endereço de email.\nVocê optou por receber uma senha aleatória, que segue abaixo.\nVocê precisa ativar sua conta antes de prosseguir.");
define('_PT-BR_USERS_REGISTER_RANDOM_SENDMAIL_FAILED', "Houve um erro ao enviar a senha para {1}, logo, por motivos de segurança nós excluímos seu usário do banco de dados");
define('_PT-BR_USERS_REGISTER_REGISTERED', "A conta foi criada");
define('_PT-BR_USERS_REGISTER_REGISTERED_MSG', "A conta foi criada. Você pode <a href=\"{0}\">entrar</a> quando desejar. Se você solicitou uma senha aleatória ela foi encaminhada para seu email");
define('_PT-BR_USERS_ACTIVATE_ACTIVATION_LINK', "Link de ativação");
define('_PT-BR_USERS_ACTIVATE_ACTIVATION_BY_ADMIN_MSG', "Sua conta foi criada. Entretanto, ela será submetida a um processo de verificação manual por um administrador. Você receberá um e-mail quando isto ocorrer.");
define('_PT-BR_USERS_ACTIVATE_ACTIVATION_BY_USER_MSG', "Sua conta foi criada. Um e-mail foi enviado para você com as instruções de como ativá-la.");
define('_PT-BR_USERS_ACTIVATE_ACTIVATED_BY_USER_MSG', "Sua conta foi ativada, você pode se <a href=\"{0}\">autenticar</a> quando quiser.");
define('_PT-BR_USERS_ACTIVATE_ACTIVATED_BY_ADMIN_MSG', "A conta foi ativada.");
define('_PT-BR_USERS_ACTIVATE_ACTIVATED_MAIL_MSG', "Sua conta foi ativada, você pode se autenticar quando quiser.");
define('_PT-BR_USERS_ACTIVATE_NOT_ACTIVATED_SENDMAIL', "Houve um erro ao enviar o link de ativação para {0}. Por questões de segurança seu usuário foi removido do banco de dados.");
define('_PT-BR_USERS_ACTIVATION_KEY_NOT_VALID', "Desculpe, a chave de ativação não é válida");
define('_PT-BR_USERS_ACTIVATION_ERROR_ACTIVATION', "Houve um erro ao ativar a conta");
define('_PT-BR_USERS_FORGOT_LOGIN', "Esqueceu sua senha?");
define('_PT-BR_USERS_FORGOT_REMEMBER', "Lembrar senha");
define('_PT-BR_USERS_FORGOT_MAIL_SENT', "Um email foi enviado com informações para trocar a sua senha");
define('_PT-BR_USERS_FORGOT_ERROR_SENDING_MAIL', "Houve um erro ao enviar o email com as informações de recuperação de senha");
define('_PT-BR_USERS_FORGOT_MAIL_MESSAGE', "Foi solicitado a recuperação da sua senha. Para mudar a sua senha abra o link a seguir. Caso não deseje fazê-lo simplesmente ignore esta mensagem e sua senha continuará a mesma");
define('_PT-BR_USERS_FORGOT_KEY_NOT_VALID', "A chave não é válida");
define('_PT-BR_USERS_FORGOT_PASSWORD_CHANGED', "A nova senha foi gerada automáticamente e enviada para o seu email");
define('_PT-BR_USERS_FORGOT_PASSWORD_CHANGED_SUBJECT', "Nova senha");
define('_PT-BR_USERS_FORGOT_PASSWORD_CHANGED_MESSAGE', "Uma nova senha foi atribuída a sua conta, você pode encontrá-la abaixo. Para trocá-la entre no sistema com seu usuário ({0}) e esta senha, então você poderá atualizar seu perfil");
define('_PT-BR_USERS_FORGOT_ERROR_CHANGING_PASSWORD', "Houve um erro ao mudar a sua senha");
