<?php
// General Translation file (i18n) for Skeleton gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Skeleton"
 * "Last-Translator: "
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_SKELETON_NAME', "Skeleton");
define('_EN_SKELETON_DESCRIPTION', "A base gadget to use for new gadgets.");
define('_EN_SKELETON_ACTION_DEFAULT', "Default Action");
define('_EN_SKELETON_ACTION_DISPLAY', "Display Version");
define('_EN_SKELETON_ACTION_DISPLAY_DESC', "Displays the version number of your Jaws install.");
define('_EN_SKELETON_DISPLAY_MESSAGE', "You are running Jaws {0}"); // {0} = Jaws version
define('_EN_SKELETON_ADMIN_MESSAGE', "This gadget is just an example, so it doesn't have a Control Panel gadget.");