<?php
/**
 * Meta Data
 *
 * "Project-Id-Version: Phoo"
 * "Last-Translator: Francesc D. Subirats <fsubirats@gmail.com>"
 * "Language-Team: CA"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_CA_PHOO_NAME', "Organitzador de Fotos");
define('_CA_PHOO_DESCRIPTION', "És un organizador de fotos per al lloc web");
define('_CA_PHOO_DEFAULT_VIEW', "Vista per defecte");
define('_CA_PHOO_ALBUM_LIST', "Llista de Àlbums");
define('_CA_PHOO_PHOTOBLOG', "Fotobloc");
define('_CA_PHOO_RANDOM_IMAGE', "Imatge aleatòria");
define('_CA_PHOO_RANDOM_IMAGE_DESC', "Mostra una imatge aleatòria de qualsevol àlbum");
define('_CA_PHOO_MOBLOG', "Mobloc");
define('_CA_PHOO_MOBLOG_DESC', "Mostra l'àlbum Mobloc");
define('_CA_PHOO_ALBUMS', "Àlbums");
define('_CA_PHOO_ALBUMS_DESC', "Mostra tota la llista d'àlbums");
define('_CA_PHOO_UNKNOW_ALBUM', "No es troba a cap àlbum");
define('_CA_PHOO_WITHOUT_ALBUM', "Fotos òrfenes");
define('_CA_PHOO_WITHOUT_ALBUM_DESCRIPTION', "Fotos que no pertanyen a cap àlbum");
define('_CA_PHOO_NEW_ALBUM', "Àlbum nou");
define('_CA_PHOO_EDIT_ALBUM', "Edita l'àlbum");
define('_CA_PHOO_ALBUM_CREATION_DATE', "Data de creació {0}");
define('_CA_PHOO_EDIT_PHOTO', "Edita la foto");
define('_CA_PHOO_FIRST', "Primera");
define('_CA_PHOO_PREVIOUS', "Anterior");
define('_CA_PHOO_NEXT', "Següent");
define('_CA_PHOO_LAST', "Última");
define('_CA_PHOO_THUMBS', "Miniatures");
define('_CA_PHOO_WIDTH', "Amplada");
define('_CA_PHOO_HEIGHT', "Alçada");
define('_CA_PHOO_SIZE', "Mida");
define('_CA_PHOO_APERTURE', "Apertura");
define('_CA_PHOO_EXPOSURE_TIME', "Temps d'exposició");
define('_CA_PHOO_FOCAL_LENGTH', "Longitud focal");
define('_CA_PHOO_UNKNOWN_CAM', "Càmera desconeguda");
define('_CA_PHOO_LEAVE_COMMENT', "Deixa un comentari");
define('_CA_PHOO_PHOTOS', "Fotos");
define('_CA_PHOO_PHOTO', "Foto {0}");
define('_CA_PHOO_PHOTO_COUNTER', "Foto {0} de {0}");
define('_CA_PHOO_PHOTOS_COUNT', "{0} fotos");
define('_CA_PHOO_COMMENTS', "Comentaris");
define('_CA_PHOO_ADDITIONAL_SETTINGS', "Ajustaments addicionals");
define('_CA_PHOO_IMPORT', "Importa");
define('_CA_PHOO_NUM_PHOTOS_ALBUM', "{0} imatges a l'àlbum");
define('_CA_PHOO_UPLOAD_PHOTOS', "Pujar fotos");
define('_CA_PHOO_EDIT_DESCRIPTION', "Edita la descripció");
define('_CA_PHOO_DELETE_ALBUM_CONFIRM', "Esteu segur que voleu esborrar aquest àlbum?");
define('_CA_PHOO_NOT_PUBLISHED', "Sense publicar");
define('_CA_PHOO_START_UPLOADING_PHOTOS', "Comença a pujar fotos");
define('_CA_PHOO_INEXISTENT_ALBUM', "L'àlbum no existeix.");
define('_CA_PHOO_EMPTY_ALBUMSET', "No hi ha àlbums.");
define('_CA_PHOO_PHOTO_TITLE', "Títol de la foto.");
define('_CA_PHOO_PHOTO_DESCRIPTION', "Descripció de la foto.");
define('_CA_PHOO_POSTED_BY', "Publicat per");
define('_CA_PHOO_ALBUM', "Àlbum");
define('_CA_PHOO_ALLOW_COMMENTS', "Permetre els comentaris");
define('_CA_PHOO_STATUS', "Estat");
define('_CA_PHOO_HIDDEN', "Esborrany");
define('_CA_PHOO_PUBLISHED', "Publicat");
define('_CA_PHOO_DELETE_PHOTO_CONFIRM', "Esteu segur que voleu esborrar aquesta foto?");
define('_CA_PHOO_UPLOAD_FAILURE', "No s'ha pogut pujar la foto.");
define('_CA_PHOO_ALBUM_NAME', "Nom de l'àlbum");
define('_CA_PHOO_ALBUM_DESC', "Descripció de l'àlbum");
define('_CA_PHOO_CREATE_NEW_ALBUM', "Crea un nou àlbum");
define('_CA_PHOO_DELETE_ALBUM', "Esborrar l'àlbum");
define('_CA_PHOO_KEEP_ORIGINAL', "Conserva la imatge original");
define('_CA_PHOO_SHOW_EXIF_INFO', "Mostra la informació d'EXIF");
define('_CA_PHOO_EXIF_INFO', "Informacié EXIF");
define('_CA_PHOO_SAVE_CHANGES', "Desa els canvis");
define('_CA_PHOO_COMMENTS_WHERE', "Comentaris on");
define('_CA_PHOO_ID', "ID és");
define('_CA_PHOO_TITLE_CONTAINS', "El títol conté");
define('_CA_PHOO_COMMENT_CONTAINS', "Els comentaris contenen");
define('_CA_PHOO_NAME_CONTAINS', "El nom conté");
define('_CA_PHOO_EMAIL_CONTAINS', "L'adreça electrònica conté");
define('_CA_PHOO_URL_CONTAINS', "L'URL conté");
define('_CA_PHOO_IP_CONTAINS', "L'adreça IP conté");
define('_CA_PHOO_FILTER', "Filtre");
define('_CA_PHOO_IP_ADDRESS', "Adreça IP");
define('_CA_PHOO_COMMENT', "Comentari");
define('_CA_PHOO_UPDATE_COMMENT', "Modifica el comentari");
define('_CA_PHOO_DELETE_COMMENT', "Esborra el comentari");
define('_CA_PHOO_REPLY', "Respondre");
define('_CA_PHOO_SEND_COMMENT', "Envia els comentaris");
define('_CA_PHOO_RECENT_COMMENTS', "Comentaris recents");
define('_CA_PHOO_RECENT_COMMENTS_DESC', "Mostra el resum dels comentaris recents.");
define('_CA_PHOO_SAVE_SETTINGS', "Desa els ajustaments");
define('_CA_PHOO_RESIZE_METHOD', "Mètode de redimensió");
define('_CA_PHOO_DEFAULT_STATUS', "Estat per defecte");
define('_CA_PHOO_MOBLOG_ALBUM', "Àlbum Mobloc");
define('_CA_PHOO_MOBLOG_LIMIT', "Límit del Mobloc");
define('_CA_PHOO_PHOTOBLOG_ALBUM', "Àlbum Fotobloc");
define('_CA_PHOO_PHOTOBLOG_LIMIT', "Límit del Fotobloc");
define('_CA_PHOO_THUMBNAIL_LIMIT', "Miniatures per pàgina");
define('_CA_PHOO_FULL_ALBUM', "Tot l'àlbum");
define('_CA_PHOO_READY_TO_IMPORT', "Llest per a importar {0} imatges");
define('_CA_PHOO_IMPORT_MESSAGE', "Importa les imatges seleccionades a ");
define('_CA_PHOO_NO_IMAGES_TO_IMPORT', "No hi ha imatges per a importar");
define('_CA_PHOO_IMPORT_INSTRUCTIONS', "Copia o puja les imatges al directori data/phoo/import, desprès torneu a aquesta opció per a importar les imatges.");
define('_CA_PHOO_IMPORTING', "Important images");
define('_CA_PHOO_IMPORTING_WARNING', "No tanqui aquesta finestra fins que s'importen totes les imatges");
define('_CA_PHOO_FINISHED', "Finalitzat");
define('_CA_PHOO_DELETE_MASSIVE_COMMENTS', "Esteu segur que voleu esborrar aquests comentaris?");
define('_CA_PHOO_MODERATE_COMMENTS', "Modera els comentaris");
define('_CA_PHOO_COMMENT_IS_SPAM', "El comentari s'ha marcat com brossa.");
define('_CA_PHOO_COMMENT_IS_WAITING', "El comentari està esperant moderació.");
define('_CA_PHOO_ALBUMS_ORDER_TYPE', "Tipus d'ordre per a els àlbums");
define('_CA_PHOO_PHOTOS_ORDER_TYPE', "Tipus d'ordre per a les fotos");
define('_CA_PHOO_ORDER_TYPE_BY_CREATETIME', "Per hora de creació");
define('_CA_PHOO_ORDER_TYPE_BY_NAME', "Per nom");
define('_CA_PHOO_ORDER_TYPE_BY_ID', "Per ID");
define('_CA_PHOO_ADD_ANOTHER_PHOTO', "Afegeix un altra foto");
define('_CA_PHOO_COMMENT_MAIL_VISIT_URL', "<a href=\"{0}\">{1}</a>");
define('_CA_PHOO_ALBUM_EMPTY', "Àlbum vuit");
define('_CA_PHOO_CSS_CLASS', "Classe CSS");
define('_CA_PHOO_THUMB', "Miniatura");
define('_CA_PHOO_MEDIUM', "Mitjana");
define('_CA_PHOO_ORIGINAL', "Original");
define('_CA_PHOO_INSERTIMAGE', "Insereix una imatge");
define('_CA_PHOO_IMAGE_LABEL', "Imatge");
define('_CA_PHOO_SELECT_OTHER_IMAGE', "Seleccioneu un altra imatge");
define('_CA_PHOO_INCLUDE_LINK_TO_ALBUM', "Incloure un enllaç a l'àlbum");
define('_CA_PHOO_ACL_DEFAULT', "Administra l'organitzador de fotos");
define('_CA_PHOO_ACL_ADDPHOTOS', "Afegeix fotos noves");
define('_CA_PHOO_ACL_DELETEPHOTOS', "Esborra les fotos");
define('_CA_PHOO_ACL_MANAGEPHOTOS', "Administra les fotos");
define('_CA_PHOO_ACL_MODIFYOTHERSPHOTOS', "Modificar fotos d'altres usuaris");
define('_CA_PHOO_ACL_MANAGECOMMENTS', "Administra els comentaris");
define('_CA_PHOO_ACL_MANAGEALBUMS', "Administra els àlbums");
define('_CA_PHOO_ACL_SETTINGS', "Modifica la configuració");
define('_CA_PHOO_ACL_IMPORT', "Importa fotos");
define('_CA_PHOO_ERROR_ADVANCEDSEARCH_QUERY', "S'ha produït un problema en executar la recerca avançada de l'organitzador de fotos.");
define('_CA_PHOO_ERROR_GETMOBLOG', "S'ha produït un problema en executar la recerca de Mobloc.");
define('_CA_PHOO_ERROR_ALBUMLIST', "S'ha produït un problema en cercar la llista d'àlbums.");
define('_CA_PHOO_ERROR_RANDOMIMAGE', "S'ha produït un problema en escollir una imatge aleatòria de l'Organitzador de fotos.");
define('_CA_PHOO_ERROR_ALBUMINFO', "S'ha produït un problema en obtenir la informació d'aquest àlbum.");
define('_CA_PHOO_ERROR_ALBUMS', "S'ha produït un problema en escollir àlbums per {0}.");
define('_CA_PHOO_ERROR_GETALBUM', "S'ha produït un problema en obtenir l'àlbum.");
define('_CA_PHOO_ERROR_GETIMAGE', "S'ha produït un problema en obtenir la imatge.");
define('_CA_PHOO_ERROR_GETIMAGEENTRY', "S'ha produït un problema en obtenir l'entrada de la imatge.");
define('_CA_PHOO_ERROR_CANT_UPLOAD_PHOTO_EXT', "Aquest fitxer no es vàlid. Podeu usar els formats (gif|jpeg|png).");
define('_CA_PHOO_ERROR_CANT_UPDATE_PHOTO', "S'ha produït un problema en actualitzar la imatge.");
define('_CA_PHOO_ERROR_CANT_UPLOAD_PHOTO', "S'ha produït un problema en pujar la foto.");
define('_CA_PHOO_ERROR_CANT_DELETE_PHOTO', "S'ha produït un problema en esborrar la foto.");
define('_CA_PHOO_ERROR_CANT_ADD_ENTRY_TO_ALBUM', "S'ha produït un problema en esborrar la entrada del àlbum.");
define('_CA_PHOO_ERROR_GETASPORTRAIT', "S'ha produït un problema en intentar obtenir l'àlbum com a retrat.");
define('_CA_PHOO_ERROR_ALBUM_NOT_UPDATED', "S'ha produït un problema en actualitzar l'àlbum.");
define('_CA_PHOO_ERROR_ALBUM_NOT_DELETED', "S'ha produït un problema en esborrar l'àlbum.");
define('_CA_PHOO_ERROR_ALBUM_NOT_CREATED', "S'ha produït un problema en crear l'àlbum.");
define('_CA_PHOO_ERROR_GETCOMMENTS', "S'ha produït un problema en obtenir els comentaris.");
define('_CA_PHOO_ERROR_RECENTCOMMENTS', "S'ha produït un problema en obtenir els comentaris recents.");
define('_CA_PHOO_ERROR_FILETEREDCOMMENTS', "S'ha produït un problema en obtenir els comentaris filtrats.");
define('_CA_PHOO_ERROR_GETCOMMENT', "S'ha produït un problema en obtenir el comentari.");
define('_CA_PHOO_ERROR_CANT_ADD_COMMENT', "S'ha produït un problema en afegir el comentari.");
define('_CA_PHOO_ERROR_CANT_UPDATE_COMMENT', "S'ha produït un problema en modificar el comentari.");
define('_CA_PHOO_ERROR_CANT_DELETE_COMMENT', "S'ha produït un problema en esborrar el comentari.");
define('_CA_PHOO_ERROR_CANT_UPDATE_SETTINGS', "S'ha produït un problema en modificar els ajustaments.");
define('_CA_PHOO_ERROR_CANT_DELETE_IMAGE', "S'ha produït un problema en esborrar la imatge.");
define('_CA_PHOO_ERROR_CANT_FETCH_SETTINGS', "S'ha produït un problema en obtenir els ajustaments.");
define('_CA_PHOO_ALBUM_CREATED', "L'àlbum s'ha creat.");
define('_CA_PHOO_ALBUMS_UPDATED', "Els àlbums s'han modificat.");
define('_CA_PHOO_ALBUM_UPDATED', "L'àlbum s'ha modificat.");
define('_CA_PHOO_ALBUM_DELETED', "L'àlbum s'ha esborrat.");
define('_CA_PHOO_PHOTO_ADDED', "La foto s'ha afegit.");
define('_CA_PHOO_PHOTO_UPDATED', "La foto s'ha actualitzat.");
define('_CA_PHOO_PHOTO_DELETED', "La foto s'ha esborrat.");
define('_CA_PHOO_COMMENT_UPDATED', "El comentari s'ha actualitzat.");
define('_CA_PHOO_COMMENT_DELETED', "El comentari s'ha esborrat.");
define('_CA_PHOO_SETTINGS_UPDATED', "Els ajustaments s'han modificat.");
